### ISSUE TITLE
vonDecode() error

### ISSUE THREAD

**Issue by itswonky** [wiremod/wire#1018]
So while trying to make a credit system E2, I kept receiving an error while trying to use vonDecode to convert a string into an array. I wrote up a simple E2 code and got this.

Error:
sv: von.decode error: lua/wire/von.lua:130: vON: Malformed data... Can't find a proper type definition. Char#1:h

E2 Code:
@inputs Test:array
Test = vonDecode("hello")

**Comment by BoggLog** [comment]
You should use vonEncode for that... 

but that's not good anyway

**Comment by itswonky** [comment]
I'm turning a string into an array, not an array into a string.

**Comment by Divran** [comment]
um
wat

**Comment by BoggLog** [comment]
@itswonky I meant your string is not valid encoded data for vonDecode, that's why it errors.
Try this:
ValidData = vonEncode( array(1=1,2="something") ) #getting array encoded as string, valid for von
DecodedArray = vonDecode(ValidData) #getting back encoded array from valid string

@Divran I don't think vonDecode should error e2 anyway, it could just return empty array

**Comment by Divran** [comment]
perhaps

**Comment by itswonky** [comment]
oh so i gotta encode it first alright.
well, just in case u know.

how would i make a string with each letter/number being on a separate index.
ex.
my string is "big ol test"
how would i convert it to
["b","i","g","o","l","t","e","s","t"]
would really  appreciate it, thanks

**Comment by oldmud0** [comment]
Uh, what about the null terminator?

**Comment by immibis** [comment]
@oldmud0 What's a null terminator? Lua has no concept of a null terminator.
