### ISSUE TITLE
E2 UDF return type error

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#1022]
For data types such as vector and matrix where there're 3 types for each, UDFs doesn't take the type it's in into effect so running code like this...

```function matrix testing()
{   
    return matrix4()
}```
or

```function vector testing()
{   
    return vec4()
}```

Will return this error in e2...

```addons/wiremod/lua/entities/gmod_wire_expression2/base/compiler.lua:69: attempt to index a nil value```

**Comment by AbigailBuccaneer** [comment]
@bigdogmat so a function like `function number testing() { return vec4() }` will give a more sensible error?

**Comment by bigdogmat** [comment]
Yes it'd error out with a regular return type error, but when mixing vector types or matrix types that's when it throws this error.

**Comment by TomyLobo** [comment]
does this apply to all table-based types or only to a subset of them?
rangerdata, for instance, is something to check

**Comment by AbigailBuccaneer** [comment]
```
> print(tps_pretty("ns"))
normal, string
> print(tps_pretty("xv4"))

[ERROR] addons/wiremod/lua/entities/gmod_wire_expression2/base/compiler.lua:69: attempt to index a nil value
  ...
```

**Comment by AbigailBuccaneer** [comment]
The bug is that `tps_pretty` didn't work when passed a single extended type. So this was happening for `xv4` but not `t`, etc.

For the record, `function number testing() { return vec4() }` also shows the same issue - it's nothing to do with mixing vector types, it's just that when there's a type mismatch returning or expecting an extended type that things break.
