### ISSUE TITLE
[E2 editor] Clipboard (using context menu) not shared between tabs

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#1028]
To reproduce, copy something in one tab, either from context menu or with Ctrl+C, then paste it in another tab. Context menu will paste something copied before or last copied from current tab, while Ctrl+V will paste what you have just copied...

**Comment by TomyLobo** [comment]
What's an exchange buffer?
Are you talking about the clipboard?

**Comment by bigdogmat** [comment]
This happens because the copy functions are all done within the "Expression2Editor" panel and each tab uses a different one. This can be fixed by instead of making the clipboard an index in the panel, just make it a local variable to the file. I would make a pr to change this, though I'm not sure if it's the best way to fix it.

It would also fix clipboard text across editors as well.
