### ISSUE TITLE
Improved egpOrder API

### ISSUE THREAD

**Issue by AbigailBuccaneer** [wiremod/wire#1057]
As mentioned in #1056, `egpOrder` works but has a bad API - to the point where the original author of it recommends not using it.

@TomyLobo says:

> How about having API for:
> - Bring A to top
> - Send B to bottom
> - Put A just above B
> - Put A just below B

**Comment by Divran** [comment]
How should this be implemented? Should egpOrder have a third argument with these four options? Like `WLK:egpOrder(ID,OtherID,Third argument)`
or should we have a different function for each
```
WLK:egpOrderTop(ID)
WLK:egpOrderBottom(ID)
WLK:egpOrderAbove(ID,OtherID)
WLK:egpOrderBelow(ID,OtherID)
```

If we change the behavior of the current function, old E2s will break. Because I checked the code, and the second argument to `WLK:egpOrder(ID,Position)` is actually not an object ID. It's the new wanted position in the rendering array (meaning position 1 will render on top, and position "number-of-objects" will render last). So if we change this so that the second argument to `egpOrder` is an object ID, every E2 that currently uses it will break.

**Comment by AbigailBuccaneer** [comment]
Yes, I'd argue to leave `egpOrder` as-is and make four new functions (or one function with an extra enum parameter).

**Comment by TomyLobo** [comment]
Can we hide stuff from autocomplete and everything?

**Comment by Divran** [comment]
ehhh E2 has no way to hide functions without removing them

**Comment by Illutax** [comment]
Actually if you fully unterstand how egpOrder currently works, it actually work great. But the suggested change can be added under new names like egpOrderTop(index) or egpOrderAfter(index, index). Is it a thing to add an parameter like in print(n,s) ?? For example 
    
Egp:egpOrder(_top_, 1)

**Comment by Divran** [comment]
Yeah the main problem of adding these new functions would be that the old one works off of rendering order, while we're suggesting these new ones will use object index, with "before/after" options. I prefer the new ones as well, but it might be confusing to have functions with similar names that work completely differnetly. What if they try to use an object index as argument to `egpOrder` and it doesn't work? Actually, that might be what people are already doing...

**Comment by Illutax** [comment]
EgpReorder(int position, int index [, int index])

**Comment by TomyLobo** [comment]
Do we really want constants there?
That'd be like the winapi :D

**Comment by CaptainPRICE** [comment]
> That'd be like the winapi

With enums it would look nicer :D

**Comment by TomyLobo** [comment]
or just plain constants... _EGP_ORDER_TOPMOST
