### ISSUE TITLE
Redo op cost for array functions

### ISSUE THREAD

**Issue by bigdogmat** [wiremod/wire#1061]
After talking to Divran about the op cost of array functions and why they cost more than the same function for tables he said that they just use the wrong cost. 

This being said I think the op cost should be either the same as the table cost or less as they're arrays. At the moment the only real reason to use arrays is when working with the default functions in E2, as all the functions cost ~5 more, so you'd just be wasting ops.

Another example of this is iterating through an ordered array vs ordered table. Each test is using 5 number entries and a numeric for loop.
Array - 202
Table - 181

I would've tested foreach loops but I don't believe they take into account the op cost for getting the value as for the same test above it costs 139 ops for arrays. And for the time being you can't iterate over numeric indexes in tables.

**Comment by Ruuttu** [comment]
+1 
Simply accessing from an array (e.g. return myArray[1,number]) is almost three times as costly ops-wise as "accessing" a normal variable (unscientific test). I don't know if that makes technical sense, but it feels a little unfair to me as a user. In extreme cases, one might be tempted to have 40 separate variables and a ton of duplicated code instead of using an array just so you don't blow the budget. Which would be horrible :)

**Comment by Divran** [comment]
yay more issues that have been completely forgotten
