### ISSUE TITLE
Add faster preformed traces in wiremod officially

### ISSUE THREAD

**Issue by dvdvideo1234** [wiremod/wire#1123]
I've posted more on the subject here.
http://www.wiremod.com/forum/ideas-suggestions/35567-attaching-sensors-entities.html
I need that for my maglevs to lag the server less when playing on train maps.
For 8 rangers in total I am getting vast increase in performance ( 110 ops for the wiremod sensor and 70 ops for mine )
This may be put in ..entities/wire_expression2/core/custom/flash_sensors.lua

https://github.com/dvdvideo1234/ScriptsWireE2/blob/master/Bridges/flash_sensors.lua

What do you guys think, may I create a patch for it ?

**Comment by Nebual** [comment]
I believe the majority of the performance impact on the server comes from the util.TraceLine function, which is likely effectively hundreds of ops, rather than from lua primitive array instantiation. In either case, if you truly wanted to "cache" a trace request object, your sampleTrace(s) function could just be two lines: 
local trData = findSensor(...) 
util.TraceLine(trData) 

Which I could see some value in... But to be accepted into official wire, it should use the same E2 types and methods as regular traces. Your variable reuse in findSensor is also rather troubling, just return false if any input parameter is missing, and then return the whole chain in one operation.

**Comment by AbigailBuccaneer** [comment]
> For 8 rangers in total I am getting vast increase in performance

E2 ops are not a useful measure of performance - we could just manually every function to 0 ops. Can you provide actual performance benchmarking?

**Comment by immibis** [comment]
We could set e2 functions to negative ops, and then **clearly** executing those functions makes the server run faster.

**Comment by TomyLobo** [comment]
@immibis ...wat

**Comment by immibis** [comment]
@TomyLobo We could set some E2 functions to negative ops, and then, obviously, executing those functions will make the server run faster.

**Comment by dvdvideo1234** [comment]
The whole idea is to "attach" a sensor to the entity using a local position and direction, so for example for a maglev to be easier to  manage the sensors.

The E2 source used for testing

`@name Tracer Test
@inputs 
@outputs Dist Tct Cre Est Time
@persist E:entity Len End Time Tct Rep Cre Est Tst
@trigger 
@model models/props_phx/gears/bevel9.mdl

runOnTick(1)

if(first() || dupefinished())
{
    Rep = 200 
    
    Tst = 100
    End = 50
    Len = 15
    Est = 0
    Cre = Rep
    E = entity()
    E:addTracer("TEST",vec(0,0,0),vec(0,0,-1),Len)
}
if(Cre)
{
    if(Tct)
    {
        T = systime()
        Cnt = End
        while(Cnt > 0)
        {
          # BEGIN
        
          # Flash Sensors
          # E:smpTracer("TEST")
          # Dist = E:getTracerDistance("TEST")
          
          # Wire ranger
          Dist = rangerOffset(Len,E:pos(),E:up()):distance()
        
          # END
          Cnt--
        }
        Time = Time + (systime() - T)
        Tct--
    }else{
        Tct = Tst
        if(Time > 0)
        {
            Est = Est + Time
            Cre--
            if(!Cre){ print("Elapsed: "+ (Est/Rep)) }
            Time = 0
        }
    }
}`

Flash sensors: 0.10629411670619
Wire ranger: 0.18506070641881

Well using the high accurate time is still ... 80% faster

**Comment by AbigailBuccaneer** [comment]
* This doesn't fit nicely at all with the existing ranger library - at the very least it should return the same RangerData structure. I'd much rather see a pull request to extend the current ranger library. For example, the current global `ranger` functions could internally act on a ranger object similar to those created by your library. (There's also inconsistent terminology - the current ones are called rangers, and you call `ranger` to trace them, your ones are called tracers and you call `smpTracer` to trace them.)
* The only way to create a tracer with this that isn't parented to something is `entity(1):addTracer(...)`, which is silly.
* There's no limit on the number of tracers an E2 could create, and they're not garbage collected. So something like `runOnTick(1); entity():addTracer(toString(I++))` would eat the server's memory. (This isn't necessarily a huge issue because we probably are susceptible to this in many other places, and there are nastier ways to kill a server.)

**Comment by Divran** [comment]
So with 50 rangers you're getting a 0.08 second increase in speed? If you want to do this because your maglev lags the server, I think you need to fix all of your other code in your maglev before thinking about traces.

**Comment by dvdvideo1234** [comment]
Well, in that case I was thinking to code a sampler of a ranger with local coordinates to the entity. What do you guys think
```
if(first() || dupefinished())
{
    runOnTick(1)
    Filter = entity()
    RD = rangerOffset(Position,Direction,Length)
}

# Sample the ranger start/endpos relative to the entity given
# If no entity is given, then traces are using (Position,Direction,Length)
# In ranger:sample(Entity/Void) there will be a traceLine() finction
RD:sample(Filter) 

# Get the distance
D = RD:distance()
```

**Comment by Divran** [comment]
So in the above example, that means the only performance increase you'll
get is from running toWorld in Lua instead of in E2? That's not going to be
a lot. However, if we do add that, let me modify your idea a tiny bit. We
could instead add "entity:rangerOffset(...)" which would have all the same
arguments and overloads as the regular rangerOffset, except all the
positions and directions would be local to the entity.

On Tue, May 24, 2016 at 10:06 AM, Deyan Dobromirov <notifications@github.com

**Comment by dvdvideo1234** [comment]
But isn't it going to create a new ranger every iteration, though the Idea is quite good.

**Comment by Divran** [comment]
So does yours. What's the difference?

On Tue, May 24, 2016 at 11:21 AM, Deyan Dobromirov <notifications@github.com

**Comment by dvdvideo1234** [comment]
Allocates and initialize memory for the ranger once by calling E:addTracer("Down").
Gather all the data of the already allocated once sensor by calling E:smpTracer("Down") and only refreshing the allocated sensor with the coordinate system of the entity.
Read the distance associated with that sensor name getTracerDistance("Down")

**Comment by dvdvideo1234** [comment]
I've written a better system and this PR is not needed
