### ISSUE TITLE
egpDrawTopLeft inconsistent

### ISSUE THREAD

**Issue by Damianu** [wiremod/wire#1131]
There are many problems with EGP's object origins..

Problems:
- Some objects are centered by default and some arent, it's just confusing.
    Examples: Text is centered, TextLayout isn't(wtf?)
- DrawTopLeft doesnt change parent's origin(0,0)
Best way of solving it in my opinion:
- Add DrawTopLeft(2) to do not break current code and make it easier for future coding..
- Make egpParent's origin at top left corner when EGP is in 2nd TopLeftMode

PS. If I may ask, why is center-mode default?

**Comment by Divran** [comment]
Center is default because that's the way it is in gmod. It was far easier to implement. Text layout is the only object that isn't centered, and that's only because text layout is not a default gmod element - it's a small custom library within wiremod. There were plans to make use of a better text layout library, but it was never finished, so the old one stayed.

I never planned on adding drawTopLeft at all, but a lot of people were bitching on the forums and here on github that they were too lazy to use +size/2, so I hacked together the top left function. In hindsight, I should have told them to shut the fuck up and never added it.

**Comment by AbigailBuccaneer** [comment]
See #497 for some 'exciting' history of this inconsistency. The resolution at the time was "don't use `egpDrawTopLeft`".
