### ISSUE TITLE
Add E2 'number=isExtensionLoaded(s)' and 'array=extensions()' functions

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1138]
Currently in Expression 2 there is no function to test whether some extension is currently installed/enabled on the server, other than using ifdef/ifndef pre-processor directives..
I have a small E2 library just for this, so I would finally love to see them as builtin functions.

**Comment by TomyLobo** [comment]
what is your use case?

**Comment by CaptainPRICE** [comment]
@TomyLobo My use case for this is that I can have a fallback/legacy code (or otherwise simply throw a user-friendly error)..

**Comment by TomyLobo** [comment]
no you can't. If you're missing functions, you won't be able to compile your code.
That's why I created the #ifdef system where you can directly check if a certain function exists, regardless of origin.
It even works if an extension is renamed, provided its functions stay the same.

**Comment by Divran** [comment]
What @TomyLobo said. If you attempt to use a function that doesn't exist, you won't even be able to spawn your E2 at all. So for example, if you were to do this:
```
if (isExtensionLoaded("prop core")) {
    propSpawn("stuff",things,0)
} else {
    print("user friendly error")
}
```
you wouldn't be able to spawn the E2.

Even if this wasn't the case, ifdef is much more powerful anyway, since some servers may use custom scripts that disable certain functions in an extension but not others.

But if you still want something like this, just use `#include` with the code below

```
@persist LoadedExtensions:table
if (first()|duped()) {
    function isExtensionLoaded(Name:string) {
        return LoadedExtensions[Name,number]
    }

    #ifdef propSpawn(S,V,N)
        LoadedExtensions["prop core",number] = 1
    #endif

    #ifdef E:remoteUpload(S)
        LoadedExtensions["remote upload",number] = 1
    #endif

    #... and so on, for each extension you want to check
}
```
