### ISSUE TITLE
E2: Not possible to store tables/arrays in an entity's table ?

### ISSUE THREAD

**Issue by guillaume-dorczynski** [wiremod/wire#1152]
Hi,

It is possible to do for example

```
local E = entity()
E["myNumber",number] = 1
```

But storing a table (or array):

```
E["myTable",table] = table()
```

results in error No such operator: set entity[string, table]

I believe this is the part of code related: https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/entity.lua#L794

Any reason why t and r are not allowed ?

**Comment by adosikas** [comment]
I ran into this annoying issue too.

A quick workaround is
```E["mytable",string]=jsonEncode(table()
MyTable=jsonDecodeTable(E["mytable",string])
```

Although that shouldn't be needed IMO.

**Comment by Divran** [comment]
Easiest way is probably this

```
@persist EntVals:table

if (first()|duped()) {
    EntVal = table()

    function entity:setTable( Key:string, Tab:table ) {
        EntVal[This:id(),table] = Tab
    }
    function table entity:getTable( Key:string ) {
        return EntVal[This:id(),table]
    }
    function entity:setArray( Key:string, Arr:array ) {
        EntVal[This:id(),array] = Tab
    }
    function array entity:getArray( Key:string ) {
        return EntVal[This:id(),array]
    }
}

entity():setTable( "Wut", table(1,2,3) )
printTable(entity():getTable( "Wut" ))
```

**Comment by bigdogmat** [comment]
While that would work, it'd also make entries stay even after the entity is deleted, which also means any entity spawned that has the same id as the despawned entity will now carry its properties.

As for why array and table types were disabled I don't know. @syranide was one the to disable them, 6d5ab48985015b09b8eff500b280d14efa22ab58

**Comment by syranide** [comment]
@bigdogmat IIRC it's because they are mutable data types, so if you get a reference to an array/table from an entity then any modifications to it will apply to the array/table on the entity as well including all other references to it as well (which may be held by entirely different E2s). For many this behavior would come as a complete surprise and be super hard to debug as it differs from how E2 otherwise treats arrays/tables with regards to input/output etc (copying).

A secondary concern was probably also memory management and performance, avoiding careless littering of data on entities which could quickly become large amounts of memory and expensive copying for something that seems innocent. Only assigning individual properties means you can still kind of achieve the same thing, you just have to be explicit and work extra hard for it.

**Comment by GanjaFarmer** [comment]
@adosikas Yes I guess it's the best that can be done. My table is small enough and doesn't contain subtables so I think I will just store individual entries.

@Divran I agree with bigdogmat, there is that issue with your workaround. It would work if you can cleanup the table when necessary, but that's not my case.

@syranide Thanks for explanation as to why this feature have been disabled. As always, useful things can be exploited to do bad things, but tables can already be abused so I don't think that would make a difference. Just my two euro cents ;)

**Comment by chinoto** [comment]
I thought arrays were done by value and tables by reference? A workaround, in case this becomes a wontfix, would be to just store your values in a table with E:id() as your key, especially if it's only one E2 that is working with the data, otherwise use [global variables](http://wiki.wiremod.com/wiki/Expression_2#Global_Variables) to make it available to all your E2s (and others if wanted).

**Comment by bigdogmat** [comment]
> A workaround, in case this becomes a wontfix, would be to just store your values in a table with E:id() as your key

@Divran Pointed this out a few posts above, though it has an issues. 

When an entity is deleted it doesn't get deleted from the table, this is obvious because we aren't storing the information by entity reference. The issue comes into play when an entity is spawned and it takes the ent index of an old entity, this could be worked around but still isn't a perfect solution.

Considering the issues @syranide pointed out above an easy solution would be to have our own table, and store the information by entity reference on that.

**Comment by syranide** [comment]
I'm still not sure what prevents you from just storing the stuff directly on the entity? Why does it need to be in a table on the entity?

**Comment by bigdogmat** [comment]
You can iterate through an entity, nor can you use numerical keys if I remember correctly. Overall it just allows for an easier management system.

**Comment by adosikas** [comment]
@syranide But table as input and outputs **are** shared referenced instead of cloned. Same with sending a table via data signals. Changing one is mirrored on the other side. And it is **very** useful to share data structures instantly and consistent between e2s (instead of constantly spamming datasignals, which would trigger seperate E2 executions).

Making tables in entites copies would be inconsistent.

**Comment by Divran** [comment]
>@syranide But table as input and outputs are shared referenced instead of cloned. Same with sending a table via data signals.

@adosikas it didn't used to be. E2 has been slowly moving to passing tables/arrays by reference over the last few years. Syranide hasn't been active in the community for that time :)

**Comment by thegrb93** [comment]
Not sure why it's not allowed, but it's intentional https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/entity.lua#L937

**Comment by thegrb93** [comment]
I don't see why. Maybe that table can be removed.

**Comment by syranide** [comment]
@thegrb93 https://github.com/wiremod/wire/issues/1152#issuecomment-227970049

Table references are shared, which might be a bit unituitive for some... however, I think this may still be the case, the bigger issue could be that tables and such sent over the wire-interface and so on will also share the same reference and can thus be very confusingly changed remotely.

Also, I'm not sure, but it might be that one of the types in that list is unsafe to modify (e.g. because you can get/fetch references to other peoples such instances and change them without their knowledge/permission).

**Comment by thegrb93** [comment]
The table is unique per e2

**Comment by thegrb93** [comment]
Also this should be refactored to store the data in the e2 data... This is a definite mem leak
