### ISSUE TITLE
E2: Add compile-time constant directive (@const)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1173]
This would allow to write constant values of type `number` and `string`.
For example (re-edited with **edit 4**):
```
@const _SECOND       = _MILLISECONDS / 1000.0  # This should still be valid even when _MILLISECONDS is defined afterwards (as it should compute the constant value at compile-time, so _SECOND should be equal to 1.0).
@const _DAYSINWEEK   = 7
@const _GOLDENRATIO  = 1.6180339887
@const _EARTHGRAVITY = 9.81
@const _MILLISECONDS = 1000.0
@const _GREET        = "Hello %s!\nWelcome to %s!"
@const _MYFORMAT     = _GREET + "\nReal-time: %d (0x%08X)"
@const _FOO          = "BAR"

print(_MILLISECONDS + "ms = " + _SECOND + "s")  # Prints "1000ms = 1s"
print(_GOLDENRATIO * 5.5)  # Prints "8.89918693785"
print(format(_MYFORMAT, owner():name(), _FOO, realtime(), realtime()))
#[
Hello CaptainPRICE!
Welcome to BAR!
Real-time: 600 (0x00000258)
]#
```

Strings? Oh, hell yeah! Cool example (with callable string):
```
@const Vector = "vec"  # Sweet! This looks like a static function to me (as a constant can not be changed during run-time).

local V = Vector(1.5, -2.2, 3.65)  # Gentlemen, I would love to see this implemented! :D
```

(Removed edit 3 from here, it didn't make any sense - read comments.)

Some invalid examples (re-edited with **edit 4**):
```
@inputs StrInput:string
@persist MyVariable
###############################################
@const GoldenRatio = 1.6180339887             # Validation: Constant name must start with low-line/underscore and any uppercase letter.
@const _E          = 50000                    # Validation: Constant '_E' already exists.
@const _INVALID    = realtime() + 1.2345      # Validation: Must be a constant value.
@const _HELLOWORLD = "Hello" + " " + "World"  # Validation: Must be a constant value.
@const _ENT        = entity()                 # Validation: Must be a constant value.
@const _STR        = StrInput                 # Validation: Must be a constant value.
@const _STR        = StrInput                 # Validation: Must be a constant value.
_INVALID           = 220                      # Validation: Assignment operator (=) must be preceded by variable.
_MYFORMAT          = "Nope!"                  # Validation: Assignment operator (=) must be preceded by variable.
_PI                = -9000                    # Validation: Assignment operator (=) must be preceded by variable.
###############################################
MyVariable = StrInput:toNumber(16)
```

**Edit (4)**:
Constant's name should be all uppercase and start with low-line/underscore character and any letter (A-Z), and then optionally it may be followed by any number of uppercase letter or digit or low-line/underscore.
Let me express it via Lua pattern:
`^(@_[A-Z][0-9A-Z_]*)$`
LEGAL examples: `_A`, `_FOO`, `_B4B3`, `_HELLO_WORLD`
ILLEGAL examples: `_`,  `__`,  `_123`,  `C`,  `_Nope_`,  `_\NOPE`

**Edit (1)**: On the second though, strings actually can be constants, too! Updated code examples above.
Aww! Please **do** this! :smile: 

**Edit (2)**:
You may be wondering why angle/array/bone/complex/effect/entity/gtable/matrix/matrix2/matrix4/quaternion/ranger/table/vector/vector2/vector4/wirelink can't be defined as a constant, too?
Well, in my opinion these should **not** be allowed constant types, because:
> Constants have to be compile-time constant, and the compiler can not evaluate your constructor/functions at compile-time.

It is actually better to have a white-list than a black-list for this ;)
```
local ALLOWED_CONST_TYPES = {
    "n",
    "s",
}
```

So.. Even, if you just try to imagine what it would result in (the following is of course invalid constant definition, at least it should be):
```
@const _ENT  = propSpawn("path/to/model.mdl", 0)  # I am not enclosing this with #ifdef directive, because I am assuming propcore E2 extension to be enabled..
@const _MAT4 = matrix4()
interval(1)

# P.S. I know interval timer is limited to 10ms at minimum. The reason why I've specified 1 rather than 10, is simply because Clamp will return faster. How? Because, it is how Clamp function works, it is (like a macro with) two if-statements (nano-optimization -- just how I like it XD). And if you specify a value that is in-range then the two if-statements are evaluated to false which would mean they run for "no reason"..
```

**Comment by bigdogmat** [comment]
Other than this being better performance wise if implemented correctly, I don't see the point.

**Comment by CaptainPRICE** [comment]
@bigdogmat 
> Other than this being better performance wise if implemented correctly

Agreed on this, because true and simple said :)

**Comment by oldmud0** [comment]
okay, what if you did
```
@persist B
@const _A = B + $B
```
error or no error?

**Comment by CaptainPRICE** [comment]
@oldmud0 That should error, obviously.

**Comment by oldmud0** [comment]
Uh, if it's a preprocessor directive, then that's NOT a compile-time constant. They are completely different types of constants.

**Comment by CaptainPRICE** [comment]
@oldmud0
> Uh, if it's a preprocessor directive, then that's NOT a compile-time constant.

What? What have you just said... I don't understand you (are you saying a constant value (`WHATEVER` in your case) is not a constant at compile-time?!).
  
I wrote "pre-processor directive", because of all these: `@name`, `@inputs`, `@outputs`, `@persist`, `@model`, `@trigger`, `@autoupdate`, `#include` and `#ifdef/#ifndef/#else/#endif` are called (pre-processor) directives in Expression 2 (E2) scripting (at least according to [wiki](http://wiki.wiremod.com/wiki/Expression_2#Syntax)).  
In E2 there is no macro functionality (like `#define` in C, which I think is called pre-processor directive there -- but that's C, and this is about E2).  
Now, since you compare it with C, I think you obviously got confused with E2's definition of "pre-processor directive".
So, let me try to enlighten you (the following is the correct equivalence between the three, since I think that you though you would use `#define` in C where you use `@const` in E2 -- which is wrong, the latter case you have posted is correct):
—————
C: `static const int _INT = 123;` (you have missed a `static` keyword)
C#: `const int _INT = 123;`
Java: `static final int _INT = 123;`
E2: `@const _INT = 123`
—————
C: `static const char _NAME[] = "Hello World";`
C#: `const string _NAME = "Hello World";`
Java: `static final String _NAME = "Hello World";`
E2: `@const _NAME = "Hello World"`
—————
`#define` (macros) in C is something different, it acts *similar* to `#include` in E2, and is not equivalent to this `@const` directive at all.
So, there is no such thing as `#define` in E2. Just like there is no `@name` in C.
Here is my conversion of your (invalid) C to (invalid) E2:
```
@persist A B  # Variable definitions.
# ERROR (at line 2): Can not convert '#define' statement.
@const _WHATEVER = A + B  # Validation: Must be a constant value.
A = 2
B = 3
```

Above E2 code is (*pretty much*) the correct/exact equivalent of the C code you have posted.
Heh.. And now you can see why is that not even a valid E2 (since C code is invalid in the first place).
So, I will repeat it once again (for this case) `@const` can not add two numbers (A and B) as they are not constants at compile-time, but variables (which is contradict of constant)!
  
What's called "pre-processor directives" in C does not necessarily have the same meaning in the context of E2.
  
Now.. Can you please explain to me, what do you mean or have I understood you correctly?

**Comment by oldmud0** [comment]
Yes, you have the right idea. What I am saying though is that you should call this a "compile-time constant" directive, not a "preprocessor directive." The reason is that this will cause confusion as to the behavior of `@const` because it will not substitute a constant to a value *before* compilation, but rather *during*. You will also notice that the word "preprocessor" in reference to directives has not been mentioned anywhere in the E2 docs to prevent this confusion (although yes, there is a `preprocessor.lua` that processes the directives).

I also don't really understand the "private static function" functionality you propose (first of all, if I understand correctly, combining E2s via `#define` will expose both the library and the E2 in the same scope, unless somebody comes up with some sort of namespaces), because if you want the behavior of a compile-time constant, then it does not make sense to suddenly allow constants to be substituted by their value and use this to call some method that may or may not be valid. Neither C, C#, nor Java endorse this behavior.

What about this?
```coffeescript
@const MYVECTOR "vec4"
@const START "("
@const END ")"

Vector = MYVECTOR START 0.25 0.1 0.36 0.55 END
```

I do believe that any type that is immutable should be allowed to be used as a constant.

And then yet again, C++ *can* evaluate at compile-time:
```c++
static const int a = 6, b = 7, c = a + b;
static const char* d = (char*)malloc(4);

int main() {
	// your code goes here
	printf("%d %d", c, &d);
	return 0;
}
```
So, it's not a preprocessor directive.

Now I do believe I am tangling myself in a mess so I'll stop now

**Comment by CaptainPRICE** [comment]
@oldmud0
> I also don't really understand the "private static function" functionality you propose (first of all, if I understand correctly, combining E2s via #define will expose both the library and the E2 in the same scope, unless somebody comes up with some sort of namespaces)

`#define`? I think you meant `#include`.
Indeed, forget about private/public. I think it should be "public", because when you `#include` a file (for example `#include "path/to/lib"`), it will concatenate all (pre-processor) directives other than `@name` directive (in this case, from "path/to/lib" file) to E2 which executes `#include "path/to/lib"` statement.
Also from what I remember, @Rusketh told me that E2s that are included are run in their own environment.

> What about this?
> ```
> @const MYVECTOR "vec4"
> @const START "("
> @const END ")"
> 
> Vector = MYVECTOR START 0.25 0.1 0.36 0.55 END
> ```

Uh. Not again.. You're again thinking of this as to be a macro.. [e2macros](https://github.com/notcake/e2macros). Though, that would be nice to have, but as `#macro` -- not `@const`.
> I do believe that any type that is immutable should be allowed to be used as a constant.

Yeah, I agree.

> And then yet again, C++ can evaluate at compile-time:
> 
> ```
> static const int a = 6, b = 7, c = a + b;
> static const char* d = (char*)malloc(4);
> 
> int main() {
>     // your code goes here
>     printf("%d %d", c, &d);
>     return 0;
> }
> ```

Now, that could be allowed, constants can evaluate themselves with other constants (of the exact/same immutable type of course, as casting (for example between string and number) is not done at compile-time rather run-time). So, yeah the following could be allowed (if you think more about it, now I see no reason why would it be illegal):
```
@const _A = 6
@const _B = 7
@const _C = _A + _B
```

Since this is compared to other languages, it should remain legal/valid, even if `_C` was defined before `_A` and/or `_B` constants (as that's basically allowed in C/C#/Java..).

**Comment by Divran** [comment]
Included E2s do run in their own environment, but they share persists, inputs, and outputs with all other included E2s.

**Comment by oldmud0** [comment]
I think instead of adding a `@const` directive, the interpreter (post-validation) should perform an optimization pass that would check for assignments of a variable to an immutable type (number, string). If the variable doesn't depend on a method, the variable can be considered constant, and all occurrences of that constant can be substituted by its value.

```
while running through all lines in code:
  if line is an assignment and does not call any functions and is not inside any control blocks:
    put the name of the variable and the expression to the right of it in a substitution table
for each (name, value) in the substitution table:
  if value is an expression:
    evaluate value:
      if the expression contains any names in the substitution table:
        (recurse)
    value is now evaluated value
  else:
    replace all occurrences of name in the entire code and values in substitution table
    delete name and value from substitution table
repeat until substitution table is empty
```
probably wrong but whatever

**Comment by Rusketh** [comment]
I agree with Divran, I added something similar to ExpAdv2 called the define directive

`@define: Example 22 + 7 ^ 6`

`print(Example)`

How ever this syntax was used not to speed up run-time by replicating a constant, instead to speed up compile time. The compiler would compile the instruction  _22 + 7 ^ 6_ and cache the completed instruction. After that every time the compiler finds a word token of _Example_ it would insert that pre-compiled instruction. I often use this method to create super fast 1 line functions because at run time its way faster to do it this way then to call a function, I can even use variables as arguments.

`int red, green, blue = 225, 255, 255
@define: RandomColor color(random(0, red), random(0, green), random(0, blue))
print(RandomColor)
blue = 0
print(RandomColor)`

Anyway that is what happened when I tried to make constants for ExpAdv2 and as you can see its ended up nothing like what is suggested here. That's simply because constants will not really give you anything new, in my opinion. I can see the point of this in other languages like C but that's a whole different ballpark. I would simply suggest to define your constant variables as you would any other variable and just don't reassign them.

Sorry but I have to side with Divran on this one.

**Comment by TomyLobo** [comment]
We have a system for compile-time-replaced constants, btw.
It's called ``E2Lib.registerConstant``. You would have to make the constant registry per-chip, though, before being able to add something like `@const`
