### ISSUE TITLE
Expression 2 applyForce server crash exploit/bug

### ISSUE THREAD

**Issue by theplayer232** [wiremod/wire#1189]
Video:
https://www.youtube.com/watch?v=F7qQWT7dKGU

Code:
```PHP
@name Rekt
if (first()) {
    runOnTick(1)
}
if (duped()) {
    selfDestruct()
}
entity():applyForce(vec(sinr(curtime() * 1e24) * 1e+24,cosr(curtime() * 1e24) * 1e+24,cosr(curtime() * 1e24) * 1e+24))
```
Unfreeze it after you spawn it and server should crash.

**Comment by oldmud0** [comment]
but why

**Comment by CaptainPRICE** [comment]
Duplicate of #1188.

@theplayer232 
Perhaps code just looks different to you, but it is the same function which causes it to crash. So, no need for two same issues.
Learn how to use [Markdown](https://guides.github.com/features/mastering-markdown/).

@oldmud0 
> Test it in raw Lua.

How, lol. You mean GLua.
Yep, tested and it crashed the server as expected:
```
if not SERVER or #player.GetAll() < 1 then return end

local EntID = 0  -- ID of entity to use.

local ent = NULL
if EntID > 0 then
    ent = Entity(EntID)
else
    local ply = player.GetAll()[1]
    if IsValid(ply) then
        local tr = ply:GetEyeTrace()
        ent = ents.Create("prop_physics")
        if IsValid(ent) then
            ent:SetModel("models/props_c17/canister02a.mdl")
            ent:SetPos(tr.HitPos + ply:GetAimVector() * -16)
            ent:Spawn()
        else
            ent = tr.Entity
        end
    end
end
if IsValid(ent) then
    local phys = ent:GetPhysicsObject()
    if IsValid(phys) then
        print("Crashing . . .", ent, phys)
        phys:EnableMotion(true)  -- Unfreeze.
        phys:ApplyForceCenter(Vector(1e54, 1e54, 1e54))  -- Apply abnormal force.
    else
        print("Pick entity with valid physics object", EntID)
    end
else
    print("Pick valid entity", EntID)
end
```

This should not be difficult to fix, simply clamp the vector should fix it, right?
And then just add ConVar to make it easy to control the behavior.

**Comment by theplayer232** [comment]
@CaptainPRICE Just wanted to mention on the reference you made to this issue report is that this doesn't actually require PropCore to be enabled to work, the other issue instead needs PropCore.

**Comment by CaptainPRICE** [comment]
Yeah, #1188 requires propcore just so it can spawn a prop. But, that code is **not** necessary to reproduce the issue, that means that part of code is unrelated as it is not required.
And here you seem you have minimized it. So, I'll go ahead and minimize it further:
```
interval(1)
entity():applyForce(vec(1e54))
```

See, that's minimized code, which is just enough to make it crash. No propcore.
Another words, propcore has nothing to do with this. so why mention/use it.
Now, with minimized code we can clearly see what it does.  :)

**Comment by oldmud0** [comment]
So clearly 1e54 is the magic value to kill the physics engine. What is the crash dump/engine error message?

**Comment by theplayer232** [comment]
Values that have worked: 1e+24 and 1e24
those two are the ones that causes extremely high number.

**Comment by bigdogmat** [comment]
Those represent the same number, the question here is what should we clamp the vectors to

**Comment by oldmud0** [comment]
The question is, should *we* be making the workarounds here? I do believe it's better to let the GMod developers know about this problem so that it can be resolved at the root. Also, what's stopping players from just dividing the force into two applyForce commands?

**Comment by shadowscion** [comment]
@oldmud0 I don't think wiremod should 'fix' this, it shouldn't really be possible to crash something bearing the name 'sandbox'; report it on the garrysmod github.

**Comment by CaptainPRICE** [comment]
@bigdogmat
> the question here is what should we clamp the vectors to

I've just wrote an automatic E2 to figure that:
```
# To change the model of E2, uncomment a line below if you wish. LED is the smallest model I know of, however I haven't noticed any changes, like "if using different model it wouldn't not crash", so that's nothing to do with crash issue.
#@model models/led.mdl

# We want these as outputs, right, so we can see them via Debugger (or whatever).
@outputs ExpressionGate:entity Busy E N:string F:vector

# Since there are no inputs, I'll just set trigger to none.
@trigger none

# I call this an "Automation pattern" (with timer)..  ;-)
if (clk("beginApplyForce") | clk("endApplyForce") | clk("prepareApplyForce") | clk("increment"))
{
    (clkName())()
}
elseif (first())
{
    ExpressionGate = entity()
    ExpressionGate:setMass(1)  # That's a kilogram, right? Still crash.
    E = +35  # From which exponent to start from. Note: E is incremented by default.

    function endApplyForce()
    {
        if (!Busy) { stoptimer(clkName()), return }
        print("End of " + E)
        ExpressionGate:propFreeze(1)  # Freeze physics object.
        ExpressionGate:setAng(ang())  # Zero angles.
        ExpressionGate:setPos(vec())  # Move it to origin.
        timer("increment", 1000)
        Busy = 0
    } # End of function void=endApplyForce()

    function beginApplyForce()
    {
        if (!Busy) { stoptimer(clkName()), return }
        print("Begin of " + E)
        ExpressionGate:applyForce(F)
        timer("endApplyForce", 1000)
    } # End of function void=beginApplyForce()

    function prepareApplyForce()
    {
        if (!Busy) { stoptimer(clkName()), return }
        print("Preparing for " + E)
        ExpressionGate:setAng(ang())  # Zero angles.
        ExpressionGate:setPos(vec())  # Move it to origin.
        ExpressionGate:propFreeze(0)  # Unfreeze physics object.
        timer("beginApplyForce", 1000)
    } # End of function void=prepareApplyForce()

    function increment()
    {
        if (Busy) { return }
        Busy = 1
        E++  # Direction of force. Use E++ (to post-increment E by 1) or E-- (post-decrements E by 1).
        N = "1e" + (sign(E) == -1 ? "-0" : "+0") + E  # Construct an exponential notation string, E being the exponent.
        F = vec(N:toNumber(10))  # Parse N as decimal number with base 10, and construct a 3D vector.
        timer("prepareApplyForce", 1000)
    } # End of function void=increment()

    increment()  # Start the "increment" loop initially.
} # End of first()
```

That was pretty easy to do. Here are the results:

> ...
> Preparing for 38
> Begin of 38
> End of 38
> Preparing for 39

Stopped at 39 as that's where it crashed. So, I guess it should also then crash at -39, too (just replace `E++` with `E--` on line 54, and run it).
So, now we know that.. Here is my set of temporary E2 functions, if anybody will find them useful (though I don't know why would you even..):
```
if (first())
{
#ifdef entity:applyForce(vector)
    function safeApplyForce(Force:vector)
    {
        entity():applyForce(clamp(Force, 1e-38, 1e+38))
    } # End of function void=safeApplyForce(v)

    function entity:safeApplyForce(Force:vector)
    {
        This:applyForce(clamp(Force, 1e-38, 1e+38))
    } # End of function void=e:safeApplyForce(v)
#endif

#ifdef entity:applyOffsetForce(vector, vector)
    function safeApplyOffsetForce(Force:vector, Position:vector)
    {
        entity():applyOffsetForce(clamp(Force, 1e-38, 1e+38), clamp(Position, 1e-38, 1e+38))
    } # End of function void=safeApplyOffsetForce(v,v)

    function entity:safeApplyOffsetForce(Force:vector, Position:vector)
    {
        This:applyOffsetForce(clamp(Force, 1e-38, 1e+38), clamp(Position, 1e-38, 1e+38))
    } # End of function void=e:safeApplyOffsetForce(v,v)
#endif
} # End of first()

# Usage:
entity():propFreeze(0)  # Unfreeze E2.
## Center:
safeApplyForce(vec(1e+54))  # Now crazy physics should not crash a server.
safeApplyForce(vec(1e-54))  # It should not crash in another direction either.
## Offset:
safeApplyOffsetForce(vec(1e+54), vec())
safeApplyOffsetForce(vec(1e-54), vec())

print("Success! You have not crashed the server by using applyForce in E2.\n" + owner():name() + " has unlocked a new achievement 'Truth Server Physicist'.")
entity():setPos(owner():aimPos())  # Move E2 where owner aims at.
```

:beers: 

@oldmud0 Yeah, I agree that Wiremod should not 'fix' this, instead should be reported [here](https://github.com/Facepunch/garrysmod-issues/issues) (or PM Rubat).. @shadowscion, as you can see issues are no longer there on [garrysmod](https://github.com/garrynewman/garrysmod) repo.
However, above is just a temporary E2 solution to keep server from crashing when working with huge applyForce (until it becomes fixed).. Clamping arguments between [1e-38, 1e+38] of [applyForce](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/compat.lua#L31-L34) and [applyOffsetForce](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/compat.lua#L36-L39) functions seems to be enough, at least that's what above E2 does.
So, if you attempt to apply abnormal force, clamp function will take care of that, meaning a vector you specify will always be within a maximum range which does not lead a server to crash (at least for me, on Windows).

**Comment by CaptainPRICE** [comment]
Hah! Nailed it, any Vector whose component reaches 1e+039 will have magnitude/length equal to INF:
![image](https://cloud.githubusercontent.com/assets/9789070/17090036/be144ba8-522c-11e6-9dce-9851a8c59338.png)
Now to simplify my comment above..

**Comment by Divran** [comment]
I knew there had to be an infinite value somewhere.

**Comment by shadowscion** [comment]
@CaptainPRICE https://github.com/Facepunch/garrysmod-issues issues are and always have been there

**Comment by TomyLobo** [comment]
could it be that gmod casts that stuff to float somewhere?

**Comment by TomyLobo** [comment]
Nailed it:
Float: 4 bytes, positive values range from 1.8E-38 to 3.4E+38

**Comment by Divran** [comment]
Alright so we can run the input to all applyforce functions through `E2Lib.clampPos` and make that function clamp it between 1.8E-38 and 3.4E+38

**Comment by CaptainPRICE** [comment]
> could it be that gmod casts that stuff from Lua numbers (which are double-precision floats) to C++ floats (i.e. single precision) somewhere?

Yep, that would make sense as vec_t is a float..
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/mathlib/vector.h#L70

**Comment by Divran** [comment]
All of the applyforce functions already use a function called `check`. This function checks for `math.huge`. If the force vector is larger than `math.huge`, it doesn't apply the force at all. What we're proposing here is to not apply the force if it's larger than 3.4E+38 or smaller than 1.8E-38, or should I clamp it to those values instead of not applying any force at all?

For now, I'll update the code to not apply any force at all, but I'll not commit/push it yet, to give everyone a chance to respond to this.

**Comment by CaptainPRICE** [comment]
@TomyLobo Is somewhat wrong about the range ;)
I know for a fact this is the correct range for a single-precision floating-point number:
`-3.402823E+38 to 3.402823E+38`
And for double-precision floating-point number:
`-1.79769313486232E+308 to 1.79769313486232E+308`

@Divran On it...

**Comment by Divran** [comment]
@CaptainPrice alright try editing the code to 3.4E-38 and see if it works

**Comment by Divran** [comment]
I ended up adding the check to WireLib instead of E2Lib because @CaptainPRICE reminded me of the existence of the applyForce gates

**Comment by TomyLobo** [comment]
@CaptainPRICE stop being a smartass, of course it's not a round number, considering we're talking decimal representations for numbers stored in binary format here.
And you did notice I said non-zero absolute values, right?
Absolute values don't become negative if you didn't know.
Words, they mean stuff.

**Comment by oldmud0** [comment]
Yeah but how many other things don't have clamps? It's not just force that can crash the game you know. Tons of other stuff that uses floats.

**Comment by CaptainPRICE** [comment]
@TomyLobo
> we're talking decimal representations for numbers stored in binary format here.

What binary format you are talking about?! (.. float size is (always) 32 bits in (gmod) memory ..)
Decimal digits are also very important as it makes a BIG difference. `FLOAT_MAX != 3.4E+38`

> And you did notice I said non-zero absolute values, right?

Yes.. Look, I have wanted to correct you and I did. Because, both of the values you have posted are **completely** wrong:
> Float's non-zero absolute values range from 1.8E-38 to 3.4E+38

Also if you haven't noticed it, it was completely unnecessary to post "non-zero absolute minimum value", by the way there is one word for that and I think it is called `Epsilon`, now I've teached you that. Moving onto the actual thing.. See these two screenshots below:
![float constants](https://cloud.githubusercontent.com/assets/9789070/17266128/103fac1c-55f5-11e6-9b8f-e4b62e2d7c8e.png)
![float Max test](https://cloud.githubusercontent.com/assets/9789070/17267332/6094c556-5606-11e6-9c76-7db02058cbd7.png)

See? You have been corrected, twice! Accept it, and be happy.
Okay, I am going to be even more precise now, so here they are - **the correct (constant) values**:
```
FLOAT_EPSILON     = 1.4e-45            -- The smallest positive float value that is greater than zero.
FLOAT_EPSILON_ARM = 1.175494351e-38    -- The smallest positive float value that is greater than zero (use only on ARM-processor systems, as FLOAT_EPSILON is too small to be detected, so it equates to zero).
FLOAT_MAX  =  3.40282346638528859e+38  -- The largest possible value of float.
FLOAT_MIN  = -3.40282346638528859e+38  -- The smallest possible value of float.
```

You wanted magic numbers, you got them now. I guess that is okay, since that is the only way ;)
Now watch this outcome. Because you have provided incorrect range value ("Max: `3.4E+38`"), @Divran have used that wrong (*non-precise*) information in f8e3e74aa4a6f52b204a4ac6c11f564048a5c014 commit. Now we can't do `applyForce(vec(3.4028234e+38))`, which is valid force (would not cause a server to crash)..

> Absolute values don't become negative if you didn't know.

... by looking at your comment, I was like "What crap is this guy spewing?! When I know those values on top of my head, *LOL*, the values he has posted are not correct" ...

> Words, they mean stuff.
> stop being a smartass

You have got my upvote because you have a good point, but also a downvote because of incorrect values.
Please, don't be jelly my friend, sorry I just know better than you. Now, calm down man. k? :sunglasses:

@oldmud0
> It's not just force that can crash the game you know. Tons of other stuff that uses floats.

Yep. Sure it is not just apply force.. As nobody was apparently aware of this type-casting from another side, until now, that is just ridiculousness after so many years..

**Comment by CaptainPRICE** [comment]
@TomyLobo
> we're talking decimal representations for numbers stored in binary format here.

What binary format are you talking about?! (.. float size is (always) 32 bits in (gmod) memory ..)
Decimal digits are also very important as it makes a BIG difference. `FLOAT_MAX != 3.4E+38`

> And you did notice I said non-zero absolute values, right?

Yes.. Look, I have wanted to correct you and I did. Because, both of the values you have posted are **completely** wrong:
> Float's non-zero absolute values range from 1.8E-38 to 3.4E+38

Also if you haven't noticed it, it was completely unnecessary to post "non-zero absolute minimum value", by the way there is one word for that and I think it is called `Epsilon`, now I've teach you that. Moving onto the actual thing.. See these two screenshots below:
![float constants](https://cloud.githubusercontent.com/assets/9789070/17266128/103fac1c-55f5-11e6-9b8f-e4b62e2d7c8e.png)
![float Max test](https://cloud.githubusercontent.com/assets/9789070/17267332/6094c556-5606-11e6-9c76-7db02058cbd7.png)

See? You have been corrected, twice! Accept it, and be happy.
Okay, I am going to be even more precise now, so here they are - **the correct (constant) values**:
```
FLOAT_EPSILON     = 1.4e-45            -- The smallest positive float value that is greater than zero.
FLOAT_EPSILON_ARM = 1.175494351e-38    -- The smallest positive float value that is greater than zero (use only on ARM-processor systems, as FLOAT_EPSILON is too small to be detected, so it equates to zero).
FLOAT_MAX  =  3.40282346638528859e+38  -- The largest possible value of float.
FLOAT_MIN  = -3.40282346638528859e+38  -- The smallest possible value of float.
```

You wanted magic numbers, you got them now. I guess that is okay, since that is the only way ;)
Now watch this outcome. Because you have provided incorrect range value ("Max: `3.4E+38`"), @Divran have used that wrong (*non-precise*) information in f8e3e74aa4a6f52b204a4ac6c11f564048a5c014 commit. Now we can't do `applyForce(vec(3.4028234e+38))`, which is valid force (would not cause a server to crash)..

> Absolute values don't become negative if you didn't know.

... by looking at your comment, I was like "What crap is this guy spewing?! When I know those values on top of my head, (*LOL*), the values he has posted are not correct" ...

> Words, they mean stuff.
> stop being a smartass

You have got my upvote because you have a good point, but also a downvote because of incorrect values.
Please, don't be jelly my friend, sorry I just know better than you. Now, calm down man. k? :sunglasses:

@oldmud0
> It's not just force that can crash the game you know. Tons of other stuff that uses floats.

Yep. Sure it is not just apply force.. As nobody was apparently aware of this type-casting from another side, until now, that is just ridiculousness after so many years..

**Comment by oldmud0** [comment]
> I just know better than you
hey leave the ego in the forums will you

**Comment by AbigailBuccaneer** [comment]
@CaptainPRICE, consider the ways in which you're acting aren't helping the situation right now. I'm locking this conversation thread.

**Comment by TomyLobo** [comment]
Since @AbigailBuccaneer closed the thread, let me just make a few corrections to what you said.

1. GMod doesn't run on ARM, so mentioning ARM is unnecessary, but apart from that, you're also wrong: ![floating point test on ARM] (http://img.ctrlv.in/img/16/07/30/579cdc03f2546.png)
2. [GMod Lua numbers are doubles] (https://github.com/garrynewman/gmod-module-base/blob/master/include/GarrysMod/Lua/LuaBase.h#L47), which are 64 bits wide.
3. Epsilon is not what I was talking about. IEEE doesn't even define epsilon. In broader terms, [Machine epsilon] (https://en.wikipedia.org/wiki/Machine_epsilon) is a relative error, which has nothing to do with the minimum absolute value for any floating point type used in GMod.

I had to look that up, but I'd rather know what I don't know than to claim bullshit as the truth and feel superior to other people when I am clearly wrong.

*I* was wrong in one point, too, though.
http://ideone.com/vXAWp8
I forgot about denormal numbers. For standard single-precision floating point numbers, that's everything between roughly 7.1e-46 (=0.71e-45 i.e. about half your FLOAT_EPSILON) and 1.18e-38 (which you for some reason call FLOAT_EPSILON_ARM).

**Comment by Divran** [comment]
Well, @TomyLobo I'm not afraid to admit I have no clue what the correct values are so feel free to edit the values in the check function if they are wrong. The current values seemed to work in-game though.

**Comment by TomyLobo** [comment]
They don't really matter anyway. No one is going to try any values that high anyway.
The +/-3.4e38 you picked is fine
