### ISSUE TITLE
E2: UDF can not be found if the first argument's name is "This"

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1191]
For example:

```
function string str(This:entity)
{
    return "Entity: " + This:id()
}

print(str(entity()))  # Validation: No such function: str(entity) at line 6, char 7
print(entity():str())  # Works.
print("str"(entity())[string])  # Also works.
```

Is this known limitation?

**Comment by Divran** [comment]
"This" is a restricted keyword. We could probably allow it to be used in functions like this one, that aren't methods. But the only real problem here is that the error message isn't descriptive.

I have no idea why the second way works. The third way (callable strings) looks correct. It should auto-detect whether or not it's a method.

**Comment by bigdogmat** [comment]
Just to clarify, `This` isn't a restricted keyword, it's simply a normal argument. The reason the second way works was because of the way we were checking if a UDF was a method (Checking if the first arguments name was `This`).
