### ISSUE TITLE
Expression 2 server crash exploit/bug after temporary fix

### ISSUE THREAD

**Issue by theplayer232** [wiremod/wire#1195]
It's back!

@name Server crash exploit by N3tGh0st
if(first()){
    entity():isWeldedTo():applyForce(vec(1e+24,1e+24,1e+24*1e+24))
}

attach it to prop and it crashes

**Comment by bigdogmat** [comment]
You shouldn't just put this in the pr, or in the already made issue. Back to the issue, did you apply the fix yourself? This should've created a vector with a inf length in which case it not apply the force at all

**Comment by oldmud0** [comment]
Yeah we know about this.

**Comment by CaptainPRICE** [comment]
@theplayer232
> It's back!

No.. You just created yet another duplicate.
Learn how git works.
Just tested it again, and it didn't crash on `CaptainPRICE:temp-fix-1189-applyforce-crash` branch; unable to reproduce.

**Comment by theplayer232** [comment]
I updated wiremod today and it worked

**Comment by CaptainPRICE** [comment]
> I updated wiremod today

Something tells me you either downloaded Wire from Workshop, or [downloaded](https://github.com/wiremod/wire/archive/master.zip)/cloned **master** branch of this repository, so obviously:
> it worked

Since it hasn't yet been merged.
So, instead, you should have merged #1190 locally, and then you would see that it does not work.
Like I said in previous comments: Learn how git works please.

**Comment by oldmud0** [comment]
People aren't going to learn how git works. It's a developer tool.

**Comment by theplayer232** [comment]
@CaptainPRICE I didn't know it wasn't merged yet.

**Comment by AbigailBuccaneer** [comment]
Duplicate of #1189.

**Comment by Divran** [comment]
@theplayer232 this is fixed now
