### ISSUE TITLE
E2 double execution speed issue with interval()

### ISSUE THREAD

**Issue by nerdkoopa** [wiremod/wire#1229]
When server uptime gets closer to 24 hours, any E2 chip running on interval() will start being executed at double speed and at double the ops count.
The warning signs start at around 20 to 22 hours, when things start gradually speeding up ever so slightly. This doesn't seem to happen with chips using runOnTick(), only with interval().

**Comment by bigdogmat** [comment]
I don't believe this is really fixable by us, once a server reaches around 6 hours of up time its time calculations start being less precise due to it using a float internally.

To quote what the wiki says

> This is internally defined as a float, and as such it will be affected by precision loss if your server uptime is more than 6 hours, which will cause jittery movement of players and props and inaccuracy of timers, it is highly encouraged to refresh or change the map when that happens (a server restart is not necessary).
This is NOT easy as it sounds to fix in the engine, so please refrain from posting issues about this

**Comment by Divran** [comment]
Install some more addons so your server crashes regularly

Nah but really get an admin mod with a map change scheduler thingy and use that
