### ISSUE TITLE
Keyboard: Use enum literals instead of hardcoded integers

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1232]
I have noticed that [lua\entities\gmod_wire_keyboard\remap.lua](https://github.com/wiremod/wire/blob/03972803dd6f6087479c848dab7d015e5bce10f9/lua/entities/gmod_wire_keyboard/remap.lua) uses hardcoded integers which is bad as you should already know (i.e. it would completely break if the internal values are changed).
Stop the hardcoding please, it doesn't help anyone.

> **Warning!** Decimal values are for reference only! The actual value may be different between two Garry's Mod versions.

Proves my point...

**Comment by bigdogmat** [comment]
Where is it not using enums?

**Comment by CaptainPRICE** [comment]
> Where is it not using enums?

Do you see integers all over the place? Starting from the line 49.

**Comment by bigdogmat** [comment]
The ones below 129 seem to be in reference to something, I'd have to look at the code to figure out. All the other numbers just seem to be the ascii code for the keys, of which the enums do not represent.

**Comment by CaptainPRICE** [comment]
> of which the enums do not represent.

Create it.

**Comment by bigdogmat** [comment]
The Enums are already mapped to those keys through use of the table, I don't see a reason to create Enums for the keys as there name is right next to them.

**Comment by CaptainPRICE** [comment]
Then what about?
208, 221, 235, 274, 305, 316, 355

**Comment by Divran** [comment]
On the left hand side we already have enums. On the right hand side, all of the numbers are ascii values or strings. https://github.com/wiremod/wire/blob/03972803dd6f6087479c848dab7d015e5bce10f9/lua/entities/gmod_wire_keyboard/init.lua#L188 This line right here converts any strings back into ascii as necessary. The only reason the keyboard remap file has strings is to make it more readable. Some values don't use strings because there's either no visible character that represents them, or the person who wrote that part doesn't have that key on their keyboard. Or maybe the person who wrote that part of the code felt like using the ascii number, who cares.

The only part which I can't explain is lines 108-129, which is this part:
```
remap[KEY_XBUTTON_UP] 		= 200
remap[KEY_XBUTTON_DOWN]		= 201
remap[KEY_XBUTTON_LEFT]		= 202
remap[KEY_XBUTTON_RIGHT]	= 203
remap[KEY_XBUTTON_START]	= 204
remap[KEY_XBUTTON_BACK]		= 205
remap[KEY_XBUTTON_STICK1]	= 206
remap[KEY_XBUTTON_STICK2]	= 207
remap[KEY_XBUTTON_A] 		= 208
remap[KEY_XBUTTON_B] 		= 209
remap[KEY_XBUTTON_X] 		= 210
remap[KEY_XBUTTON_Y] 		= 211
remap[KEY_XBUTTON_LTRIGGER] 	= 214
remap[KEY_XBUTTON_RTRIGGER] 	= 215
remap[KEY_XSTICK1_UP] 		= 216
remap[KEY_XSTICK1_DOWN] 	= 217
remap[KEY_XSTICK1_LEFT] 	= 218
remap[KEY_XSTICK1_RIGHT] 	= 219
remap[KEY_XSTICK2_UP] 		= 220
remap[KEY_XSTICK2_DOWN] 	= 221
remap[KEY_XSTICK2_LEFT] 	= 222
remap[KEY_XSTICK2_RIGHT] 	= 223
```
I believe this was written a very, very long time ago. Back when the keyboard was added to wiremod for the first time, when there was only one single keyboard layout. They seem to reference a console controller, though.

**Comment by Divran** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_keyboard/init.lua#L192
On this line, it seems it ignores any keys that are above KEY_LAST. This means that lines 108-129 as described in my other post are never used. They're junk left over from older versions of wiremod, it seems.

**Comment by Divran** [comment]
>Then what about 83's?
208, 221, 235, 274, 305, 316, 355
Is that supposed to be KEY_RALT or KEY_LALT?

Ah, wait. This is correct, these should be using key enums.
