### ISSUE TITLE
Enable unlimited mode by default for single-player game

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1242]
Since there are no limits in single-player (i.e. any amount of props can be spawned), there is no reason for wire to force the limits in single-player game (by default).

There's also a bug with unlimited mode (which makes it not work as expected), but I guess @AbigailBuccaneer is aware of that. #1238 (cleanup?)

**Comment by oldmud0** [comment]
No, because this will confuse newbies further as to why their E2 is working in singleplayer but not in any server. Also, it's nice to keep parameters consistent between singleplayer and multiplayer so that makers can be sure that their contraptions work online too, not just in singleplayer.

**Comment by CaptainPRICE** [comment]
> No, because this will confuse newbies further as to why their E2 is working in singleplayer but not in any server.

LOL! I could say the same for dupes:
"why my contraption is working in singleplayer but not in any server."

**Comment by AbigailBuccaneer** [comment]
> There's also a bug with unlimited mode (which makes it not work as expected), but I guess @AbigailBuccaneer is aware of that. #1238 (cleanup?)

#1238 isn't a bug report, and I can't see any relevant bugs. If setting `wire_expression2_unlimited` currently doesn't work then that's another issue that should be reported.

**Comment by AbigailBuccaneer** [comment]
@oldmud0 is right that consistency between singleplayer and multiplayer is good, @CaptainPRICE is right that this isn't a principle that is even vaguely enforced or encouraged by Garry's Mod itself (sandbox limits being a prime example). I can imagine something like using unlimited ops in singleplayer but warning if a chip uses more than the default multiplayer ops would be useful, but probably also overkill.

**Comment by Divran** [comment]
I think Garry's choice of not having any limits in single player is a bad one. Ideally, it should start at the same default limits as any server, but then also give the user easy access to an options menu to change them whenever they want.

Building something in single player and then having it not work online is a bad experience, and this is encouraged by Garry himself, apparently. But just because others are doing it doesn't mean we should.

**Comment by Rusketh** [comment]
I would have to agree with Divran here too,
This would make it so that any e2 privately developed in single player will potentially run at over kill ops.
I learned e2 in single player and if e2 had an ops system back then this would have messed me up quite badly, as a beginner my e2's would have used a lot of ops.

Secondly why is this even needed, do the current ops limit not provide you enough and wouldn't it be easier for you to move to something more optimized like starfall ex in that case?

Also in case you have not have realized that you can easily change a convar in single player with in a matter of seconds. Let me keybind that for you. _bind [ wire_expression2_unlimited 1;_
Run that in console and when ever you enter single player press [ and you no longer need to set the convar MAGIC.

**Comment by CaptainPRICE** [comment]
> you have not have realized that you can easily change a convar in single player with in a matter of seconds

Yes, we know about the unlimited convar (@AbigailBuccaneer has pointed it out twice already), but there is a problem with it.

> Let me keybind that for you.

No need. I have it in `server.cfg`, but it is set to 0 (as it does not work as expected for me) along with all `sbox_*` being set to very high value, so no limits for anything.
Apparently the whole point of `wire_expression2_unlimited` is to make it a shortcut to:
```
wire_expression2_quotasoft 1000000
wire_expression2_quotahard 1000000
wire_expression2_quotatick 100000
```

So, as long as `wire_expression2_unlimited` is enabled, those limits are present. But, those limits assigned by unlimited are not precise and it uses `ConVar.GetInt` (wrong function)... (Basically, that's why I have unlimited convar set to 0..)

**Comment by bigdogmat** [comment]
> But, those limits assigned by unlimited are not precise and it uses ConVar.GetInt (wrong function)

In what world would you need to be more precise than an int? I honestly can't think of any reason that would need to be a float.
