### ISSUE TITLE
Editor misbehaves when file/folder list is out-of-sync!

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1256]
## Steps to reproduce the issue
1. Create a new file and save it via Editor.
2. Rename the file to something else by using File Explorer (in operating system).
3. Right-click the file in Editor, click `Save to`, and then at that point, you will be prompted if you want to overwrite the file.

Well, that's just completely wrong as it is out-of-sync. It should check it again and see if the file is still there...
This could completely screw the work up (until you are aware of it, but then it is probably already too late), since the majority of chips lives "one-file" life!

**Comment by Divran** [comment]
What would happen is that it would check if the file still exists and when it found out that it doesn't exist, it would simply save the file without asking to overwrite. How is that any better? Asking to overwrite does no harm, but not asking to overwrite might confuse you into thinking it deleted the previous contents of the file without asking (of course, that didn't happen since the file was renamed first, but it could be pretty scary)
