### ISSUE TITLE
Preprocessor attemptes to index field 'directives' (a number value)

### ISSUE THREAD

**Issue by Codingale** [wiremod/wire#1274]
The issue randomly happened when opening the Wire E2 editor, it occurs on 10 other peoples clients. 
```
addons/wire/lua/entities/gmod_wire_expression2/base/preprocessor.lua:283: attempt to index field 'directives' (a number value)
 
Trace:
    1: Line 32  "Trace"     lua/includes/extensions/debug.lua
    2: Line 308 "__index"       addons/wire/lua/entities/gmod_wire_expression2/core/e2lib.lua
    3: Line 283 "nil"       addons/wire/lua/entities/gmod_wire_expression2/base/preprocessor.lua
    4: C function   "Execute"
    5: Line 2171    "AC_SaveVariables"      addons/wire/lua/wire/client/text_editor/texteditor.lua
    6: Line 2202    "nil"       addons/wire/lua/wire/client/text_editor/texteditor.lua
    7: Line 2307    "AC_Check"      addons/wire/lua/wire/client/text_editor/texteditor.lua
    8: Line 2288    "nil"       addons/wire/lua/wire/client/text_editor/texteditor.lua
```

`wireversion`: [8a2f3e4]( https://github.com/wiremod/wire/commit/8a2f3e42b121d91757f4564afdc02f9bf6289f56)

(I posted this in the help chat, but was directed here, at first I thought it was just my client, haven't tried other servers)

**Comment by bigdogmat** [comment]
This is caused by the fact that [`EDITOR:GetValue`](https://github.com/wiremod/wire/blob/master/lua/wire/client/text_editor/texteditor.lua#L345-L347) doesn't limit the return from `string.gsub`, as such [`PreProcessor.Execute`](https://github.com/wiremod/wire/blob/master/lua/wire/client/text_editor/texteditor.lua#L2171) gets the amount of replacements done as its second argument.

I would've made a pr to fix this but I have no idea how to invoke the functions to do so.
