### ISSUE TITLE
EGP font whitelist assumes Windows proprietary fonts

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#1283]
It would be nice to either have the option to map Windows propiertary fonts to equivalent free fonts if applicable (like the [Liberation family](https://en.wikipedia.org/wiki/Liberation_fonts)) and/or add some more options with more permissive licences such as the Liberation or [DejaVu](https://en.wikipedia.org/wiki/DejaVu_fonts) family.
(Both of those font families are for example included with Libreoffice, but are also free&legally downloadable)

I also wonder why there is a whitelist in the first place, as trying to draw a font that is not availible will use a default font.

**Comment by Divran** [comment]
It's not really a whitelist. It's actually that each font is mapped to an integer, so that back in the days when we had umsg, egp could sent one char (8 bytes, the smallest amount you could send in umsg), instead of the entire font name as a string (loadsa bytes). Now that we have net messages, we could actually just change it to a string and not give a fuck

**Comment by Denneisk** [comment]
Fixed in  #1683
