### ISSUE TITLE
Improve debugger UI/UX

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1288]
- [ ] Make a nice VGUI for Debugger.

(I doubt I am the first one to speak about this, but since I could not find any existing issues about it - now there is.)
The current design sucks for many reasons. Let me point out a few limitations:
- It is not correctly Y-positioned, so sometimes you will also see free space (i.e. if you have hided toolgun help text). Also, text is always in top-left corner of your screen.
- You need to open spawn menu, search, and get Debugger tool every time you want to add/remove/clear component(s).
- Array, table, ranger and such types are very very limited (or completely not supported); Just a few elements are shown inside array/table (and that is troublesome a lot to all users). Elements from an array/table in a table are never shown.
- Once you run out of screen height, you could switch to horizontal display, but despite that you will still run out of width and height at some point. And then you get mess, full screen covered with text.
- It shows all inputs/outputs of component, always, it does not let you filter anything per component (i.e. only show inputs with specific name and outputs of specific type).

And so on (feel free to continue the list in the comments)...
[Link to STool](https://github.com/wiremod/wire/blob/master/lua/weapons/gmod_tool/stools/wire_debugger.lua). [Link to DebuggerLib](https://github.com/wiremod/wire/blob/master/lua/wire/server/debuggerlib.lua).
(I do have my own compact VGUI for Debugger, but unfortunately it is still not that good mainly because it is unfinished..)

So, your comments? Are you frustrated by the current Debugger design?

**Comment by thegrb93** [comment]
3/5 of those can be fixed without a new gui (1,2, and 5). 4 can be fixed with 5. And 3 can be debugged using printTable.

**Comment by CaptainPRICE** [comment]
> Those can be fixed without a new gui.

You are assuming an easy situation.. No they can't. Note they are in no order.

> It is not correctly Y-positioned
> ... text is always in top-left corner of your screen.

These are actually easy to fix.

> Use gb-radial or a keybind

Overhauled radial menu, probably good one. Keybind, nice one.
But, what about (right-click context menu) properties? :)

> Use printTable

printTable?!
If run on every tick (or even every ~7 seconds) = Console and chat spammed to death (and possibly tick quota), no thank you. **Debugging is a nightmare with all that prints** (because for one, you lose chat, and two, console is spammed with everything else, model/sound file is missing).
No such function printTable(ranger, matrix*, gtable, etc)... So, even if you manage it this way, then you still must get rid of those calls later on (at least you should). It becomes such a pain in ass (if you used them in couple of places, and are using normal text editor), realized it or not, but it doubles the development time.
Well, see, this is where VGUI comes and takes the place.

4? I don't understand your 4th point.

> Input selection could be added.

Hm? Let me just say it twice.
It is both, input and output filtering (there are 3-radio options: show inputs only, show outputs only, and show inputs and outputs). Also it should allow to filter by their IO name (e.g. if only "Active" input is marked, and no outputs, then only "Active" should be sent) and type (e.g. if only "angle" type is marked, then it should only send inputs/outputs of type "angle").
Again, this actually requires making VGUI.

**Comment by thegrb93** [comment]
Input/Output Selection. Just requires adding the same menu to the debug tool that the wire tool has.

**Comment by Divran** [comment]
Looks like @thegrb93 already covered this, but still

>>Use printTable

>printTable?!
If run on every tick (or even every ~7 seconds) = Console and chat spammed to death (and possibly tick quota), no thank you. Debugging is a nightmare with all that prints (because for one, you lose chat, and two, console is spammed with everything else, model/sound file is missing).
No such function printTable(ranger, matrix*, gtable, etc)... So, even if you manage it this way, then you still must get rid of those calls later on (at least you should). It becomes such a pain in ass (if you used them in couple of places, and are using normal text editor), realized it or not, but it doubles the development time.
Well, see, this is where VGUI comes and takes the place.

Use printTable properly, then. Don't run it in places in your code that runs every tick. Use it in a place that is only ran once, then view the output carefully to find the bug in your code. Then remove the printTable when you no longer need it.

The reason the debugger tool doesn't display this information is a practical one. Any info the debugger shows must be synced to the client for display. The debugger tool syncs the data several times per second https://github.com/wiremod/wire/blob/master/lua/weapons/gmod_tool/stools/wire_debugger.lua#L246-L258 Making a new UI will not magically solve this issue. You simply can't send an infinitely large array or table every 0.1 seconds, so instead we MUST limit the data that is sent. The limit might currently be pretty small, but remember that it was chosen for two reasons: Both the fact that it previously used umsg, and so was limited to 255 bytes. And also because you have a limited space on your screen to show stuff. You also brought up the screen size limit, but @thegrb93 already covered that.

**Comment by adosikas** [comment]
Alternatively you could just make a E2 that reads the outputs of the E2 you want to debug and displays them in way that you need, for example using wirelink to read all inputs and display them in a nice fashion on a EGP (prettyprint json is nice to display tables easily), or just something like `setName("Value1:"+InputTable["Value1",number]+ ...)`.

**Comment by Divran** [comment]
@adosikas Oh yeah I completely forgot about that. `setName` is a thing, too. I believe the character count limit for `setName` is around 30 000, which should be plenty for debugging. Not enough for debugging a table/array that's enormous, but pretty much nothing can do that, so whatever

**Comment by shadowscion** [comment]
you cant use new lines with setName

**Comment by Divran** [comment]
Yes you can
