### ISSUE TITLE
[Expression 2] Can't use foreach on an array of tables

### ISSUE THREAD

**Issue by Matt1923** [wiremod/wire#1297]
**_Foreach can't find a table inside of an array_**
```
Prizes:pushTable(table("prize" = "bronze",  "chance" = "0.5"))
Prizes:pushTable(table("prize" = "silver", "chance" = "0.25"))
foreach(K, V:table = Prizes)
{
    printTable(V)
}
```
This foreach doesn't run at all. I've tried printing some text inside of it.
However this works fine:
```
for(I = 1, Prizes:keys():count()){
    printTable(Prizes[I,table])
}
```
So having tables in arrays is fine but foreach can't recognize it.

**Comment by bigdogmat** [comment]
Uh, unless your Wiremod is very outdated, you can't put tables inside arrays, or even arrays inside arrays for that matter. However if `Prizes` is a table, the reason it doesn't print anything is because foreach only iterators over string indices, and `pushTable` puts it in the next sequential index.

**Comment by Matt1923** [comment]
Foreach works for arrays for me which don't have string indices.

**Comment by bigdogmat** [comment]
> Foreach works for arrays for me which don't have string indices.

This is because it wouldn't make sense for arrays as they can't contain string indices.

> Just tried this with push also just incase that was the problem

push* is pretty much the same as doing `Arr[Arr:count() + 1, type] = foo`.

> E2 allows me to use 2D Arrays but gives me the an error when I do a foreach on the 2d array:
> Table expression (of type 'r') has no indexing operator

Can you show me how you're creating a 2D array.

 I ask because E2 doesn't allow this, the only construct in which it doesn't error would be `array(array(), array())`, and in that case those arrays are not put into the one you're creating, they're discarded.

The reason `foreach` errors is because arrays can't contain nested arrays/tables, as such there's no indexing operator for them.

**Comment by Matt1923** [comment]
I was creating the array as you stated earlier
```
array(array("SomeString", "SomeOtherString"), array("SomeOtherString", "SomeString"))
```
The arrays inside of the array are disposed of like you said.
Sorry for wasting your time. This is clearly intended behaviour.

**Comment by Divran** [comment]
Arrays can't have arrays inside of them like you said. Dunno if this was mentioned already, but the reason your example with tables in the very first post of this thread didn't work is because the "K" variable in foreach loops in E2 can only use one type at a time. So, for arrays we chose numbers (since arrays can't use any other type anyway), and for tables we chose strings. This means that foreach can't iterate over numerical indexes in tables at all, only string indexes. This COULD be solved if we added `K:typename` in foreach for example, but there hasn't been a need for it, since you can instead just do `for(I=1,Table:ncount()) {` ( https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/table.lua#L407 )

**Comment by bigdogmat** [comment]
> This COULD be solved if we added K:typename in foreach for example, but there hasn't been a need for it, since you can instead just do for(I=1,Table:ncount()) {

There is a need for it if you wanted to iterator over unordered indices, of course that doesn't apply here. I opened the issue for that here #1060.

**Comment by Divran** [comment]
You can already kind of do that using `T:keys()` but yeah that is more of a hassle. Will also be a pain if your table uses mixed string and number indexes.
