### ISSUE TITLE
printTable doesn't work with arrays

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#1307]
`printTable(array(1,2,3))`
=>
'' (nothing)

I know that print(Array) now works, but It was again not easy to figure out.
printTable(Array) is still valid, still in E2Helper, but just not working.
I suggest turning back to how it was - printTable() for both arrays and tables, and print... just leave it how it is, cuz somebody is now using it with arrays too.

**Comment by bigdogmat** [comment]
Do you have wire-extras installed? I ask because the function still works fine alone, the reason it doesn't with wire-extras installed is because wire-extras overwrites the default `PrintTable` function breaking the method we use.

For reference, this is the [code](https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/entities/gmod_wire_expression2/core/debug.lua#L185-L205) used here, it overwrites `Msg` because that's what the default `PrintTable` function uses.

Wire-extras breaks this because it overwrites `PrintTable` with its own version [here](https://github.com/wiremod/wire-extras/blob/ed04148c897b16fbd2fcd704c01ddedfaa31753b/lua/entities/gmod_wire_hud_indicator_2/util/tables.lua#L6-L26).

Solution would be to create of own version of `PrintTable` for arrays, mainly because using this sort of _hack_ is bad imo. Alongside doing that, we should also not overwrite the `PrintTable` function in wire-extras, although that's an issue that should be posted over on that repo.

**Comment by Divran** [comment]
wtf wire extras shouldn't be doing that

**Comment by bigdogmat** [comment]
This was fixed by #1321.
