### ISSUE TITLE
HoloClip info Server to Client unreliable

### ISSUE THREAD

**Issue by sammyt291** [wiremod/wire#1328]
Hello,
This has been a long standing issue where newly spawned holograms occasionally are clipped in random position/angles.
This occurs even when there are no clips enabled on the holo itself or anywhere in the E2.

I have tried running holoClipEnabled both on and off for each hologram to see if they are still effected and it seems they are.

We have also ruled out the possibility of other addons causing the issue by spawning large multiple holo E2s on a fresh server.
[Example](http://dev.wizry.net/other/finetree/ImageUpload/hl2_2017-01-30_21-06-08.png)
All the E2 fans in that image are the same code and spawned in roughly 3 seconds apart.

Also each user seems to receive different random clips, sometimes on totally different holograms.

This issue is a nightmare for us as we convert all our high prop count vehicles to holo and upon spawning them in random props appear missing or split in half  or quartered etc. 

Help with resolving this would be greatly appreciated,
Sam.

**Comment by shadowscion** [comment]
Yeah, I don't know why my issue about this was closed 3 years ago, especially after all the good discussion on the post - and nothing was every done about it.

https://github.com/wiremod/wire/issues/247

**Comment by adosikas** [comment]
@shadowscion The commit fixed the obvious bug (recreating the holo on the same chip not clearing clips), not the compartively edgecase of reusing a holoid for a different chip.

Looks like the clientside table is indexed by entity id (`clip_buffer[eidx]`), while the server [checks the clips from the holo id](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L366). It will never will find clips when a new holos is created on a reused entity id, and as such never send the reset packets. 
The holoid [only when sending the packet](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L205), which doesn't happen here.

Maybe the resetholocl should sent a packet to the client to drop the entityid from the table, instead of just setting everything to false.  
A better way IMO would be to add a hook to clear the table when the entity is deleted (if possible), to avoid the problem of lingering entries altogether.

**Comment by sammyt291** [comment]
Could Clip data serverside have an extra variable of the entity's [Creation ID](http://wiki.garrysmod.com/page/Entity/GetCreationID)

That way the client can validate the ents creation id with the one in the clipdata?
if there is a mismatch then drop the clip data.

**Comment by sammyt291** [comment]
Anyone with more understanding of the underlying hologram functions that could verify Any of the above? and/or trial some fixes? 
It would be amazing to have this one resolved

**Comment by sammyt291** [comment]
Fixed by:
[Commit 69c7e9a](https://github.com/wiremod/wire/commit/69c7e9a262bf0a463135715f07bd99f1d3c627ba)

**Comment by shadowscion** [comment]
That remains to be seen

**Comment by sammyt291** [comment]
@shadowscion I had been running this change on a trainbuild server where 100+ hologram E2s are the norm for every locomotive.

This completely resolved the issue for me over the week to 2weeks testing :)

**Comment by shadowscion** [comment]
The big test would be on notoriously afflicted servers like cre8tive.
