### ISSUE TITLE
Wire tool Not working and when linking a egp getting script errors

### ISSUE THREAD

**Issue by Luketheepic** [wiremod/wire#1334]
[Wiremod] lua/entities/gmod_wire_egp_hud/init.lua:62: attempt to call method 'LinkHUDToVehicle' (a nil value)
  1. LinkEnt - lua/entities/gmod_wire_egp_hud/init.lua:62
   2. RightClick - lua/wire/tool_loader.lua:528
    3. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:250

Keep getting that error when linking a Egp. I assume wire tool not working linked to it because of 3 also because wire tool stoped working after this
Please help me Fix this want to work on acf
Also on servers wiremod works perfectly
Also before these solutions are listed I have already:

Restarted Game
Uninstalled Wiremod
Reinstalled Wiremod
Changed Map
Changing Map with ULX
Changing gamemode with ULX (Game Crashed)
Uninstalling Workshop Wiremod and Reinstalling Git Hub Wiremod and Vice Versa

**Comment by Luketheepic** [comment]
Also before these solutions are listed I have already
Restarted Game
Uninstalled Wiremod
Reinstalled Wiremod
Changed Map

**Comment by Divran** [comment]
The only way this could happen would be if this file https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/huddraw.lua 
is not being included properly by this line here https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp_hud/init.lua#L5

I noticed that the above init.lua line 5 does name the file with uppercase letters. Are you using an operating system which is case sensitive? If you're using the downloaded github version of wiremod, try editing line 4 and 5 of init.lua linked above so that it's all lowercase. If this works, I'll make the change officially.

**Comment by Luketheepic** [comment]
Thank you @Divran that Fixed it. Also I am on Linux.

**Comment by Divran** [comment]
Alright this is now fixed
