### ISSUE TITLE
foreach loop valid entity checks not working

### ISSUE THREAD

**Issue by LazorDildar** [wiremod/wire#1350]
Trying to run any kind of test on an entity such as V:isValid(), V != noentity() or V:id()>0 will always return true in a foreach loop. 

e.g.
```
@persist Props:array
interval(100)

if (first()){
    findIncludePlayerProps(owner())
    findByClass("prop_physics")
    Props = findToArray()
}

foreach (K, V:entity = Props){
    if (!V:isValid()){
        print("Invalid entity found in foreach loop")
        selfDestruct()
    }    
}    

for (I = 1, Props:count()){
    if (!Props[I, entity]:isValid()){
        print("Invalid entity found in for loop")
        selfDestruct()
    }
}
```

Spawning a few props, pasting this chip then removing a prop will cause "Invalid entity found in for loop" to print in chat. If the for loop was not there then it would never print or self destruct.

**Comment by bigdogmat** [comment]
Are you saying `V:isValid()` always returns true? 

> Spawning a few props, pasting this chip then removing a prop will cause "Invalid entity found in for loop" to print in chat. If the for loop was not there then it would never print or self destruct.

Makes it sound like its only returning true when you delete a prop, which is correct behavior.

**Comment by LazorDildar** [comment]
In the loop `foreach (K,  V:entity = Props)`  both `V:isValid()` and `Props[K, entity]:isValid()` will _always_ return true, regardless if the prop still exists or not. 

In contrast, if you made a loop `for (I = 1, I < Props:count())` then `Props[I, entity]:isValid()` would return false if the prop is removed from the game.

To be clear:
```
foreach (K, V:entity = Props){
    if (V:isValid()){
        #Will always be called
    }   
    if (Props[K, entity]:isValid()){ 
        #Will always be called
    }
}     

for (I = 1, Props:count()){
    if (Props[I, entity]:isValid()){
        #Will only be called if the entity still exists in the game
    }
}
```

**Comment by bigdogmat** [comment]
Ok, I see what you mean, though I don't think it's exactly what you think it is.

foreach does a type check using the type's type checker, so once an entity inside the array is removed, it's NULL and doesn't pass the type checker. So no matter what, `V` is always valid because the invalid entities in the array aren't iterated over.

The reason this works fine with a normal for-loop is because you're still iterating over the invalid entities.

**Comment by LazorDildar** [comment]
Ohhh I understand. Thanks.

**Comment by Divran** [comment]
Yes I read this post earlier and didn't have time to reply. I was also thinking about removing the isvalid check from there, but I'm unsure if that might have unforeseen side effects.

**Comment by bigdogmat** [comment]
Whenever using foreach I was always under the impression that it went over NULL entities, I know at least some of my codes do special things in the case of it being NULL. So it wouldn't break anything I'd have, but that's not to say it wouldn't break someone else's.

**Comment by Divran** [comment]
nah, I dont think it would break anyones E2s in that way because every single function that does something to entities has validity checks, such as applyforce. It might add a few extra ops when it attempts to apply force to an entity that doesn't exist rather than skipping over it.

Not sure if we even need to change this behavior though. Why not call it `intended behavior ™` and leave it be

**Comment by bigdogmat** [comment]
We could, though I feel that'd be a bit inconsistent. For example foreach on tables iterates over NULL entities, also using `A:exists(index)` when index is that of a NULL entity returns 1.
