### ISSUE TITLE
Wire keyboard enter code changed

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1354]
Hello, i want to ask why you changed wire keyboard enter code? It was 13 but now its 10. This broke compatibility with wiremod in other addons, all stuff what used those key code now broken. This including all e2's, wire inputs on entities what can use wire keyboard as input, etc.

**Comment by oldmud0** [comment]
Point of contention: https://github.com/wiremod/wire/commit/bb9aee73f0948de7d27807588f81e315d84d0a82#diff-30951466c6d7f431ffdf1e858717ff46L65

**Comment by glebqip** [comment]
But, there is lot of old E2\CPU(including mine) chips, that works fine, but use old Enter code. Fixing E2\CPU 
 can tale a long time, and, i think, the authors of some E2\CPU will not fix it. I think, the good solution to add "Legacy mode" for wire keyboard, which return the old enter code(or add wire input)

**Comment by Divran** [comment]
There are other addons that use the wire keyboard directly? what? At most, I thought we broke old E2s that relied on the output being 13. Simply open those E2s, do ctrl+f, search for 13, replace with 10, save and done.

The reason it was changed was because 13 is an old windows relic. The value should be 10 everywhere, and windows recognizes that it's an old relic because it doesn't strictly enforce it anywhere (you can use whichever method you like). It's just slow to change because of backwards compatibility (the same argument you are giving here).

Also, try to run this code `print(string.byte("\n"))` at this url https://www.lua.org/cgi-bin/demo (or in any lua environment, like gmod for example - even in E2 if you want)

**Comment by Divran** [comment]
Also, those addons that use the wire keyboard could've avoided this issue in a number of different ways. For example
```
if key == Wire_Keyboard_Remap[KEY_ENTER] then
```
or
```
if string.char(key) == "\n" then
```
or
```
if KeyboardEntity:IsPressedEnum( KEY_ENTER ) then
```
or
```
if KeyboardOutputString == "\n" then
```

**Comment by AlexALX** [comment]
Why you think that \n is enter key? Its new line character != enter. Key code 13 is an "\r" if talk about ansii. And yes its "carriage return" what might be relic. But do you realize how much of code we need to replace to fix this small change? Its everywhere as we never thought that someone would change this mechanism in gmod/wiremod. Also like i said if we need detect this code even if autorun before entities loaded and table "Wire_Keyboard_Remap" initialized then it even harder to make compatibilty with new/old wiremod, as placing "10" instead of "13" is also not very good idea like it was. But in any case we talks about ansii, why we even need to use Wire_Keyboard_Remap in first place? Ansii is standard and it have both \r or \n key codes.

By the way:

Windows end of line sequence:  \r\n
Unix end of line sequence:     \n
Mac end of line sequence:      \r

And due to compatibility best choice is \n\r as it should work on all systems if talk about text files, but again we are talking about input and now look into this:

In python enter key code is 13.
In C/C++ enter key code is 13.
In C# enter key code is 13.

All those things is valid for windows, for linux it probably 10 not sure, but yes in most cases used constant what do this job automatically (13 or 10).
-----------
So what to do now?

**Comment by Divran** [comment]
Mac hasn't used \r for years. They switched to \n

**Comment by AlexALX** [comment]
> In either case, judging by all the references to this issue, you've already fixed it.
those issues only by one entity, but there is much other including all stargates/dhds and some other entities + e2s + starfall + e2a chips, everything need to look manually as "13" returning too much garbage. So this require some time to recode what i actually want to avoid. 

Sadly that table actually is "Wire_Keyboard_Remap[KEY_ENTER]" so we can't use two values like 10 or 13, but maybe there is some other way to make compatibility?

**Comment by Divran** [comment]
I already gave you several other different solutions
`if string.char(key) == "\n" then`
use this for example

**Comment by AlexALX** [comment]
Why i need to use like this if ansii is standard? If it says 10 or 13 it should not be changed. Also calling function and compare string is just noneffective usage of performance (even if difference will be small). I'm very disappointed that wiremod devs actually don't care about compatibility issues, its so easy to break something so others need waste personal time to fix issues caused by other when it was work for ages since 2007 year.

**Comment by Divran** [comment]
Standard? It was never following a standard to begin with. 13 was selected randomly from the start. Gmod doesn't output 13 or 10 anywhere.

**Comment by Divran** [comment]
Since you have already fixed it, any further bitching out of you is pointless. You're saying "omg it'll be so much work to fix" *while you already fixed it*

**Comment by AlexALX** [comment]
Just leave this:

> print("ascii of enter: " + str(ord("\n")));
> print("10: '"+chr(10)+"'");
> print("13: '"+chr(13)+"'");
> print("ascii of enter: " + str(ord("\r")));

Result:

> ascii of enter: 10
> 10: '
> '
> 13: '
> '
> ascii of enter: 13

So why you saying that 13 is not also enter? Both actually valid if talk about python https://repl.it/HH0G/1

And like i said i did not said it fixed those pull requests (what made not even by me) is fixing stuff only for ONE entity, but there is much other places and things what also needs to be fixed and its more that just few lines.

Anyway it seems like you have no plans of make proper compatibility of this what is pretty sad.

**Comment by AlexALX** [comment]
Also another note - you also broke all cap based addons what did other developers what we can't control or fix their code. This includes eap https://github.com/williamdefly/Evolutionaddonpack and all custom made stargates what is on workshop. So this even make us more problems as we need add more checks to make them incompatible with latest version of addon to not get another bug reports like "someones stargate not work with wiremod". And all this only because you calling "it is relict".

**Comment by oldmud0** [comment]
The bugs in other mods are not caused by "divran just decided to change something just cuz he felt like it," they are caused by poor coding practices. I have never seen anyone condone the use of a keycode in number format instead of as an enum (e.g. `KEY_ENTER`).

Tell your mod authors to use the [comparisons](https://github.com/wiremod/wire/issues/1354#issuecomment-293665851) Divran wrote above instead of hardcoding key codes. You will notice that @CryptAlchemy still hasn't learned his lesson and is *still* hardcoding the newline key code, instead of centralizing that value as a constant.

We want to stop using weird Windows quirks and just get on with doing things the standard way. I do admit Divran should have warned mod authors in advance, but I don't think they would have gotten the memo either way.

**Comment by Divran** [comment]
There is no way to know who to contact

**Comment by SharpOB** [comment]
> The bugs in other mods are not caused by "divran just decided to change something just cuz he felt like it,"

Actually, this is true. They worked fine without the change, and because of Divran they are now broken. This change has resulted in numerous headaches and is honestly so trivial that it should never have happened anyway. Whilst some of the blame can be laid upon the authors of the now broken code, it did work perfectly fine before, and Divran's change broke it.

It should be reverted, in my opinon.

**Comment by Elanis** [comment]
Indeed, it's a problem, i'm the developer of EAP quoted before, and we have same issues as @AlexALX 's Carter Addon Pack because our lua scripts are alike. I think my addons will have problems too with this update because we have same "libraries".

This update is not a small issue, it'll impact many addons, and without revert, we'll have addons which will bug with the "old" wiremod or the "new". And if we could fix it, that's would be heavy and ugly code, and our addons will be pointed because not optimized ?

It reminds me of a gmod update 2 years ago which delete the "velocitydecay" function and make bugs many addons like CAP, spacebuid or environments, and some addons are even now bugged because not maintained.

PS: in some case, we can't use constants as values, like configurations files which require numbers to work.

**Comment by AlexALX** [comment]
Ok, if talk about lua then there is indeed various ways to fix issue and even make automatically compatible with old/new wiremod. But if talk about e2 there is no automatic solution. You can't detect this is new or old wiremod, and get to know what is enter key code, so need to make or statement - if (Key==10|Key==13). KEY_ENTER is actually gmod key code and not ansii what equals to 64.

But anyway don't revert anything, as it will make even more confuse. If it is done ok, we will change code. At least where we can.

**Comment by Ruuttu** [comment]
As a user, I just noticed that two E2 dupes I've published, Tetris and Snake (http://steamcommunity.com/sharedfiles/filedetails/?id=422381743 http://steamcommunity.com/sharedfiles/filedetails/?id=760198061) are broken or partially broken. This is annoying because it's not possible to release patches to workshop dupes, and they already have a bunch of comments, ratings and subscriptions. I'm the kinda sucker that cares. 

The docs for the keyboard HiSpeed link only mentioned ASCII. 
(http://web.archive.org/web/20160722100242/http://wiki.wiremod.com:80/wiki/Wired_Keyboard) 

To @Divran's suggestions: 
- Wire_Keyboard_Remap was _not_ mentioned in the docs. 
- Using a function to retrieve the ASCII code, I would've had to check against "\r" at the time. It still would've broken because the keycodes have changed but ASCII hasn't. 
- KeyboardEntity:IsPressedEnum() (or keyPressed()) and the gmod key enums are irrelevant when working with the keyboard HiSpeed link. 
- ?

Line breaks in text are one thing. I understand that "\n" can be seen as more "universal" there. When it comes to numbering the buttons of a keyboard in ways that handily overlap with ASCII, I think we've been in agreement for a couple of decades that RETURN is "\r" and it's counterproductive to go different there. Don't forget there are two different buttons casually called "enter" on the keyboard that actually report different codes. 

Anyways thanks for all your work.

**Comment by Divran** [comment]
Well, we've received a lot of complaints about this now, mostly related to backwards compatibility. I didn't know that you can't update workshop dupes. I mean I knew workshop was complete trash, which is why I never use it if I can avoid it (only use it when that's the only way to get an addon). 

How about a compromise. I could add an option which is saved on the keyboard through dupes. All this option does is toggle between 13 and 10 when pressing enter. Old dupes would default to 13 (the old value) to preserve backwards compatibility. The default setting for this checkbox would be 10, however. So unless you change it in the tool, new keyboards will use 10.

**Comment by Ruuttu** [comment]
Oh I think every key _should_ have its own code, numpad enter included. If I'm honest, I'll probably never need that key. But if I did make a splitscreen multiplayer for example, being artificially unable to address both keys could be really frustrating. 

I still feel like return being 10 is silly, but if you can make the change backwards compatible, I'm perfectly happy. It's a shame to have to add a checkbox for that, but it's probably impossible to perfectly recognize an "old dupe" as it can be reduplicated etc. So yeah, checkbox makes sense (:

**Comment by Divran** [comment]
My PR above already recognizes "old dupes" by the fact that the new checkbox value doesn't exist on them. When it doesn't exist, I made it default to output 13.

**Comment by Ruuttu** [comment]
Sure, but I was asking would the checkbox value persist if a dupe is reduplicated. Even then, if a user were to spawn a new keyboard for whatever reason,ä and connect to an old dupe, the checkbox will come handy.

**Comment by Divran** [comment]
Yes, and yes that's why I made it a checkbox.
