### ISSUE TITLE
concmd console command missing when rejoining servers

### ISSUE THREAD

**Issue by kbarber1998** [wiremod/wire#1355]
I have noticed on some occurrences that when I join servers, the command "wire_expression2_concmd" is present, but once I leave a server and then rejoin the command is missing. And because the command is missing, you can not run concmd() in expression 2 as the function cant verify if the user has concmd enabled or not.

**Comment by Divran** [comment]
Yep, I have noticed issues like this (not this specific one, but similar ones, because I never use concmd and have it always set to 0). I'm 99% sure this is caused by the fact that clientside E2 extension files used to be loaded only after you first open the E2 editor for the first time each session. And as you can see here
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/cl_console.lua
this console command is created on the client in one such file.

However, pretty recently, I fixed this https://github.com/wiremod/wire/commit/f374d5bbcef78667aaf4a985f50a9553e3c98112 so you'll need to tell the owner of the server you play on to update wiremod to the latest version to fix this. Unfortunately, updating your wiremod on your own computer won't help because the server's version overrides yours while you play on said server.

Until then, you'll simply have to open the E2 editor (and then close it again or whatever) every time you want to use console commands.

**Comment by kbarber1998** [comment]
Ah I see now, thanks for the reply
