### ISSUE TITLE
E2 internal parser error (big mamma if-elseif statement runs out of memory?)

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1396]
Apparently it errors out at parser, it is big if-elseif statement (10000).
An error is printed into console, and has the following error all over the place:
```
....
	7280: Line 830	"IfElseIf"		addons/wire/lua/entities/gmod_wire_expression2/base/parser.lua
	7281: Line 830	"IfElseIf"		addons/wire/lua/entities/gmod_wire_expression2/base/parser.lua
	7282: Line 830	"IfElseIf"		addons/wire/lua/entities/gmod_wire_expression2/base/parser.lua
	7283: Line 241	"Stmt1"		addons/wire/lua/entities/gmod_wire_expression2/base/parser.lua
	7284: Line 223	"Root"		addons/wire/lua/entities/gmod_wire_expression2/base/parser.lua
	7285: Line 109	"nil"		addons/wire/lua/entities/gmod_wire_expression2/base/parser.lua
	7286: C function	"Execute"
	7287: Line 63	"wire_expression2_validate"		addons/wire/lua/entities/gmod_wire_expression2/cl_init.lua
	7288: Line 526	"Expression2Upload"		addons/wire/lua/wire/stools/expression2.lua
	7289: Line 576	"func"		addons/wire/lua/wire/stools/expression2.lua
	7290: Line 32	"nil"		lua/includes/extensions/net.lua
```

Test E2 code:
[elseif-test.txt](https://github.com/wiremod/wire/files/1074544/elseif-test.txt)

This should be fixed by not spamming/printing error all over the console, and it should tell more user-friendly error message instead of just saying:
![image](https://user-images.githubusercontent.com/9789070/27132240-595cdfae-510e-11e7-8e96-71280c944b6a.png)

![Console spam screenshot](https://user-images.githubusercontent.com/9789070/27132344-d43c94a8-510e-11e7-920f-87e7d77ebb42.png)

P.S. I forgot to mention that it also errors all over the place even in unlimited mode (`wire_expression2_unlimited 1`).

**Comment by bigdogmat** [comment]
The reason this errors is due to a stack overflow. The reason for all of the `IfElseIf` spam in console is because of the recursive lookup for `IfElseIf`. I'd suggest we write our own `debug.Trace()`([source](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/debug.lua#L24-L51)), and dump the full error to file as well as console. This fixes the case of the trace going past the limit of console.

**Comment by AbigailBuccaneer** [comment]
It should be possible to subtly refactor parsing of `if` / `elseif` chains so that it doesn't involve recursion.

In general, I think it's fine for the parser to recurse based on the nested structure of the code, in cases like:
```PHP
if (0) { if (0) { if (0) { if (0) { if (0) { if (0) { if (0) { if (0) {} } } } } } } }
```
But not in situations where we're parsing something linear like:

```PHP
if (0) {} elseif (0) {} elseif (0) {} elseif (0) {} elseif (0) {} elseif (0) {}
```

And definitely not in cases like:
```PHP
A = 1 A = 2 A = 3 A = 4 A = 5 A = 6 A = 7 A = 8 A = 9 A = 10 A = 11 A = 12 A = 13
```

That way, we can prevent stack overflow in all situations just by manually keeping track of block depth.

**Comment by Nebual** [comment]
Unless someone wants to post a less contrived example, I'm going to assume this doesn't actually affect anyone and close this for now.
