### ISSUE TITLE
Digital screen now extremly slow

### ISSUE THREAD

**Issue by AlexALX** [wiremod/wire#1416]
After latest updates (like 3 months ago) digital screen now useless in multiplayer. To draw 512*512 image it takes too much time. I know that you added buffering feature, but it too slow. There is no settings to change that on server/client side. So if i setup wire expression2 unlimited it opens image much more faster that it draws on screen. Please consider to add settings to change rates for make everyone happy. Also if you sending very much data, and then reset the screen - it wont do that before finish previous tasks.

**Comment by thegrb93** [comment]
Yes it's slow because networking ~1MB through the reliable channel is expensive and has to be done safely. You might want to consider a scripting chip that supports external image loading, like starfallex or expadv2

**Comment by Divran** [comment]
It was slowed down because it was completely killing everyone's fps. One option would be to have a convar to change the speed.

**Comment by oldmud0** [comment]
Isn't this chiefly because the calls to update the digital screen are done pixel-by-pixel? One way to mitigate this would be to buffer the calls and try to send them together on the same network message, or make a new call to update the bitmap (or a range of the bitmap) all at once by taking data from another array.

**Comment by Divran** [comment]
No, it was already buffering the updates

**Comment by oldmud0** [comment]
So, in theory, what if you made a functioned that explicitly uploaded a segment of an array (i.e. video memory) to the digiscreen and then compressed that buffer as a whole? Would that accelerate the process?

**Comment by immibis** [comment]
@oldmud0 As I understand it, it already does that.

**Comment by AlexALX** [comment]
I'm still not sure why it so slow then. If it buffers then it only should send add data in one tick instead of using many net messages, but right now it slower in ~10 times than before. I'm drawing image pixel by pixel / line by line via e2, and before with wire unlimited 512*512 image loading in ~2-3 minutes, but now it loads in 10 minutes, and i think this is not normal. 512*512 image have 262144 pixels so i assume that ratio is very low if it loads so slow.

**Comment by Divran** [comment]
The bottleneck is not in the data sending, thanks to the buffering. The reason it was slowed down in a recent update was because of the bottleneck in the decompressing and parsing of the transmitted compressed data. So basically, what used to happen was this:
* The server saves up a small buffer, compresses it, and then sends that to the client.
* The client receives it and .. bam the client freezes for 1 second.
* This repeats every second or so, so basically everyone on the server gets a massive stutter freeze once a second.

To fix this, I did this
* I made the code detect when you are trying to send a lot of data at once, and it then increases the buffer size (it waits a little bit longer before sending it to the client).
* I also slowed down the rate at which it decompresses & parses the received data on the client, and this is where the slowdown you are seeing comes from. Now, the client no longer freezes or gets FPS drops, but instead the rendering is slower.

**Comment by AlexALX** [comment]
I'm using only single thread in my e2 script for render, so it took 2-3 minutes usually, but like i said after update it now extremely slow. And bottleneck is in digital screen because e2 sended all data in 2 mines and another 8 minutes screen just renders it somewhy. I'll record video later.

**Comment by AlexALX** [comment]
OK here is video: https://drive.google.com/file/d/0B8sOhIwrqCQscEdNYW4zNDFTYUU/view

As you can see here when it starts it works fine and renders pretty fast, but after few seconds it slow down to very slow speed and idk why. Maybe there is some bug with buffer what slow down rendering? Before this changes percent in dialog window was equal to actual progress on digital screen, but now you see...

**Comment by Divran** [comment]
yeah that is definitely too slow

**Comment by Divran** [comment]
I just tested it. Using a single E2, with expression2_unlimited on it takes about 5 seconds to load a 512x512 image. With it off, it's bottlenecked by the E2 so it takes about 1 minute. Add me to steam and you can join my local server to test it out. Steam name is the same as here

**Comment by AlexALX** [comment]
Ok, dirvan fixed issue, thanks.

**Comment by immibis** [comment]
So as I understand it, this was only processing one RLE section per tick by mistake?

**Comment by Divran** [comment]
Yes
