### ISSUE TITLE
Re-bound flashlight key not recognized

### ISSUE THREAD

**Issue by clonbon** [wiremod/wire#1453]
As tittle suggests, pod controller and E2 functions only recognize "F" to be flashlight, but all other keys are recognized when bound to something other than default.

I use ESDF so this makes it hard to use other peoples contraptions.

**Comment by CaptainPRICE** [comment]
Yeah, because somebody whoever wrote that *lame* E2 code was assuming that all of us have the exactly the same, default keybindings.

The appropriate way to check if the player has flashlight turned on/off: [`Player.FlashlightIsOn`](https://wiki.garrysmod.com/page/Player/FlashlightIsOn).
So, update (your?) E2 to use these functions, for example: `owner():isFlashlightOn()`, `owner():keyForward()`, `owner():keyLeft()`...

-----

[Wire GitHub](https://github.com/wiremod/wire) is for reporting issues/bugs/enhancements of the Wiremod code itself, not for asking for help on "how to use" it. The correct place to ask those questions would be on the [Wiremod reddit](https://www.reddit.com/r/wiremod/), or [Wiremod Discord](https://discord.me/wiremod) (join the `#help` channel) which is far more active than Wiremod reddit.

We are inviting you to join [Discord](https://discordapp.com/) community. I suggest you to join our Discord as there are many experienced E2 coders available to help you with Wiremod usage.

**Comment by Divran** [comment]
What is ESDF?

**Comment by CaptainPRICE** [comment]
@Divran 

> What is ESDF?

🤦‍

"What is WASD?"

**Comment by Divran** [comment]
you realize you're extremely rude @CaptainPRICE

**Comment by clonbon** [comment]
I've gotten around this problem on my own projects. The real issue is when trying to use other peoples vehicles and other things. The only short term solution would be to just ask them to use the isFlashlightOn() functions in E2 and not wire anything to the "Flashlight" output on the pod controller. However that doesn't seem practical and I cant expect everyone to dig into their machines just to change this small thing so that I can try it out effectively. 

Like I said earlier, all the other keybinds are recognized when changed to something other than default, accept for "Flashlight". As @Divran pointed out, it seems hard-coded into the pod controller, as opposed to checking for the use of "impulse 100" which is the command used to turn on the flashlight. Would it be safe to assume that E2 was programmed similarly to cause the same problem?  I'm no programmer so these are just my observations and I don't know how hard that sort of thing would be to change.

**Comment by Divran** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/player.lua#L109-L114

E2 uses this function correctly, so changing the pod controller to use it as well should be easy.

**Comment by Divran** [comment]
Nope, doesn't work. The `FlashlightIsOn` function doesn't work when you're sitting in a vehicle, making it useless for the pod controller.

**Comment by Divran** [comment]
Maybe, not sure how though

**Comment by thegrb93** [comment]
input.LookupBinding("inpulse 100")

**Comment by oldmud0** [comment]
@thegrb93 did you mean: `impulse 100`?

**Comment by thegrb93** [comment]
Ye

**Comment by Divran** [comment]
that's clientside only tho

**Comment by Damianu** [comment]
http://wiki.garrysmod.com/page/GM/AcceptInput Maybe? (didnt test it)

**Comment by Divran** [comment]
@Damianu `Called when a map I/O event occurs.` doesn't look like that'd work
