### ISSUE TITLE
Wiremod not working for gmod, at all.

### ISSUE THREAD

**Issue by VenipedeGaming** [wiremod/wire#1467]
So, when I subscribe to wiremod, its not fucking there. I tried literally everything, unsubscribing and resubscribing, subscribing outside of gmod, even fucking uninstalling and reinstalling gmod, but nothing has worked. I even deleted the addons file and it still doesn't work, its been like this for too fucking long.

**Comment by Divran** [comment]
This is for single player (or a locally hosted server), right?

Anyway, try not using workshop, because it's a pile of shit. Unsubscribe from wiremod on workshop, then open gmod and type `menu_cleanupgmas` in console to make sure it's deleted. Then you can optionally delete the garrysmod/downloads folder for good measure.

After that, simply go to this github repo's main page: https://github.com/wiremod/wire and then click "download zip" in the top right corner. Unzip it, and put it in your addons folder. Make sure it's placed in such a way that it looks like this: `addons/wire-master/lua` (and not like this `addons/wire-master/wire-master/lua`, which can happen if you unzip it the wrong way).

**Comment by VenipedeGaming** [comment]
Thanks mate! After a year, I can finally enjoy wiremod!

**Comment by CaptainPRICE** [comment]
Close this?
