### ISSUE TITLE
Linked Vehicle output for camera controller

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#1485]
The pod controller has the Entity output which returns the vehicle it is linked to. I would like to see the same thing added to the camera controller.

**Comment by Nebual** [comment]
Little known fact: the Cam Controller can apparently be linked to multiple vehicles at once. I doubt many use this, but it does make adding an output awkward. The first entity? The most recently linked? An array of linked entities is unpleasant but technically correct.

**Comment by thegrb93** [comment]
Nebual is right. Use an entity marker instead.

**Comment by Divran** [comment]
Little known fact 2019 edition: Linking cam controllers to multiple entities at once is actually useful, because 99% of the time the way you want to use the cam controller is
* set position to local, and leave it unwired `0,0,0`
* enable clientside movement

so if you do this, which is the recommended way anyway, and then link it to all seats in your vehicle, you now have a (for example) tank where each person has the same 3rd person view but control their own camera.
