### ISSUE TITLE
Limit E2 Array size

### ISSUE THREAD

**Issue by gamerpaddy** [wiremod/wire#1493]
Filling up a array with random stuff allocates more and more RAM on the server until e2 gives an "not enough memory error" and the server crashes with a lua panic error.  depending on how much memory the system got, the whole system could crash

it may be an good idea to limit arrays somehow. not sure about sub arrays.

''```
@name 
@inputs 
@outputs
@persist S:string A:array I I3 S2:string
@trigger 
runOnTick(1)

while(perf()){
    I++
    for(I2=1,8){
        S="asdh":repeat(randint(1,50000))+randint(1,50000)
        A[I^I2,string] = S
    }
}

```
''

if possible, someone please delete this post after reading / checking if you can reproduce it, before someone mad could use this abusively.

**Comment by Divran** [comment]
We already know about this and arrays are not the only way to crash servers in this way. Limiting arrays would solve nothing. Instead, try enabling this feature https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L605 using the console commands in the code linked above. 

This will shut down all E2s at once if it notices the server is in general using too much ram, because there's no foolproof way of checking each individual E2. So after this causes all E2s on the server to shut down, you can use admin powers to investigate the cause and ban people responsible.

I would also appreciate it if you could report back on how well this works because I haven't heard anything about it.
