### ISSUE TITLE
E2: Bad UDF non-void "didn't return a value" error throwing

### ISSUE THREAD

**Issue by Monkatraz** [wiremod/wire#1529]
```
@name test

function number breakE2(Test:number){
    
    if(Test){
        
        return 1
        
    }else{
    
    }
    
}

Num = breakE2(0)
```

This will throw this error:
`Expression 2 (test): addons/wire-master/lua/entities/gmod_wire_expression2/core/e2lib.lua:137: attempt to concatenate a table value`
 rather than the correct
`Expression 2 (test): Function test() executed and didn't return a value - expecting a value of type array`
(this is for a different function, but I couldn't actually get it to throw this error again, it seemed to be permanently broken after I successfully found a way to reproduce the line 137 error)

This exact error pops up with other, apparently correctly written, E2s. This includes some of my own E2s. I'm not sure how they're throwing this error, or else I would give you one of their functions.

I would recommend reverting the recent UDF error throwing changes as some servers automatically update to the Github, at least until this is fixed for sure.

**Comment by bigdogmat** [comment]
This is caused by the fact `E2Lib.generate_signature` when given argument names only expects a table full of the names. The table passed by the function operator gives it a table full of tables for each argument that contain the name and type. A table in the required format is never given so it can just be generated on the fly.

```lua
local ArgNames = {}

for k, v in ipairs(Args) do
  ArgNames[k] = v[1]
end
```

Right above https://github.com/wiremod/wire/blob/f8bc03f1a0917cd9f2b3adeee13f43765425ba00/lua/entities/gmod_wire_expression2/core/functions.lua#L47 and pass `ArgNames` instead of `Args`.

**Comment by Divran** [comment]
@Nebual
