### ISSUE TITLE
Callable strings don't work with numbers as arguments

### ISSUE THREAD

**Issue by axelsandinpekka** [wiremod/wire#1567]
Using numbers as arguments with callable strings don't seem to work.

```
function void func_0() {
    print("func_0")
}

function void func_1(A:number) {
    print(A, "func_1")
}

function void func_2(A:string) {
    print(A, "func_2")
}

function void func_3(A:vector) {
    print(A, "func_3")
}

"func_0"()
Call0 = "func_0"
Call0()

"func_1"(5)
Call1 = "func_1"
Call1(10)

"func_2"("1")
Call2 = "func_2"
Call2("2")

"func_3"(vec(1, 2, 3))
Call3 = "func_3"
Call3(vec(4, 5, 6))
```

This prints:
```
func_0	
func_0	
1	func_2	
2	func_2	
[1,2,3]	func_3	
[4,5,6]	func_3
```

But it should print:
```
func_0	
func_0	
5	func_1
10	func_1
1	func_2	
2	func_2	
[1,2,3]	func_3	
[4,5,6]	func_3
```
Skipping the function with number argument.

**Comment by bigdogmat** [comment]
This happens because you're calling the `print` function with a number and string argument, that has a specific meaning.

E.g.
```
print(_HUD_PRINTCENTER, "Hi")
```

`_HUD_PRINTCENTER` is really just a constant number. In your case you're calling it with 5 and 10 which are not valid enumerations for said function, so it just doesn't do anything.
