### ISSUE TITLE
E2: entities/gmod_wire_expression2/core/table.lua:279: attempt to compare number with nil

### ISSUE THREAD

**Issue by zazi125** [wiremod/wire#1574]
Example:
```
@name 
@inputs TAB:table
@outputs 
@persist 
@trigger 
if (TAB) {}
```

**Comment by Divran** [comment]
huh that should be impossible
I'll have to test it when I get the time

**Comment by AbigailBuccaneer** [comment]
Hmm. The issue here is that E2's internal representation of tables doesn't match the rest of Wiremod's. In particular, `wirelib.lua` defines:

```Lua
WireLib.DT = {
    -- ...
    TABLE = {
        Zero = {}
    },
    -- ...
}
```

And `gmod_wire_expression2/core/table.lua` defines:

```Lua
local DEFAULT = {n={},ntypes={},s={},stypes={},size=0}

registerType("table", "t",
    table.Copy(DEFAULT), -- default value
    function(self, input) -- input serializer
        if input.size == 0 then
            return table.Copy(DEFAULT)
        end
        return input
    end,
    nil, -- output serializer
    -- ...
)
```

E2 tables are internally split into two subtables, one for number keys and one for string keys. I think this is unnecessary. But E2 tables also record the types of the values in them, which I think *is* necessary, as you can't always differentiate between types just by inspecting them (see `E2Lib.guess_type`).

I think we've only ever avoided this issue because nobody has ever written any entities that input/output tables, except `gmod_wire_damage_detector`'s output. If you wired one of those to the `TAB` input above, it'd give the same result.

The input and output serializers are supposed to handle exactly this case of E2's internal representation being different to the rest of Wiremod. But the input serializer and output serializer both assume that the E2 representation is the one used by the rest of Wiremod. This means that E2s can send tables between them just fine but E2s can't accept non-E2 tables as input, and E2 tables won't make much sense when output to any other entity.

We could make the input and output serializers do the right thing and keep the internal representation of E2 tables the same, but that'd lose information (as we'd have to `E2Lib.guess_type` all the values in the input serializer). I wonder if we could change the internal representation to mean that type information gets stored outside of the table? Something like:

```Lua
local valueTypesForTable = setmetatable({}, { __mode = "k" })

local function inputSerializer(t)
    if #t == 0 then t = {} end -- copy default tables, like we currently do
    if valueTypesForTable[t] then return end
    local valueTypes = {}
    for k, v in pairs(t) do
        valueTypes[k] = E2Lib.guess_type(v)
    end
    valueTypesForTable[t] = valueTypes
end

-- all the table code now gets the type of t[k] from valueTypesForTable[t][k], instead of t.ntypes[k] or t.stypes[k]
```

That would mean that E2s could pass tables between them and not lose any data (because the `valueTypesForTable` entries would still be there when a value is sent across the wire), but the table value itself would just be a regular table instead of a specially formatted one.

**Comment by Divran** [comment]
If you store types outside the table then von/json encoding would break and we'd have to use guess types there again

**Comment by AbigailBuccaneer** [comment]
Or we could just make sure that the `(json|von)(Encode|Decode)` E2 functions still write out and read in the same format that they currently use.

**Comment by bigdogmat** [comment]
Does anything actually rely on the definition of table in `wirelib.lua`? I'd imagine everything that uses the table type would use E2s structure.

**Comment by AbigailBuccaneer** [comment]
In fact, if we want to go the route of making E2 tables the only Wiremod tables there are, then I'd like somebody to extract the functions you need to manipulate E2 tables in Lua into `wireshared.lua` too - otherwise it's a datatype that's not technically specific to E2 but only E2 (and the damage detector, which does things hackily) knows how to use them.
