### ISSUE TITLE
Setting wire gimbal origin

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [wiremod/wire#1596]
You should be able to set the rotation origin of the model of the wire gimbal so that specific models can rotate properly without needing propcore.

**Comment by Divran** [comment]
Do you mean you want to be able to change the rotation axis position, or the rotation angle offset?

For example, if what you want is this: you spawn the long thin pole again and the gimbal rotates it around its center, but you want it to rotate around one of the sides instead, that means you want to change the rotation axis position.

If I spawn a prop shaped like a long thin pole, and the gimbal rotates it so that the long end points toward the target input, but you want it to rotate so that one of the short pointy ends is pointing toward the target input, that means you want to change the rotation angle offset.

"rotation origin" does sound like the former, but I'm not sure if that's what we should add, because the gimbal works by using `SetAngles` and changing the axis position would involve also using `SetPos`

**Comment by EmergencyTemporalShift** [comment]
Sorry, I forgot about this suggestion. Lets say you set wire_gimbal_model to "models/mechanics/roboticslarge/a1.mdl" The orgin at which it rotates by default is on the side, hardly ideal for pointing at things.

**Comment by Divran** [comment]
yeah adding that to the way the gimbal works right now would be a pain because it works using `SetAngles`, so adding an offset to position would require also spamming `SetPos` which would basically entirely prevent you from using it on a moving contraption (that's already a bad idea but still).

Back when I posted my last message, I did work on changing the way it works to move by applying rotational force instead, which means it always rotates around the center of mass, but I never finished it

**Comment by AbigailBuccaneer** [comment]
Would it be possible to do something clever with parenting and `SetAngles`? If we created a dummy entity at the point to be rotated around, and parented the prop to that entity, then we could just `SetAngles` the dummy. @EmergencyTemporalShift would it satisfy your use case if the facer had to be non-solid to rotate around a point other than its origin?
