### ISSUE TITLE
Two-way Radios don't dupe correctly in multiplayer

### ISSUE THREAD

**Issue by TMinusBlastedRocket** [wiremod/wire#1610]
This bug is a old one but it needs fixing so when I dupe a two way radio outside of the session that it was created in even in the same server but not single player two things happen first  it and everything connected becomes a world prop then it de-welds everything connected. I dont know why this happens as I am not great at LUA but please fix this.

**Comment by Grocel** [comment]
It is probably caused by Garry-Dupe (Adv Dupe is probably using it as well with the duplicator Lua library) saving ALL variables even unstorable ones such as entities (that can be outside the dupe). Duping an entity even breaks the duplicator if it has circular references in it.

To fix it you need to filter out the data right for before it is saved in the ```ENT:OnEntityCopyTableFinish(data)``` hook.

The data variable is a copy, BUT not a deep copy of the entity table. To apply a filter, you can modify it, but be aware that changing nested tables (instead of replacing them) results in changes of their originals in the Entity. This could cause the entity to behave in a not expected manner after loading it in the duplicator buffer.

**Comment by Andrew-Eathan** [comment]
I had the same problem, but with a regular radio. It only seemed to happen once or something.

**Comment by thegrb93** [comment]
Only lua error I found is when undo'ing a duped twoway radio. Will look into it.
