### ISSUE TITLE
E2: changed() functionality

### ISSUE THREAD

**Issue by RainbowWings** [wiremod/wire#1681]
So I am not exactly sure about the changed function working, unless it is its intended way to work like that. Basically in code terms what is my idea how changed should work is
`changed(Value)`
should work the same way as
`$Value&1`

I am working on a code, where some values when changed triggers some timers. After some time I found the changed() function doesn't return 1 where I would expect it to do (as I stated above). I wrote a piece of code ([changed_test.txt](https://github.com/wiremod/wire/files/2190660/changed_test.txt)) where the results showed me that the idea I have, doesn't work.

Printed results where basically the value of changed() function result should be the same as delta result, but they aren't:

//First execution
1	=	First: changed=1/Delta=1
//interval 100
1	=	interval: changed=1/Delta=1
2	=	interval ang(2): changed=1/Delta=1
3	=	interval ang(1): changed=1/Delta=1
//interval 1000
1	=	interval: changed=0/Delta=1
2	=	interval ang(2): changed=0/Delta=1
3	=	interval ang(1): changed=0/Delta=1

I feel like that the changed() function stores an array of values that have been assigned to that variable somehow, and detects if the value isn't in the array? Is this the the intented functionality or is it a bug?

**Comment by bigdogmat** [comment]
The delta operator gives the difference between the last value and the current value. It does this by storing the old value whenever it's assigned to.

The `changed` functions work by storing the expression they're used on and the value it returns. Every instance of the `changed` function uses a different expression, even if it looks the same as another one. It doesn't look at the variable used in it or anything.

Another thing is that the `changed` operator will always return `1` on its first run.

For example,

```
for(I = 1, 2)
{
    print(changed(I))
    print(changed(I))
}
```
The output of this will be
```
1
1
1
1
```
Even though the value doesn't change between the first and second print it still prints `1` because they're separate expressions.

**Comment by RainbowWings** [comment]
Oh, I see. I thought that it works pretty the much the same as the delta functionality with extension to custom expressions which aren't a variable, but here it stores the value it returned for every changed() used separately in the code (every instance as you stated, where I kinda struggled to understand).

Basically I have a bigger code, with timer sections, where each section run only when needed. What made me ask about the changed() is that, a section A set a persist variable then stopped running and switched to section B. The section B changed the same variable to a different value, stopped running and switched back again to the section A. Section A set value the variable back to the value which was set the last time in section A before the changed() was ran, therefore the changed() return 0 where I was expecting it to return 1.

I guess I'll just have to use something else, like the delta itself although its more expensive. Thank you for explaining, very much appreciated.
