### ISSUE TITLE
Add function to printcolor in console

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#1693]
```
# _HUD_PRINTCENTER, _HUD_PRINTCONSOLE, _HUD_PRINTNOTIFY, _HUD_PRINTTALK

printColor(array(_HUD_PRINTCONSOLE, vec(0,255,0), "what1"))
printColor(_HUD_PRINTCONSOLE,vec(255,0,0), "what2")
print(_HUD_PRINTCONSOLE, "what3")
```

![code output](https://i.imgur.com/xmLDsMj.png)

I'm not entirely sure how all of those constants should work, as console print is the only one I use.

**Comment by TomyLobo** [comment]
do these other places even support color?

**Comment by shadowscion** [comment]
Unlikely, but console should be fixed.

**Comment by TomyLobo** [comment]
well, it's not easy. if you introduce a number parameter, you break everyone's code that puts a number there.

**Comment by TomyLobo** [comment]
Ideally, those constants would have a special type that's not used for anything else, but that wasn't thought of either in the original implementation, so if you introduce that type now, you'd break code that stores those constants in a number variable

**Comment by Codingale** [comment]
`Warning! Decimal values are for reference only! The actual value may be different between two Garry's Mod versions.` 

Why not slap that warning everywhere haha.

**Comment by bigdogmat** [comment]
It does, however there's an issue that if someone originally used a number as the first argument to `printColor` it would now be interpreted as a print type.

**Comment by Codingale** [comment]
Honestly, if you're using print color, for the default color what's the point?
In my time running a few servers, most who've asked me for help wanted `_HUD_PRINTCONSOLE` to print to color in the console, they asked me how I could work around it and I said you can't really.

I see why for backwards compatibility but honestly this train of thinking could result in us constantly thinking that for every change. I've seen it happen, a lot has changed and if your contraption breaks because of a print statement you need to recode it anyways.

**Comment by thegrb93** [comment]
printColor in console would be MsgC

**Comment by shadowscion** [comment]
What should the new function be called?

**Comment by thegrb93** [comment]
printColorC maybe
