### ISSUE TITLE
EyePod component is borken

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1807]
I remember using eyepod some day ago, and I had problems using it, was bugged a lot (including popup UI info wasn't saying correct stuff, tool settings being ignored, it has a gimbal-lock bug too I believe, etc.)

**Comment by Divran** [comment]
The eye pod doesn't output angles, it's actually impossible for it to have gimbal lock problems on the output https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_eyepod.lua#L66

The only angle it has is an input (which can be modified via `SetPitch`, `SetYaw`, or `SetViewAngle`). Although I haven't tested it yet, It's not impossible for it to have gimbal lock issues here, which would affect the angle at which the player's camera is locked.

If there is a gimbal lock problem, it's most definitely caused by this https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_eyepod.lua#L268
If it is, a solution would be to implement matrix addition instead of euler addition like @thegrb93 did in another recent PR.

That said, keep in mind that the eye pod is pretty much made obsolete by the cam controller.

**Comment by thegrb93** [comment]
I used eyepod last weekend and no problems. That +90 yaw shouldn't be an issue either since only the pitch and yaw are used and yaw is rotated before pitch. Maybe you are thinking of another entity.
