### ISSUE TITLE
dhdd data not saving after duping with all 3 duplicators(adv dupe 1 2 and normal dupe)

### ISSUE THREAD

**Issue by iurirolho** [wiremod/wire#1818]
so i duped a drive since i wanted to make something that relied on the data being able to be carried after a dupe but it seems that on all those 3 it failed, i did ask 2 friends for help to figure stuff and both of them the data transfer failed one of those friends did a test with lower data and still was lost, since me and 3 friends did this test i assume its broken but idk in what way, i did test in sp and mp but in mp only with adv dupe 1 but both friends also tested only in mp, with that all said i await a reply from anybody that has know-how in this subject.

**Comment by iurirolho** [comment]
another note rom also has the same issue

**Comment by iurirolho** [comment]
a friend of mine tried compressing the data to 9 bytes and still did not save, my file was also 49bytes, idk if that could be the issue

**Comment by iurirolho** [comment]
50k is less more than 49bytes, right?, or am-am getting the measurements confused

**Comment by TAbdiukov** [comment]
I just double-checked, you can save up to ![https://latex.codecogs.com/gif.latex?512%5E2](https://latex.codecogs.com/gif.latex?512%5E2) of addresses, and each address, i believe, is at least 2 bytes long (since you can easily save numbers > 255) . Hence we should have 

![https://latex.codecogs.com/gif.latex?%282%5E9%29%5E2%20*%202%20%28%5Ctextsc%7Bbytes%20each%7D%29%20%3D%202%5E%7B19%7D%20/%201024%20%28%5Ctextsc%7Bto%20get%20KB%7D%29%20%3D%202%5E9%20KB%20/%201024%20%28%5Ctextsc%7Bto%20get%20MB%7D%29%20%3D%202%5E%7B9%7D/2%5E%7B10%7D%20%3D%20%5Cfrac%7B1%7D%7B2%7D%20MB](https://latex.codecogs.com/gif.latex?%282%5E9%29%5E2%20*%202%20%28%5Ctextsc%7Bbytes%20each%7D%29%20%3D%202%5E%7B19%7D%20/%201024%20%28%5Ctextsc%7Bto%20get%20KB%7D%29%20%3D%202%5E9%20KB%20/%201024%20%28%5Ctextsc%7Bto%20get%20MB%7D%29%20%3D%202%5E%7B9%7D/2%5E%7B10%7D%20%3D%20%5Cfrac%7B1%7D%7B2%7D%20MB)

I will write some test read & write e2 scripts once I get back home, but **betweeen you and me**? Just use the E2 fileWrite to save your data... You can save more, faster, easier  and no need to design a file system for DHDD

**Comment by thegrb93** [comment]
Advduplicator has something like a 50k file size limit

**Comment by iurirolho** [comment]
When I rebuild something I tough using that tool as that was a good way to make some of the things interchangeable

**Comment by iurirolho** [comment]
My project would use that as a quick swap for the data, btw am not at home atm

**Comment by iurirolho** [comment]
am home now so i can write a more detailed info on how i intended to use it, i intended to use it as a swappable storage medium on demand to use it as data storage in order to decrease how much space it would take, since the old way i did the data was paired to the reader and was too big and laggy on spawning and that's how i came with that idea to shorten the sizes and load times as well as lag times sort of, so with all that said i hope we find something useful in regards to the issue the dhdd and rom have as well.

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_dhdd.lua#L112

You can see it should only save the first 1k. Does that at least work?

**Comment by iurirolho** [comment]
yep, good point, i tried with rom as well as a test and both refused to save, and when my friend tried to compress the data even more both rom and dhdd failed

**Comment by thegrb93** [comment]
Lol, looks like whoever wrote it forgot to add the code that reads the memory from the dupe.

**Comment by thegrb93** [comment]
Should be an easy fix.

**Comment by iurirolho** [comment]
oh wow, thx, sometimes it takes one to notice it so others fix it

**Comment by adosikas** [comment]
Just mentioning #1816 here. 

Also for completeness,  Kilo/Mega/Giga are a factor of 1000, just like kilometers, kilograms etc.
If you want to use the factor of 1024, the prefixes are Kibi/Mebi/Gibi-Bytes.

**Comment by iurirolho** [comment]
i might as well ask this, i recorded some data while this bug was present, would reloading it again once fixed allow me to keep the data duped or i would have to store it again?

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/1816/files going to link this here so I can make sure it gets merged and doesn't conflict with anything.

**Comment by iurirolho** [comment]
good, i cant wait to see the feature working again, keep the great work wiremod devs and contributors

**Comment by thegrb93** [comment]
From what I can tell the data is duped correctly, it just incorrectly says the size is 0. https://github.com/wiremod/wire/pull/1816 fixes that.
