### ISSUE TITLE
cancel button in wire text entry entity resets output string

### ISSUE THREAD

**Issue by Andrew-Eathan** [wiremod/wire#1819]
while typing in a wire entry, clicking cancel will not leave the output as it is, instead it will reset it to blank.

**Comment by Andrew-Eathan** [comment]
the one where you click E on it and it brings up some sort of input menu and you have 2 buttons: one submits the input and one closes the tab (aka cancel)

**Comment by thegrb93** [comment]
Still don't know what you're talking about. Is it an entity?

**Comment by thegrb93** [comment]
The wire Text Entry entity?

**Comment by Andrew-Eathan** [comment]
Yes, that one.

**Comment by thegrb93** [comment]
No spam allowed https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_textentry.lua#L157

**Comment by CaptainPRICE** [comment]
> No spam allowed

that's not really anti-spam.
btw, if you read the code:
> local ent = Entity(...)               -- handle to the text entry entity, make it valid one, plz. also, **be sure you're using the entity**, thanks.

**Comment by thegrb93** [comment]
self.User gets set to nil after receiving that net message.

**Comment by CaptainPRICE** [comment]
> self.User gets set to nil after receiving that net message.
ezpz. stay nearby the entity, aiming at it the whole time.
one option, using (client-side) Lua code still:
```lua
RunConsoleCommand("+use") -- add this flag for 1 tick, then remove on the next, after sending out a net message. maybe even hook it up via hooks if it works: PlayerEnteredVehicle/PlayerExitedVehicle
```
second option, using `User` entity, face it towards the text entry entity, and trigger the `Fire` output, bam.
third option, using E2 functionality, just call `entity:use()`, bam.
fourth option....
profit. back to spamming.

>  Regardless, don't you think writing a fix, if one is needed, would be a lot more productive?

i set not to. because, if i do that fix here, it would be local fix to just this particular addon to address only that single net message from spam. which is just waste of time, useless simply. it could also create collisions...
therefore, i fix such a thing differently, it works on a greater scope - binary level.

simply detour `net.Incoming` and `usermessage.IncomingMessage` functions... so, whilst it can be quick-fixed using server-side Lua script that way, it'd become ugly af to maintain. besides, it is CAC detected.

**Comment by thegrb93** [comment]
So 1 valid net receive per 2 ticks. I don't think you understand how net.receive abuse works.

**Comment by thegrb93** [comment]
net.receive abuse is when you find an expensive net.receive that uses tons of cpu, then spam it with 100s of net.Start each frame to jam up the server's cpu. It has nothing to do with flooding.

**Comment by Andrew-Eathan** [comment]
well i uhhh have no idea how to check it, i'm sorta new to github

**Comment by CaptainPRICE** [comment]
github is just an online platform. what you want to do is, [learn git](https://git-scm.com/).

**Comment by thegrb93** [comment]
Just save https://raw.githubusercontent.com/wiremod/wire/322fa39cef9343785dc9f96dbc612a1490cffb1f/lua/entities/gmod_wire_textentry.lua to wire/lua/entities/gmod_wire_textentry.lua

**Comment by Andrew-Eathan** [comment]
that fixes the issue

**Comment by Andrew-Eathan** [comment]
the text stays the same
