### ISSUE TITLE
[ZCPU] Getting Errors when there shouldn't be

### ISSUE THREAD

**Issue by MSTVIRUS** [wiremod/wire#1829]
I just discovered ZCPU yesterday and I really wanna get into using it but for some reason there are errors when there shouldn't be. For example, the "Hello World" example gets stuck at line 15 with Error #7[65536] and from reading the documentation this means that there was a memory read/write fault even though I haven't touched any of the code. In another example, similar to the "Hello World" example, I got Error Code 4 even though the opcode was highlighted and clearly talked about in the documentation

Here is the Hello World Example:
![zcpuproblems](https://user-images.githubusercontent.com/16159456/51412902-25a37300-1b3b-11e9-8724-7cf5e253eb97.png)

Here is the other example:
![zcpuproblems2](https://user-images.githubusercontent.com/16159456/51412928-3d7af700-1b3b-11e9-8f2f-89c0f62fa480.png)

**Comment by thegrb93** [comment]
It's always been buggy and difficult. Nobody is maintaining it either. You might want to open the hood yourself and try fixing what's wrong.

**Comment by thegrb93** [comment]
It is still an issue so it should stay open.

**Comment by cinder1992** [comment]
Actually, the CPU is working as-intended here.

In the first example, error 7 (Memory I/O Error) is being generated because there's (possibly) no console screen attached to the CPU's MemBus input.

In the second, the "Invalid Opcode" error is being generated due to a bug in your program.
the `Data` and `Code` meta-opcodes are like preprocessor flags, `Data` says "Put a jump to Code here" and `Code` says "If you encounter data, jump here", or something to that effect.

this is what the CPU sees. ( using the preprocessor `#pragma set OutputFinalListing`)
```
=== HL-ZASM High Level Assembly Compiler Output ==
     0 jmp 24
Line1:
     3 db "Hola craps it works!",0
_code:
Writestring:
    24 cmp #EAX,0
    27 je 44
    30 mov #EBX,#EAX
    32 inc EBX
    34 mov #EBX,999
    37 inc EBX
    39 inc EAX
    41 jmp 24
Writeend:
    44 ret 
Main:
    45 mov EBX,65536
    48 mov EAX,3
    51 call 24
==================================================
```
the CPU is jumping to location 24 in memory, which is the start of `Writestring`, which means `Writestring` is being run with EBX and EAX being unset. This results in the program overwriting the processor's memory with `999`, leading to the processor clobbering the whole Writestring function, and getting 999 instead of the intended opcode. 999 is not a defined opcode in `lua/wire/cpulib.lua` so it throws `Error #4[999]`

The program should work as intended by adding `jmp Main` after your Code declaration on line 6.

**Comment by thegrb93** [comment]
I'll reopen if there's any further problems.
