### ISSUE TITLE
Increase or decrease the default EGP max objects

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1860]
Right now I believe it is set to `300`.
I suggest to either increase this default value to `324`, or, decrease it down to `289`.
The reason? idk, just a fix idea with square roots and screen resolution...
Right now `sqrt(300) == 17.320508075689`, so, if I wanted to fill the EGP with max amount of "pixels", I have to set resolution to 17×17 and drop 11 extra pixels, or, set resolution to 18×18 and always have some blank space on the screen (24 pixels).

**Comment by adosikas** [comment]
You do realize that there is a lot more you can do with EGP than just making a worse version of the digital screen, right?

And if it were made it a square number, and someone would need a couple more objects to maybe draw a background, a title, or whatever, that wouldn't line up.

And i would argue keeping it at a "round number", such as 300 is much more logical than arguing about abstract mathematical thoughts, like square numbers. The only reason to have limits at a "arbitrary" numbers would be if that were was a hard limit and giving everyone the *choice* of using the limit completely, instead of artificially limiting it to make the number "look good".

**Comment by thegrb93** [comment]
The limit is too high imo. EGP can induce a ton of network lag

**Comment by adosikas** [comment]
That would be an issue with [`wire_egp_max_bytes_per_sec`](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp/lib/init.lua#L24), not the total number of objects.

**Comment by Adorable-Catgirl** [comment]
What's the point in this other than "it feels good"?

**Comment by CaptainPRICE** [comment]
> What's the point in this other than "it feels good"?

None. I had opened this to have something to argue about.
