### ISSUE TITLE
E2/EGP: Add innerRadius function for polygon

### ISSUE THREAD

**Issue by CaptainPRICE** [wiremod/wire#1861]
Adding such a function would allow to draw more tasteful polygons.
By introducing a function for getting/setting the distance between the center and the innermost point.

Getter `number=wirelink:egpInnerRadius(polygonID:number)`
Setter `wirelink:egpInnerRadius(polygonID:number, innerRadius:number)`

Practically:
![egp-polygon-innerRadius](https://user-images.githubusercontent.com/9789070/55688844-d58bbe00-597d-11e9-857a-81eb4ed1c2ea.gif)

**Comment by adosikas** [comment]
Instead of making this a generic attribute for a single usecase (which I highly doubt is applicable to anything but regular polygons in a way that makes sense), a specialized `egpStar(ID, Points, OuterRadius, InnerRadius)` would make more sense.

Besides, you can already do this right now with polygons by doing something like this, with the first vertex in the center

```
function wirelink:egpStar(Id, Center:vector2, N, InnerR, OuterR, AngleOffset) {
  local Vx = array(Center)
  for(I=0, N*2) {
    Vx:pushVector2(Center+vec2(N&1?InnerR : OuterR, 0):rotate(AngleOffset+I/(N*2)))
  }
 This:egpPoly(Id, Vx)
}
```

**Comment by CaptainPRICE** [comment]
> Besides, you can already do this right now with polygons by doing something like this

I'm not sure what you're trying to do there (tried to get your function to work)..
But, `innerRadius` should be a function that would work for any non-concave polygon (free-form shape).
In other words, this is not trying to accomplish exactly those shapes which are being presented on gif (with point count) into a single function - it is just an illustration of how innerRadius works.
