### ISSUE TITLE
E2: Some optimizations don't take into account value types

### ISSUE THREAD

**Issue by spgill** [wiremod/wire#1975]
This is one that came out of the blue. This particular line of code;

`holoCreate(2000, vec(13, 0, 32), vec(0.25, 4, 0.25) * 0, ang(-85, 0, 0))`

results in this error message as a hint upon pasting the E2;

`No such function: holoCreate(number, vector, number, angle)`

_Note: this error never shows in the editor, it only shows upon pasting the chip_

If I remove the multiplication entirely _OR_ change the multiplier to a number other than `0` it works just fine.

**Comment by bigdogmat** [comment]
This is due to the optimizer not caring about value types when applying optimizations. e.g. it assumes anything multiplied by zero is zero. This could be done by either applying a type check, or replacing the _zero_ value with the default value of the type.

Though there's an issue with trying to do that and that is the optimizer doesn't know about types. I've talked to @AbigailBuccaneer about adding another pass that gathers type information. However I haven't had the time to implement such a thing.

**Comment by spgill** [comment]
Gotcha gotcha

Something interesting to note is that this wasn't an issue in the past.

I had used the exact same E2, without any modifications last year (I think around May 2018). But without changing any of this E2's code it suddenly threw the noted error when I tried to plop it down recently.

**Comment by TomyLobo** [comment]
@bigdogmat the optimizer should never replace one type by another. better remove that particular optimization right away and put it back once it has been fixed.
This could be potentially catastrophic.

Also, why can't the optimizer be applied client-side?

**Comment by bigdogmat** [comment]
@spgill It was added semi recently, so that makes sense

@TomyLobo Even though it'll cause confusing bugs it shouldn't cause anything catastrophic. The optimizer is just a pass between the parser and compiler and any type differences are error'd out there.

> Also, why can't the optimizer be applied client-side?

The optimizer runs E2 functions for constant propagation. Functions only exist server side.

**Comment by TomyLobo** [comment]
I hope the optimizer knows which functions have side-effects and which don't.
I really hope so...

**Comment by AbigailBuccaneer** [comment]
Oops, good catch! I'll fix this ASAP; the short term fix might just be to disable those optimizations until a typechecking pass exists.

> I hope the optimizer knows which functions have side-effects and which don't.
I really do

Yes, it has a whitelist, it only applies operators. See [the code for the constant propagation pass](https://github.com/wiremod/wire/blob/ac28f13a23fc293d0dabc140d49995efc399b021/lua/entities/gmod_wire_expression2/base/optimizer.lua#L41-L91). It's designed to be extensible - I've been meaning to add an extension to the E2 extension language that lets a function be annotated as side-effect free so they can be evaluated at compile time too.

> Also, why can't the optimizer be applied client-side?

The client doesn't have the definitions of the E2 functions (like `op:add`) that are needed to evaluate the results.
