### ISSUE TITLE
KEY_DOWN and KEY_ESCAPE have matching memory numbers on the Keyboard

### ISSUE THREAD

**Issue by marchcain** [wiremod/wire#2013]
Not a big deal since KEY_ESCAPE can't _really_ be used properly, but still should probably be fixed if possible

**Comment by Divran** [comment]
Apparently it's always been this way for as long as the wire keyboard has existed. I don't want to change the values for the arrow keys now since people have gotten used to those values and probably check for them in the code, so if this is to be changed, the escape key should be the one that is changed.

As you say tho, the escape key probably can't be used anyway since the game will intercept it and always use it to open the main menu as far as I know.

Another question is, if we change it, what do we change it to?

**Comment by marchkarcz** [comment]
I'm pretty sure spaces 11-16 are open (although not certain), but I'm not 100 percent sure. If not important, maybe just removing the escape key entirely from the code would be the right solution considering the game will always intercept it (unless there's some fancy lua magic that could possibly cancel the intercept, but as far as I'm aware that's not possible, right)

**Comment by Divran** [comment]
Are you able to unbind escape and rebind the "Open main menu" key to something else? I haven't actually tried that

**Comment by marchkarcz** [comment]
You can't unbind the escape key it seems. However I think you can bind "cancelselect" to another key, but esc will still work

**Comment by thegrb93** [comment]
Just delete this https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_keyboard/remap.lua#L71
