### ISSUE TITLE
Pod Controller Output Menu

### ISSUE THREAD

**Issue by Gracefulmender2** [wiremod/wire#2042]
When you select the output of a pod Controller, it does not start at the top (W), it starts at the second option (A).

**Comment by Divran** [comment]
The wire tool will try to automatically move the cursor to an output with the same name as the selected input. If you've selected an input named "A" it'll start there. Here's what happens when selecting an input named "Space" from an E2
![image](https://user-images.githubusercontent.com/1485728/79032564-e336dd80-7ba7-11ea-9114-da312ffe1f8c.png)

If you select an input that doesn't match anything, it'll use whichever it tried the last time.

**Comment by Divran** [comment]
I suggest asking simple questions like this on the discord <https://discord.gg/H8UKY3Y> to get help faster.
If you're unsure if it's a bug you can ask on discord first and if someone says it's a bug you can then create a bug report here on github.
