### ISSUE TITLE
circular include with #ifndef not properly validated

### ISSUE THREAD

**Issue by KoromaruKoruko** [wiremod/wire#2146]
# /file1.txt
```
@persist Var1

function void func1()
{
}

#ifndef func2()
#include "file2"
#endif

```
# /file2.txt
```
@persist Var2

function void func2()
{
}

#ifndef func1()
#include "file1"
#endif

```

the continuous code should look like this
```
@persist Var1
function void func1()
{
}
##include "file2"
@persist Var2
function void func2()
{
}
```

but if you directly use file1 or file2 it comes up with this error
```
file1: include 'file1' -> Directive (@persist) contains multiple definitions of the same variable at line 1, char 10
file2: include 'file2' -> Directive (@persist) contains multiple definitions of the same variable at line 1, char 10
```

which means the validator for some reason doesn't interpret the function definition in the first file
and the continuous code actually looks like this
```
@persist Var1
function void func1()
{
}
##include "file2"
@persist Var2
function void func2()
{
}
##include "file1"
@persist Var1
function void func1()
{
}
```

now if you include file1 or file2 from a third file, file3 the error vanishes

# /file3
```
#include "file1"
#include "file2"
```

the validator properly interprets the code, and throws no errors!

## take away
so to wrap it up, for some reason the validator does not take into account the function definitions for the preprocessor blocks within the first file/open file. But will properly handle subsequent files.
Effect:
if you are developing a complex library over multiple files that require inter-dependability you are unable to properly validate the files and have to open a separate file to import the library and run the validator properly!

**Comment by adosikas** [comment]
This has nothing to do with includes, and is not a bug.

`#ifdef` is not supposed to work with custom functions (infact it cannot, because custom functions are only declared during runtime, while the preprocessor runs way before that).

This problem has been brought up before, the answer was that you should build a lookup table that you fill as you the function declaration runs, and check against that. IMO bad design, but w/e.

```
@persist DeclaredFunctions:table
if(first()) { # only declare the function once
  function bla() {
  }
  DeclaredFunctions["bla", 1] = 1  # alternatively save a more detailed signature
}
elseif(someClk()) {
  if(DeclaredFunctions:exists("bla")) {
    bla()
  }
}
```

Alternatively you could put your #includes inside an `if(FILE1_LOADED)`, because (just like function defintions) #includes are evaluated during runtime.
