### ISSUE TITLE
jsonDecode crash

### ISSUE THREAD

**Issue by klen-list** [wiremod/wire#2176]
### Step to reproduce
```lua
@name
jsonDecode("{\"\":":repeat(50000) + "{}" + "}":repeat(50000))
```

**Comment by klen-list** [comment]
https://user-images.githubusercontent.com/49125075/121777850-c8416e00-cb9c-11eb-974f-68afccde12f1.mp4

**Comment by Divran** [comment]
this uses a gmod function called `util.JSONToTable`
<https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/serialization.lua#L419>
the only way to fix this would be to implement our own json parser in order to add quota checks to it.

The problem could be alleviated slightly by adding a prf check just after adding the length of the string to prf, but that wouldn't fix it entirely.

**Comment by thegrb93** [comment]
You sure it's getting frozen and not a stack overflow? This looks more like a stack overflow.

**Comment by thegrb93** [comment]
Yeah, its a stack overflow crash. The only solution is to wait for gmod devs to fix it.

**Comment by Divran** [comment]
which most likely is not happening

**Comment by TomyLobo** [comment]
do we want to create our own lua-only json parser?
or use a premade library maybe?

**Comment by TomyLobo** [comment]
https://github.com/rxi/json.lua/blob/master/json.lua here's an MIT-licensed one that doesn't look too bad.
