### ISSUE TITLE
Hydraulic length issue

### ISSUE THREAD

**Issue by DoomMarine91** [wiremod/wire#2262]
soo i have no idea what you guys did but it seems that Hydraulics dont work right anymore now 

for instance say your Hydraulic's length = 15.5 well when your car drives now it will add a little to itself despite you telling it to stay at 15.5 why?

**Comment by Divran** [comment]
This github page is meant for bug reports. If you need help with something that isn't a bug, please go to https://discord.gg/H8UKY3Y

Since you provided no information about your setup, I can only assume it's something you did wrong. If you go to the discord channel and post more information, some images, maybe a video, or even a dupe file, loads of people there will be able to help.

If it turns out to be a bug after all, we can go back here and reopen this ticket.
