### ISSUE TITLE
addons/wiremod/lua/entities/gmod_wire_rt_screen.lua:202: assertion failed!

### ISSUE THREAD

**Issue by Aws0mee** [wiremod/wire#2263]
Hello I have no context whatsoever but this error was being spammed when you look in a certain direction in my server
```
[wiremod] addons/wiremod/lua/entities/gmod_wire_rt_screen.lua:202: assertion failed!
  1. assert - [C]:-1
   2. DrawScreen - addons/wiremod/lua/entities/gmod_wire_rt_screen.lua:202
    3. unknown - addons/wiremod/lua/entities/gmod_wire_rt_screen.lua:281 (x435)
```

**Comment by Vurv78** [comment]
@stepa2 ?

**Comment by Divran** [comment]
Yeah I saw this earlier but didn't have time to reply at the time. Pretty sure I could fix it myself if I took a look at it, but I'm definitely gonna give @stepa2 some time to respond first.

Generally assert should not be used at all outside of unit tests. The assert should probably simply be an if statement instead, so that if the assert fails, it does nothing rather than throw an error.
