### ISSUE TITLE
[BUG] E2 serverside error: attempt to index field 'directives' (a nil value)

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2311]
This error occured a few times today, not sure how to replicate it.
Serverside error:
```
addons/wire/lua/entities/gmod_wire_expression2/init.lua:366: attempt to index field 'directives' (a nil value)
   0.  __index - [C]:-1
    1.  ResetContext - addons/wire/lua/entities/gmod_wire_expression2/init.lua:366
```

**Comment by thegrb93** [comment]
Whys the stack trace so small? Need bigger stack traces

**Comment by thegrb93** [comment]
I believe this is @Vurv78 's code. Any chance the block on line 366 can be moved to compile?

**Comment by Vurv78** [comment]
Don't remember any reason as to why it's there, but since ResetContext completely empties the table, if it was moved under the call then it wouldn't have self:throw at all, and it looks like if the code didn't change it never calls compile on the chip and just resets it?.

So it might be fine to move but could we also just do ``self.directives and ...`` to be safe.

Also would be nice to know why ``self.directives`` is nil there in the first place

**Comment by thegrb93** [comment]
probably because the Compile call failed

**Comment by thegrb93** [comment]
@Vurv78 mind fixing it?

**Comment by thegrb93** [comment]
@wrefgtzweve need a better stack trace

**Comment by thegrb93** [comment]
Feel free to report again if you get a better stack trace and it pops up again

**Comment by thegrb93** [comment]
(the stack trace is the stuff below the error message btw)
