### ISSUE TITLE
e2 docs custom camera

### ISSUE THREAD

**Issue by deathking61** [wiremod/wire#2330]
why when using it there in a huge input delay for looking around? like say i use my mouse to look left it takes it 4 sec or so to respond despite using either run on tick or interval. any way to make this better?

**Comment by thegrb93** [comment]
Depends on your ping to the server. High ping while make the delay longer.

**Comment by thegrb93** [comment]
Better to use cam controller or starfall

**Comment by deathking61** [comment]
> Depends on your ping to the server. High ping while make the delay longer.

ok well i tried in SP and its just the same there so i dont think thats right

**Comment by Divran** [comment]
The camera controller can handle the majority of situations and it doesn't have any delay. In wiremod, that's your only delay-free option. If that isn't enough, you will have to look outside of wiremod, such as starfall, as was already suggested.

The E2 camera functions have a delay because E2 is serverside and rendering is clientside. By definition it can never be instant.

This github is for bug reports. If you have questions that aren't about bugs, go to the discord at <https://discord.gg/H8UKY3Y>

**Comment by thegrb93** [comment]
> > Depends on your ping to the server. High ping while make the delay longer.
> 
> ok well i tried in SP and its just the same there so i dont think thats right

There shouldn't be delay unless something is wrong with your code.
