### ISSUE TITLE
e2 entity doesn't call triggeroutput when removed

### ISSUE THREAD

**Issue by shadowscion** [wiremod/wire#2342]
maybe there is a good reason, but most other wire entities seem to call and pass a zero value to any linked entities when they are removed

**Comment by Divran** [comment]
nope literally just seems to be forgotten, see
<https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/init.lua#L219>
vs
<https://github.com/wiremod/wire/blob/master/lua/entities/base_wire_entity.lua#L418>


`WireLib.Remove` eventually reaches this line
<https://github.com/wiremod/wire/blob/master/lua/wire/server/wirelib.lua#L580>
which is what does the zero-setting

this is probably a bug caused by developers (including myself) not realizing it should be done this way, and I doubt E2 is the only one with the problem.

4:30 am right now so can't fix right now

**Comment by thegrb93** [comment]
Just need to add a baseclass OnRemove call
