### ISSUE TITLE
E2 self input wirelink stack overflow

### ISSUE THREAD

**Issue by Fasteroid** [wiremod/wire#2415]
An E2 chip writing to its own input via wirelink results in a Lua-level stack overflow:

[exploits/wirelink_stack_overflow.txt](https://github.com/Fasteroid/expression2-public/blob/master/exploits/wirelink_stack_overflow.txt)
```golo
@name exploits/wirelink_stack_overflow
@inputs Wtf
@outputs 
@persist 
@trigger

# by yours truly
# no idea what causes this
# needs more testing

E = entity():wirelink()
E["Wtf",number] = 1
```

It seems writing to the input triggers the chip to run again, which then runs it again (and so) on until stack overflow occurs.  Fortunately, it seems each execution is still subject to quota checks, so this can't be used to crash the server.

**Comment by thegrb93** [comment]
There's a limit somewhere for number of output triggers per frame for every wire entity (to prevent gate stack overflows). E2 should obey this limit.

**Comment by Vurv78** [comment]
> There's a limit somewhere for number of output triggers per frame for every wire entity (to prevent gate stack overflows). E2 should be updated to obey this limit.

Turns out it wasn't this. E2 registers a `postexecute` hook which triggers the inputs at the end of the execution if they're changed, which in turn calls :TriggerInput, which calls :Execute on itself. I decided to go for a WireLib level fix in case this happens with another component, and since TriggerOutput already has such limiting
