### ISSUE TITLE
EGP Hud connect/disconnect flickering when parented

### ISSUE THREAD

**Issue by KemGus** [wiremod/wire#2473]
**How to reproduce:**
Spawn EGP Hud
Parent it to something
Try activating
(for some reason sometimes it works fine and sometimes it is not)

**Here is a dupe with that issue**
[armor analyzer new.txt](https://github.com/wiremod/wire/files/9942834/armor.analyzer.new.txt)

**Comment by KemGus** [comment]
Anyone yet got any idea on this?

**Comment by Divran** [comment]
It's possible that the use action sometimes doesn't work on parented entities, but idk. 
If you are using the hud in a vehicle you can link it to the seat to get around this. I believe there is also a function specifically to toggle egp huds.

**Comment by Denneisk** [comment]
The child entity inherits(?) the `UseType` of the parent, which in most cases is 0 (`CONTINUOUS_USE`). The parent object could be modified to enable `SIMPLE_USE` (expected behaviour) but this might have issues in overriding intended functionality of other entities that have a different `UseType`. Not sure what the best course of action is from here.

**Comment by thegrb93** [comment]
I wouldn't try hacking a fix for it
