### ISSUE TITLE
Initialization Warning on Input Variables

### ISSUE THREAD

**Issue by Hazeofdream** [wiremod/wire#2480]
I get the warning, but it doesn't take into account persist, So a persisted variable can be considered "unset" even though it could just be defaulting to zero intentionally by the user or not set at runtime immediately.

![image](https://user-images.githubusercontent.com/74027566/201220928-8189c4bb-b7eb-48a6-a190-6602e8338f47.png)
![image](https://user-images.githubusercontent.com/74027566/201220979-a42dc4e2-5f76-4589-a005-8b78428c1eff.png)

**Comment by thegrb93** [comment]
I think an unset persist would fall into the same realm as an unset var. Probably just need a directive to disable the warning.

**Comment by Hazeofdream** [comment]
> I think an unset persist would fall into the same realm as an unset var. Probably just need a directive to disable the warning, or set the var in first().

I've also had this happen for inputs, which you aren't supposed to set manually.

**Comment by Vurv78** [comment]
Yes. That is what the warning is for. If you were trying to use a local variable before it existed it would be a hard error.

This is because often the default values of types aren't expected and will cause weird behavior. For example having an `@persist Owner:entity` and using that before setting it.

**Comment by Vurv78** [comment]
This isn't a bug

**Comment by Vurv78** [comment]
Yeah it doesn't.
