### ISSUE TITLE
E2 When using a duplicate key in a table, the value is not assigned correctly

### ISSUE THREAD

**Issue by ugskv** [wiremod/wire#2494]
Create this e2 chip several times
```
A = table("key1" = "1", "key1" = "2", "key1" = "3", "key2" = "1", "key2" = "2", "key2" = "3")
print("key1", A["key1", string])
print("key2", A["key2", string])
```

Output:
```
key1	1
key2	3
key1	1
key2	2
key1	3
key2	2
key1	2
key2	2
key1	2
key2	3
key1	1
key2	1
```

**Comment by Vurv78** [comment]
What behavior do you expect here? Ideally you shouldn't be allowed to have multiple of the same keys in a table declaration. But I can't do that since it'd break backwards compatibility (I was going to do it with the table creation syntax, though.)

Right now this is just because lua's `pairs` has an undefined order at which keys are selected.

**Comment by gbv6** [comment]
The values are expected to be 3 and 3

**Comment by Vurv78** [comment]
In what usecase are you even expecting the order of potentially duplicate keys at runtime (incredibly niche)?

This will hopefully be implemented with the dedicated table/array syntax, anyway, though.
