### ISSUE TITLE
Clientside console spam when wire rt screens are used

### ISSUE THREAD

**Issue by wrefgtzweve** [wiremod/wire#2507]
**Describe the bug**
`ImprovedRTCameras: material improvedrt_screen/monitor_.vmt does not exist on client for some reason!
Screen would not be rendered`  
spams console when rt screens are used.
![image](https://user-images.githubusercontent.com/69946827/205507573-3111b502-4903-4e97-9f25-14ff4a854ddd.png)
<https://github.com/wiremod/wire/blob/962a94edd63a6da17323ff725834eee1f4abcc3d/lua/entities/gmod_wire_rt_screen.lua#L178>

**To Reproduce**
1. Equip tool `gmod_wire_rt_screen`
2. Spawn screen
3. See console, should contain ~7x the error.

**Expected behavior**
No errors / messages in console.

**Comment by legokidlogan** [comment]
Whenever `wire_rt_screen_screenmaterial` is set to "`normal`" (the default value, and only option in the tool panel's dropdown list), something causes `path` to become an empty string, leading to an invalid material file path.

When `wire_rt_screen_screenmaterial` is set to some other value (such as "`test`"), the file path is correctly built, but also kinda not. It still errors (as expected due to giving it some random file name that doesn't exist), but instead of only getting paths for `monitor_test.vmt` as expected, it alternates between that and `monitor_.vmt` when spawned in.

![image](https://user-images.githubusercontent.com/26103433/207728728-027c5646-43c9-41a4-8315-d0fed5ddd723.png)

Additionally, setting `wire_rt_screen_screenmaterial` to anything other than "`normal`" will yield an error on the server, creating a world-owned entity.
```lua
addons/wire/lua/entities/gmod_wire_rt_screen.lua:119: bad argument #1 to 'pairs' (table expected, got no value)
   1.  <unknown> - [C]:-1
    2.  pairs - [C]:-1
     3.  Setup - addons/wire/lua/entities/gmod_wire_rt_screen.lua:119
      4.  MakeWireEnt - addons/wire/lua/wire/server/wirelib.lua:1015
       5.  MakeEnt - addons/wire/lua/wire/tool_loader.lua:65
        6.  LeftClick_Make - addons/wire/lua/wire/tool_loader.lua:56
         7.  LeftClick - addons/wire/lua/wire/tool_loader.lua:37
          8.  <unknown> - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:220
```

**Comment by legokidlogan** [comment]
Despite the errors, whenever the screenmat is normal, the screen will still render correctly once wired up like normal. It just briefly hits console with this mess when spawning the screen, with seemingly no other side effects.

**Comment by Aws0mee** [comment]
> The issue appeared after #2364

@InfHorus are you sure it only appeared after #2364? I swear I remember getting this message long before it, and this PR shouldn't cause anything like this as far as I'm aware.

**Comment by wrefgtzweve** [comment]
I don't get why it's printing at all, it adds nothing of value as it does render anyways.

**Comment by Aws0mee** [comment]
> I don't get why it's printing at all, it adds nothing of value as it does render anyways.

From my experience, the game would lag heavily and when it stopped lagging I would check my console and see those prints I never saw it render and still print the message.

**Comment by wrefgtzweve** [comment]
I never use the rt cameras, players on the servers i work on do. It usually just fills up my console with junk and sometimes just crams it full to a point where console is hard to use as can be seen in the provided screenshot.

**Comment by Periapsises** [comment]
I'm also getting this issue, I haven't used an RT camera either and it's just constantly printing
![image](https://user-images.githubusercontent.com/94928308/210273500-ab92dde8-6252-48f1-b093-a087e58ad7d0.png)
