### ISSUE TITLE
E2 Suggestion: Add option to setting menu to disable warnings.

### ISSUE THREAD

**Issue by ANormalTwig** [wiremod/wire#2525]
Title

**Comment by TomyLobo** [comment]
Should be a bit more fine-grained than just on/off

**Comment by Hazeofdream** [comment]
vurv on his way to saying "just fix your code"

**Comment by Vurv78** [comment]
For the hundredth time I've probably said this, the warnings aren't even pedantic, and the yellow line won't hurt you.

I am strongly against adding a way to disable them because of this (and since either I'd need to add some sort of indexing/localization for warnings in order to disable specific ones) and since disabling them entirely is just careless when they don't affect you at all.

If there's any unavoidable warnings (e.g. "Unused variable" in #include files that are meant to export variables), those should be fixed internally rather than having a toggle to remove warnings.

**Comment by shadowscion** [comment]
If it's really the hundredth time, this is probably not a well received addition to e2 at the moment. I know there are servers refusing to update wiremod because of it, and 'they don't affect you at all' seems like an equally valid reason to add a way to disable them.

**Comment by KemGus** [comment]
Why can't you make warnings smaller like in vs code?

**Comment by Vurv78** [comment]
Not sure what you mean by that

**Comment by KemGus** [comment]
![image](https://user-images.githubusercontent.com/42640259/211113748-793763b4-5dff-424c-bfbf-76ec7e72c97d.png)
@Vurv78

**Comment by Vurv78** [comment]
I never even knew that existed, which tells you everyone would ignore them if this was implemented

Either way, vscode does this because it underlines errors and warnings so you'd see them anyway, while the wire editor doesn't, so it needs the validation bar to show you any errors/warnings right now.

**Comment by ChewySpoon69** [comment]
just add it
