### ISSUE TITLE
Issue with egpSize and circleOutlines

### ISSUE THREAD

**Issue by skatingskelly** [wiremod/wire#2542]
Using egpSize on circleoutlines causes it to disappear if its an even circle or get stretched if its uneven

**Comment by Divran** [comment]
Lower the fidelity with `egpFidelity`. It determines the number of vertices the circle is built out of and it defaults to a pretty high number. Too many and each individual circle segment becomes too narrow to render, turning it invisible. This isn't an issue when egpSize is 1 (default) because then it uses an entirely different render method
