### ISSUE TITLE
Save bug with trigger tool and SPU tool

### ISSUE THREAD

**Issue by wolfestridershooter** [wiremod/wire#2552]
**Describe the bug:**
When you load a save game the trigger will have a non-intractable 1x1 phx cube around it and the SPU will spew 10 or 20 math physics props out of itself

**Steps To Reproduce**
1. Start a new game
2. Spawn a trigger and an SPU
3. Save the map
4. Load the map

**Expected behavior:**
No extra entities spawned when loading from a save

**Screenshots:**
![image](https://user-images.githubusercontent.com/47306808/226736354-2e2b353c-d538-4d20-9230-ee5f91d75cc2.png)
![image](https://user-images.githubusercontent.com/47306808/226736610-557b2fb3-922f-4a92-a99c-6a94a92e6b9e.png)

**Comment by Vurv78** [comment]
E2 isn't compatible with saves, I doubt the SPU is. Maybe someone else can chime in, but for me I'd just make it not work with saves at all.

**Comment by Denneisk** [comment]
This is because these entities spawn helper entities to achieve their intended effect. `gmsave` then saves them without discrimination.

I think Wire should reconsider save inclusiveness—E2s are perfectly compatible with saves, as are SPUs and triggers and most other Wire entities.

In a quick fix utilizing the code used in `lua/entities/gmod_wire_expression2/init.lua` , you can disable saving of `gmod_wire_trigger_entity` entities. I'd make a PR on more of these saving issues but I'm not sure the best way to approach them—there are only two entities that I know of that have this issue to begin with. SPUs use `prop_physics` which would require a slight modification but the logic remains the same.

**Comment by Vurv78** [comment]
I mean I took that stance thinking save support would be very involved and didn't want to bother looking into it since the amount of people using saves is minimal, if your PR works without issues, then there shouldn't be any problem supporting saves
