### ISSUE TITLE
Don't jump to warning on E2 validation

### ISSUE THREAD

**Issue by KemGus** [wiremod/wire#2574]
Whenever E2 isn't validated yet and you click on the validation button, it will immediately move your view to the line where warning is. So, the suggestion: it shouldn't move your view to the line where warning is, but instead keep it where it was

Also as another note: it would be nice to have an always running validation of E2, without having to click on the button.

**Comment by Vurv78** [comment]
> Whenever E2 isn't validated yet and you click on the validation button, it will immediately move your view to the line where warning is

This is intended behavior. Errors do this too. Originally this was the only way to find where the warnings were, but now that the problems tab exists the behavior can be changed if the majority of people feel it should not do that.

> Also as another note: it would be nice to have an always running validation of E2, without having to click on the button.

Seems like a good feature, although just saying if you don't know already you can use the validation keybind (ctrl + space) to validate as well instead of clicking the bar.

**Comment by KemGus** [comment]
Yeah, I know about this feature but I don't know what's the reason of not
having it update live

сб, 20 мая 2023 г., 07:33 Vurv ***@***.***>:

**Comment by Vurv78** [comment]
> Yeah, I know about this feature but I don't know what's the reason of not
having it update live

Probably for big chips, especially since the current compiler is kinda slow
