### ISSUE TITLE
egpPoly function can't draw concave polygons

### ISSUE THREAD

**Issue by BoggLog** [wiremod/wire#763]
Basically, if I made this poly
![polybug1](https://cloud.githubusercontent.com/assets/10134635/5511123/010ff01a-87db-11e4-967c-66b16d0ae8db.png)
I expect to get this
![polybug2](https://cloud.githubusercontent.com/assets/10134635/5511129/0ca5b338-87db-11e4-9df4-a2ccc384ede3.png)
but I'm getting this
![polybug3](https://cloud.githubusercontent.com/assets/10134635/5511136/19ebfc3c-87db-11e4-89d3-9af139c6c7a3.png)

here is a simple "paint"-thing to reproduce
```PHP
@name POLY_paint
@outputs Figure:array Click Clicked
@persist S:wirelink N
@trigger 

interval(100)

if(first()|dupefinished())
{
    findByClass("gmod_wire_egp")
    findSortByDistance(entity():pos())
    S = find():wirelink()
    S:egpClear()
    timer("s",1000)
}

Click=owner():keyUse()
Clicked=$Click&Click

if(Clicked & S:egpCursor(owner()))
{
    #create new point
    Figure:pushVector2(S:egpCursor(owner()))
    #create figure
    if(Figure:count()==3) { S:egpPolyOutline(1,Figure) S:egpColor(1,vec(255,0,0)) }
    #update figure
    else { S:egpAddVertices(1,Figure) }
}
    
if(clk("s"))
{
    timer("s",1000)
    N=!N
    if(N){S:egpPolyOutline(1,Figure)} else {S:egpPoly(1,Figure)}
}
```

**Comment by AbigailBuccaneer** [comment]
So I looked at this and it turns out that decomposing arbitrary polygons into convex ones is actually not a particularly simple task. I implemented something using [monotone polygons](http://en.wikipedia.org/wiki/Polygon_triangulation#Using_monotone_polygons) but it was much to complex to justify inclusion in EGP.

I haven't implemented [ear clipping](http://en.wikipedia.org/wiki/Polygon_triangulation#Ear_clipping_method), which is slower but simpler. I imagine we'd accept a pull request for a clean and simple implementation of polygon triangulation, but I don't have any time to work on this any further.

A better route may be to report this at [github.com/Facepunch/garrysmod-issues/issues](//github.com/Facepunch/garrysmod-issues/issues).

**Comment by Divran** [comment]
Easiest solution is to build your shape out of multiple other objects, such as circles and boxes.
