### ISSUE TITLE
Wire_AdjustOutputs only supports NORMAL type outputs.

### ISSUE THREAD

**Issue by mcd1992** [wiremod/wire#779]
`Wire_AdjustInputs` might be affected as well.

Any new outputs created with AdjustOutputs will ignore the [TYPE] specifier in the names or the types table.

Example:
Create an entity with `Wire_CreateOutputs(self, {"Test"})` in the initialize
Then later call `Wire_AdjustOutputs(ent, {"SomeEnt [ENTITY]"}, {"ENTITY"})`
The `"SomeEnt"` output will be a `NORMAL` instead of an `ENTITY`.

**Comment by mcd1992** [comment]
Calling WireLib.RetypeOutputs(self, "SomeEnt", "ENTITY") seems to properly set and network the type.

**Comment by Divran** [comment]
Please use `WireLib.AdjustOutputs`, since `Wire_` is old and should no longer be used. Only reason we still have them is for backwards compatibility. (Technically I should move all function definitions from `Wire_` to `WireLib` but that's unrelated to this issue)

Anyhow, I believe to adjust outputs with types, you need to use `WireLib.AdjustSpecialOutputs( ent, names, types [, descs] )`, because `WireLib.AdjustOutputs( ent, names [,descs] )` doesn't allow you to specify the types.

so this would be `WireLib.AdjustSpecialOutputs( ent, { "SomeEnt"}, { "ENTITY" } )`

**Comment by mcd1992** [comment]
Ah I didn't notice Wire_CreateInputs didn't was skipping the types paramter. Switching to directly calling methods off the WireLib table works just fine now. Thanks for the reply.

Would you like me to close this ticket or should I leave it open so it can be closed when the Wire_Create / Adjust functions are depricated?

**Comment by mcd1992** [comment]
Issue resolved, error on my part for using legacy functions.
