### ISSUE TITLE
Ranger Lua Error

### ISSUE THREAD

**Issue by thegrb93** [wiremod/wire#800]
I'm not sure what caused it but I got a lot of console spam.

```
[ERROR] addons/wire/lua/entities/gmod_wire_ranger.lua:249: attempt to perform arithmetic on field 'Value' (a userdata value)
  1. ShowOutput - addons/wire/lua/entities/gmod_wire_ranger.lua:249
   2. unknown - addons/wire/lua/entities/gmod_wire_ranger.lua:200
```

**Comment by AbigailBuccaneer** [comment]
[gmod_wire_ranger.lua:249](https://github.com/wiremod/wire/blob/1a9198caac3552f0f2d47120bc1e1f35ef2f9329/lua/entities/gmod_wire_ranger.lua#L249)

Somehow one of the Wire output fields has been set to a userdata value. That field is created [just like all the others](https://github.com/wiremod/wire/blob/1a9198caac3552f0f2d47120bc1e1f35ef2f9329/lua/entities/gmod_wire_ranger.lua#L82).

If you have any idea how to reproduce this, let us know - but when things like this happen the cause is usually "another addon messed with the fields in our entities".

**Comment by thegrb93** [comment]
I guess we can close this since I can't reproduce it.
