### ISSUE TITLE
ConVar issues

### ISSUE THREAD

**Issue by Bryantdl7** [wiremod/wire#878]
I don't know much about convars, all I know is I'm wondering if this is an error to show you guys.
ConVarRef wire_expression2_file_max_size doesn't point to an existing ConVar
ConVarRef wire_expression2_quotatick doesn't point to an existing ConVar
ConVarRef wire_expression2_quotahard doesn't point to an existing ConVar
ConVarRef wire_expression2_quotasoft doesn't point to an existing ConVar
ConVarRef wire_expression2_unlimited doesn't point to an existing ConVar

**Comment by Divran** [comment]
Sorry for not replying sooner. I guess I was busy at the time and then forgot about this.

Anyway, I'd guess that you have some kind of lua error in the file that creates these convars. Since this is so old, I'm going to assume you already solved it (since you didn't bump the issue when nobody replied), but if you're still having this problem, feel free to reopen.

**Comment by TomyLobo** [comment]
Since you can't reopen an issue we closed, just comment and we'll reopen it.
