### ISSUE TITLE
Clutch improvement

### ISSUE THREAD

**Issue by airidas338** [wiremod/wire#888]
As far as i know, current clutch working badly: linked props are clutched to controller model as main detail. Could you make that clutch would work between props that are linked only?

**Comment by Garbius** [comment]
It does only work between linked props. Can you provide any way to produce a scenario where it doesn't?

I am aware that this issue has not been touched in a while, but neither has the clutch. The latest commit was not related to this issue and the one before was in 2013.

**Comment by dvdvideo1234** [comment]
Hi, I was checking the wiremod source and noticed the following thing

The [code] related to the "gmod_wire_clutch.lua":

local function NewBallSocket( Ent1, Ent2, friction )
     local ballsocket = constraint.AdvBallsocket (......)
end

function ENT:SetClutchFriction( const, friction )
     local newconst = NewBallSocket( Ent1, Ent2, friction ) 
end
[/code]

As this thing does it that way, if the server ticks are quite apart from one another, there will be time for the source engine to apply gravity on the clutch, displacing it and glitching it out..

I noticed that the function http://wiki.garrysmod.com/page/constraint/AdvBallsocket
returns an [Entity] constraint.AdvBallsocket(......) when called by the "NewBallSocket" function

As is does, is it possible to call http://wiki.garrysmod.com/page/Entity/SetFriction  on that constraint, updating it instead of creating a new one?

**Comment by Divran** [comment]
What are you talking about? The source engine can't apply gravity in between ticks, because nothing at all can happen in between ticks. Server ticks is when the server does its calculations. It can't magically do calculations between ticks.
In addition, the old constraint is removed and the new constraint is created all in the same tick, so even if we had the problem you explained it still wouldn't apply here.

As for why it doesn't use `SetFriction`, I don't know. Maybe that function didn't exist when the clutch was created, or maybe the author of the clutch tried to use the function and it didn't work.

**Comment by dvdvideo1234** [comment]
Oh, that's the case then. I wander than it will work in the constrain entity ??
