### ISSUE TITLE
People getting stuck in Wired Keyboard

### ISSUE THREAD

**Issue by Ruuttu** [wiremod/wire#892]
So I published this contraption as a dupe on the steam workshop. It works and gets good feedback, but I also keep hearing that some people get stuck when using the Wired Keyboard, unable to leave.

Two things:
- I think the "Keyboard turned on - Press [..] to leave." message should somehow persist on screen for as long as the player is using the keyboard. It's probably quite easy to miss a small note in the chat, and in case of the synchronous keyboard (where the player can't move or do anything else) not knowing how to leave is a big problem.
- There still seem to be cases where people get stuck when the leave key just doesn't work. I'm not sure if it could be the way I'm using the keyboard with Expression 2, or if it's a general issue.

Related contraption: http://steamcommunity.com/sharedfiles/filedetails/?id=418474420

**Comment by TomyLobo** [comment]
Right now we're just displaying the message in the chat area and that's it.
The first issue can probably be addressed by having a derma dialog displaying the hint or something.
I'll make a PR for that.

As for the second issue, I've come to expect people to make wrong or exaggerated bug reports if other, conflicting problems exist.
If there's something obviously wrong in the code, that should be addressed.
Otherwise, let's fix the first thing and see if people still get stuck :)
