### ISSUE TITLE
Add E2 extension check to validator

### ISSUE THREAD

**Issue by oldmud0** [wiremod/wire#900]
I see many people on Workshop complaining that things like `setAng()` or `wirelink()` and such are "not working" for them and thus Wiremod is broken.

Instead of just saying, `function not found: extFunc()`, if the extension that contains the function is disabled, then the validator should say, `The extension for extFunc() named <extension> is disabled`.

**Comment by Divran** [comment]
We'd have to rewrite a lot of it for that to work. The functions are never even loaded at all when the extension is disabled, so there's currently no way for the E2 to know if a nonexistant function is in a disabled extension.

**Comment by edunad** [comment]
You could always use ifdef to check if the extension is there before using it on the code. Also if the extension is missing the code wont run what's inside ifdef

if(first()){
#ifdef entity:setAngle(angle)
    print("Extension found!")
    entity():setAngle(ang(10,10,10))
#else
    print("Extension not found!")
#endif   
}

**Comment by AbigailBuccaneer** [comment]
@edunad, the issue is that if a function is missing because it's in an extension and people who wrote the code didn't know it was in an extension, there's no real way of finding out why your code doesn't work.

Ideally the editor would put warning annotations on usages of extension functions that aren't behind an `#ifdef`. But that'd be a huge leap from where the editor is now.

**Comment by edunad** [comment]
I guess, the e2 helper could say if its custom or not (might help a bit)

**Comment by TomyLobo** [comment]
You would need several steps to make this happen:
1. create a "disabled" flag for functions
2. mark functions as disabled instead of not defining them at all
3. hack up the parser to throw a special kind of error for disabled functions
4. possibly catch the error in a different way (make the bar yellow or something, though that might prove really difficult to make meaningful in the face of hard errors beyond the "extension disabled" error)

**Comment by oldmud0** [comment]
Issue aged away.
