### ISSUE TITLE
Expression 2 after a "lua_reloadents"

### ISSUE THREAD

**Issue by Matspyder51** [wiremod/wire#914]
When we launch the "lua_reloadents" on the server console, all the entities was reloaded, but the Expression 2 with an EGP is completly broken, the only way to make the EGP rework is reboot the server

**Comment by Divran** [comment]
You shouldn't ever need to use lua_reloadents. If you're developing an addon or a gamemode or something, gmod has auto reloading. It will automatically reload the entity or file you are currently editing. Some addons, however don't work with the auto reloader feature in gmod. E2 is one of them, and that's why E2's wire_expression2_reload is useful if you want to develop something for E2, but again, you should never need to reload every single entity with lua_reloadents.

**Comment by Xandaros** [comment]
It also shouldn't break things.

**Comment by Matspyder51** [comment]
Yeah, but my server is on Linux and Gmod haven't auto reload on linux server, so sometimes, my players don't want a server reboot and when I modify files to fix a bug or something else, I need to reload entities or reboot the server

**Comment by Nebual** [comment]
This is not something WireTeam has plans to fix, as it does not concern the
vast majority of users. However, wiremod is open source, so feel free to
investigate the problem and make a pull request against our repo.

**Comment by TomyLobo** [comment]
lua_reloadents always broke E2
Has never been a big priority to fix it since it broke so many things in wiremod and other addons.

Some years ago, I wrote [lua_reloadent] (https://github.com/TomyLobo/lua_reloadent) to reload a single entity type, not all of them at once.
I haven't used it in a while and it's probably broken now.
There's a [pull request] (https://github.com/TomyLobo/lua_reloadent/pull/1) by @Donkie from 2013 that I never got around to evaluate and it's probably broken by now, too.

You can try fixing it if you want :)

**Comment by Divran** [comment]
guessing this can be closed
