### ISSUE TITLE
Expression2 chip cannot send data signal to itself

### ISSUE THREAD

**Issue by sven-hollstein** [wiremod/wire#916]
Can be tested with a minimal code sample:

```PHP
dsSendDirect("Name", entity(), 42)
if (dsClk("Name")){
    hint(dsGetNumber():toString(), 10)
}
```

**Comment by Divran** [comment]
Why would you want to

**Comment by sven-hollstein** [comment]
This used to work just fine, only later did I find out this is now intended functionality. It'd still be nice to have it back.
Personally I'd use this as a makeshift callback system. The only 'first-class' function support there is otherwise is 'calling' a string variable, which has quite a lot of limitations. This would be especially useful for handling events from library code that's been #include'd.

**Comment by Divran** [comment]
Calling a string variable has limitations that datasignals don't? Like what? Datasignals have way more limitations, not to mention they are way WAY more resource intensive to call

**Comment by thegrb93** [comment]
Maybe he has a framework designed to allow e2s to communicate with each other and in some cases the chip needs to communicate with itself. I never use datasignals so I'm just guessing.

**Comment by Nebual** [comment]
There's been a check in place since April 2012 https://github.com/wiremod/wire/commit/2f8e748151bae129d62ef0acd32c9164dc43d051#diff-2c043cedd54bd76a4d37f3cf98c4746cR53 , though we could probably remove it to no ill effect.

**Comment by Divran** [comment]
I don't see any situation where you need to send a signal to the E2 itself

Also if we erase that check, there's a possibility that sending a signal to a group that the E2 is itself in, will cause the E2 to receive its own signal, which we don't want. The only case where we MIGHT want this is in `dsSendDirect`, but like I said I can't see any situation where we want it there either. Datasignals wait 1 tick, and then execute the entire receiving E2. Not only are they slower than function calls, they are also much laggier. And they're no more versatile than just using a callable string.

Datasignals are for communicating with other E2s. Allowing them to make the E2 execute itself just promotes bad code.

**Comment by AbigailBuccaneer** [comment]
Computer networks are for communicating with other computers, but nobody claims it's bad practice to run a local HTTP server and then connect to it.

I'd say if an E2 is in a group and something sends a signal to that group, then the E2 should receive it - regardless if that E2 is the one that sent the signal or not. Adding this "no loopback" check is just another corner case, it makes things less simple in design.

**Comment by Divran** [comment]
Nothing wrong with it in a http server, but this is E2, and executing E2s is probably the most expensive operation there is.

**Comment by sven-hollstein** [comment]
To me, this seems to be analogous to explicitly disallowing 0 in addition. Yes, it's useless to add zero to something, but disallowing it just because you don't see a real use case is only going to trip up people expecting consistent behavior. If you're going to send a signal with dsSendDirect to an array of chips, and that array includes the sender, it'll just refuse to send the signal because there was a specific check in place to prevent loopback. This would make perfect sense if there was some technical limitation that would cause inevitable breakage when loopback occurs, but even then it'd be good practice to either alert the programmer through a console message, or clearly document the fact that loopback is NOT allowed.
I propose to remove the check, if only as a feature request. It'll get rid of a redundant branch in the logic, and it'll mean dsSendDirect will have consistent behavior.

**Comment by Divran** [comment]
The problem with your 0 addition analogy is that +0 is a really cheap operation compared to executing an E2.

There's also the thing where people are inevitably going to crash their own E2s because they placed their dsSendWhatever in the wrong place in their E2, causing the signal to send itself over and over, causing an infinite loop. But hey I guess they'll learn that the hard way, then.

`If you're going to send a signal with dsSendDirect to an array of chips, and that array includes the sender, it'll just refuse to send the signal because there was a specific check in place to prevent loopback.`
Pretty sure it will send the signal just fine to every other E2

`I propose to remove the check, if only as a feature request. It'll get rid of a redundant branch in the logic, and it'll mean dsSendDirect will have consistent behavior.`
Currently, the same logic is used for sending a signal to a group as when sending to a single E2. In fact, when sending to a group, it'll loop through all E2s in that group and use the same code as `dsSendDirect` on each of them. So this means that if we simply remove the check, it'll be removed for sending to groups as well as direct. Unless we add some "type" arguments to the function to check if the current signal is a group or a direct signal.

Very often, the E2 is going to be in the same group that it's sending to, and 99.99% of the time there's no need to send a signal to itself, and since executing an E2 is very expensive, it's good to avoid it. This is the main reason I'm against this. Why enable a feature that no one will ever use just to make it more "consistent", which would passively make datasignals much more laggy? As well as increase your E2's ops significantly, giving you less to work with.

Of course, as mentioned above, we could add a "type" argument to the code to make sure that only `dsSendDirect` has this feature. That way we avoid most of the problems I mentioned above. Then I wouldn't be against it as much.

**Comment by sven-hollstein** [comment]
Right, I see what you mean, dsSend to a group would cause the chip to self-trigger one tick later if it's in the same group as it's sending to, which is not going to be desired behavior in pretty much every case. Indeed, only dsSendDirect seems to be the odd one out when explicitly passing the sender as an argument will get rejected.
I have no issue with disallowing this by default. Even if that means the user has to jump through extra hoops to achieve self-triggering, that's only going to discourage its use if anything, and then it'll at least be there 'just in case'.

**Comment by oldmud0** [comment]
Remember the Linux principle: one should not restrict people from doing things for the sake of it. For example, if an end-user wants to do something crazy like run GParted on a dirty partition, then it is in the best interest for the GParted/fdisk/e2fs developers to add an override switch to allow the end-user to do this, as long as the end-user fully understands the consequences if this goes wrong.

Same goes for datasignals: when a scripter *explicitly* sends a signal to his own E2, then it is assumed that he knows what he is doing and this operation should be allowed at whatever cost. For any other case, however, this behavior should not be depended upon if the scripter is not aware of loopback behavior.

So scripters who want this specific behavior should be asked to override the restriction in their own scripts by saying something like `dsToggleLoopback(true)` at the beginning of their code.
