### ISSUE TITLE
Wire Cam not working

### ISSUE THREAD

**Issue by julsilagi** [wiremod/wire#920]
everytime when i spawn a contraption using wire cam it gives errors and dont load the cam vision

**Comment by Divran** [comment]
1. are these 5 year old dupes? that'd be why
2. how can you expect anyone to help you if you don't tell us which errors you got

**Comment by julsilagi** [comment]
its not a 5 year old dupe and it appear in the side like a note so i cant
copy it. Is it possible to me to se some kind of log?

2015-07-09 18:28 GMT-03:00 Divran <notifications@github.com>:

**Comment by oldmud0** [comment]
If it appears on the side and looks like a Lua error, shouldn't you also be finding it on the console?

**Comment by Dragman200** [comment]
Same problem here and im pretty sure a 5 year old didnt make drunk combine.

**Comment by thegrb93** [comment]
@Dragman200 That's not what they said.

**Comment by Divran** [comment]
@Dragman200 Drunk combine is old as shit. The cam controller has been completely rewritten from scratch since then. I've tried to make it backwards compatible, but I wasn't very successful. Sometimes you get errors with reeeeeally old dupes (or they just don't work). To fix it, you just have to delete the cam controller and create a new one, and wire it back up.
