### ISSUE TITLE
vonEncode stack overflow with recursive tables

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#923]
Following code

```
Parent=table()
Child=table()
Parent["Child",table]=Child
Child["Parent",table]=Parent
vonEncode(Parent)
```

crashes with stack overflow, while other functions, like printTable handle recursive tables just fine(by just printing the table reference if that table has been visited already [(Reference)](https://github.com/wiremod/wire/blob/082a58dd176e7e51c8a7a2f0a079e48917ffb132/lua/entities/gmod_wire_expression2/core/table.lua#L206)).
While recursive tables might seem useless at first glance, they are extremely useful to mandatory when building more complex data structes like bidirectionally traversable trees (tables can make a surprsingly useful replacement for objects). And not being able to save those to a file without stripping the recursions first is kind of annoing. And a stack overflow is always bad.

When fixing this, please make sure vonDecode can correctly decode it as well, else it would be useless.

**Comment by Divran** [comment]
Apparently the version of the von library that wiremod uses does not support recursive references. The latest version supports it, according to the author, but updating means all old von encoded files would stop working, since it's not backwards compatible.

The only other option would be to hack this in to the version of von that wiremod has... but effort

**Comment by TomyLobo** [comment]
cherry-pick it?

**Comment by Divran** [comment]
cherry-pick what?

**Comment by bigdogmat** [comment]
What does the new version of vON improve apon?

**Comment by Divran** [comment]
Everything

**Comment by bigdogmat** [comment]
I don't see much of a reason not to update it except if you saved something on a server with github version then tried to use it on one with the workshop version. Other than that not many people would have something they needed to convert, unless their is a way to convert old saved files to new ones.

**Comment by Divran** [comment]
You can't speak for everyone. I myself have 10-20 files that use von in my data folder. I would have to convert all of them, probably manually.

**Comment by bigdogmat** [comment]
As for why I brought up a way to convert them, though that would be too much work for little gain. I understand that a lot of people would lose things from this, even I would lose loads of leaderboard files.

**Comment by TomyLobo** [comment]
cherry-pick the patch for recursive stuff

**Comment by Xandaros** [comment]
https://github.com/vercas/vON/commit/1de75ea67cb6560efd25913b03657a06ad14bf0b

If only people made atomic commits...

**Comment by TomyLobo** [comment]
duly complained in a comment :)

**Comment by thegrb93** [comment]
I think vOn is backwards compatible. I remember when I upgraded mine and everything still worked. Test and make sure first.

**Comment by Xandaros** [comment]
It isn't. I updated the vON version in evolve and it broke.
Considering the version wiremod uses is very old, it is unlikely an update is going to be without anything breaking.

**Comment by thegrb93** [comment]
I updated vON version in evolve and it didn't break for me.

**Comment by oldmud0** [comment]
Why can't we just detect an old vON file and "migrate" it?

**Comment by bigdogmat** [comment]
According to this https://github.com/vercas/vON/commit/1de75ea67cb6560efd25913b03657a06ad14bf0b#commitcomment-12360960 we can upgrade to version 1.3.0 and still have backwards-compatibility.

**Comment by TomyLobo** [comment]
That thread has been going back and forth. Did someone actually make a meaningful test?

**Comment by bigdogmat** [comment]
I was just pointing out that he said they should be compatible, as that's what most of the discussion here was about. I can't test due to not having a computer with Gmod on it.

**Comment by Xandaros** [comment]
I see these three options:
- Ship two versions of von. If the newer version is unable to read it, try the old one. If that one can read, automatically serialise it again using the new one, thereby converting it.
  - Pro: We can use the newest version of von. With a system for migrations in place, it might even be possible to always use the newest version, even with breaking changes
  - Contra: We need to ship multiple versions of von. Probably indefinitely.
- Use the latest backward-compatible version. Which one that actually is, we need to figure out. (Presumably https://github.com/vercas/vON/commit/4001fcdca718f17fe71f6842b967e8713413596e)
  - Pro: We can keep going with a single version of von.
  - Contra: A lot of effort, since the version we end up using needs to be tested extensively. (Ideally exhaustively) We cannot use the latest version of von. I can confirm that it is not backwards-compatible.
- Keep everything as-is
  - Pro: Least effort. We keep the option to use a different solution at a later date.
  - Contra: We don't actually fix anything

Of course, we can also blindly update the newest version of von. That's what I did when I updated the version evolve uses.
For wiremod, this is probably not an option, though.

**Comment by vercas** [comment]
@Xandaros Why 1.3.3? 1.3.4 didn't bring any breaking changes. It actually fixed a pretty major bug.  
I highly recommend using the latest (no bugs reported with that one in 2 years!) with the suggested migration system.
It wouldn't be that hard... Just `(x)pcall` the latest version's deserialize function, and fall back to the old one on error. Serializing could be done exclusively with the latest version, but the users should be aware that the result string is very likely to be incompatible with old versions (of vON and Wiremod).  
A cheat-ish workaround would be to have entirely different functions in E2 to load (with fallback!) and save with the new version. Or perhaps specify a version as an argument?
This way, users will have to consciously use the newer version. Having in mind that most E2 users are developers, they shouldn't have a hard time understanding this.

**Comment by AbigailBuccaneer** [comment]
@TomyLobo I've added a unit test system to my branch of vON, and I intend to write a system to test serializations between two different versions.

**Comment by Nebual** [comment]
Assuming load_new(save_new(load_old('file.txt'))) == load_old('file.txt'), shipping two versions of Von sounds like the cleanest-to-users approach and doesn't cost us much. Its already what we do with Advdupe (though lets try to keep different versions of serializers in different files, folks)

**Comment by oldmud0** [comment]
Yes, that's the least creative solution of the lot but seems to accomplish the job just fine.
(Submodules anyone?)

**Comment by Xandaros** [comment]
@oldmud0 It might, if people were able to use them...
https://github.com/Xandaros/evolve/issues/132 https://github.com/Xandaros/evolve/issues/135 https://github.com/Xandaros/evolve/issues/124 https://github.com/Xandaros/evolve/issues/146 https://github.com/Xandaros/evolve/issues/137

**Comment by AbigailBuccaneer** [comment]
We can use subtrees rather than submodules - it's possible to create a commit which is a merge commit of `wiremod/master` and `vON/master`, and has the effect of adding/updating (some or all) of the files of vON in a subdirectory.

Combined with storing some metadata in the commit message, `git-subtree` can then do `git subtree update` etc. and it works Nearly Like Magic.

**Comment by oldmud0** [comment]
Nearly™
