### ISSUE TITLE
Updating somone elses E2 doesn't change owner

### ISSUE THREAD

**Issue by adosikas** [wiremod/wire#929]
Which is kinda bad if you open someones e2 and put stuff like concmd() inside, which can get exploited with something like concmd("say !rank EvilGuy Admin"), even if you were paranoid about your concmd whitelist, "say" is probably on it.
Given it requries an admin to give you PP rights and having a e2 out, but this is a kinda common situation. Say an admin want to share a e2 with you, but instead of rightlclicking it and just pressing save, you put in your code and upload it. I was not aware of that possibility and i don't even see the friendwrite option anymore to block it, nor any other way (exept of not trusting people at all).

Some ideas on how to fix it:
- Run that code as the uploads user
- Add back friendwrite option
- Don't run E2 when others upload it, just let it sit idle, so one can still see the edits, but they don't get run
- Show a message like: "E2 uploaded by EvilGuy.  [Execute E2] [Open in editor] [Block upload] [checkbox] Remember choice"

**Comment by Divran** [comment]
How would adding friendwrite back solve it? I don't actually fully remember how that old thing used to work. Didn't even realize it was gone because I never used it.

Sure your other solutions work, but
* Easiest fix it to ban the shit out of that guy
* Second easiest fix is to disable E2 concmd (there's an option in the options menu for that) when you add people you don't trust to prop protection

**Comment by adosikas** [comment]
1) doesn't work when you "ban yourself" after ranking him up. (all admin commands are accessible)
2) doesn't work when you don't even know there is this possibility of someone executing *their* code under *your* account

Adding back friendwrite would still allow sharing code while protecting against someone overwriting your E2 with potentially malicious code. You could still enable it when you WANT other people to edit your code.

**Comment by thegrb93** [comment]
There isn't a possibility of someone executing their code under your account unless you give them access.

**Comment by oldmud0** [comment]
E2 doesn't make any assumptions on code safety. Further security is expected only by complementing Wire with other protection-based addons.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by thegrb93** [comment]
Don't enable concmd, that's your code safety.

**Comment by Divran** [comment]
um
wat

**Comment by oldmud0** [comment]
Don't click the comment button too much, that's your spam safety.

**Comment by thegrb93** [comment]
Shit wtf. Fucking cell phone.

**Comment by FNCxPro** [comment]
I thought GitHub showed if you were on mobile lol

**Comment by Nebual** [comment]
Can anyone think of an argument against changing the owner when new code is
uploaded? That seems the most straightforward fix.

If you give someone write access to your chip, you're allowing them to
switch it from being an elevator controller to being an annoying hologram
generator, as well as allowing them to remove the chip and spawn a new one
in its place, so the ownership change seems like a reasonable way of
indicating whose code is spawning props or holograms or chat commands.

**Comment by Divran** [comment]
The only argument against that is that you sometimes don't actually want that to happen.

**Comment by Nebual** [comment]
Too bad, you let someone upload code, its no longer your chip. If you can't
convince them not to, why are they on your PP friends list?

**Comment by Divran** [comment]
That's not my argument. In my experience, the most common reason people want you to upload code to their E2 is to help them with it, and you still want it to be theirs when you're done helping them. Therefore changing ownership just adds extra steps, in those cases.

**Comment by oldmud0** [comment]
Maybe ownership change could be forced based on rank difference.

**Comment by TomyLobo** [comment]
I say deactivate this mess completely until we can think of a safe way.
There's duplicator to work around in the meantime.

**Comment by thegrb93** [comment]
Yeah but that is incredibly inconvenient. How about this:
1. Someone uploads code to another's e2
2. The uploaded code is not ran but stays as the current active code.
3. The owner is notified that someone modified their e2 and to open and reupload the e2 to apply the changes

**Comment by oldmud0** [comment]
* You are a user and you want to upload a new version of an E2 for your abusive admin with a few more features like random promotion. Heck no that's not going to happen, because there is a security clearance change. Your friend isn't admin? He will need to dupe the admin's E2, edit it, and then have the admin examine the changes himself. It's like forking, but with a tool gun.
* You are a user helping another fellow user. Upload will check prop protection before doing anything, then replace the E2 without changing owner. (Not entirely convinced that owner change would be useful/allowed in this case..)
* You are an admin tending to your flock of sheeple. Upload will allow you to overwrite the E2, but shift+upload would allow you to take ownership of the E2 :smiling_imp:

**Comment by thegrb93** [comment]
@oldmud0 
E2 shouldn't treat uploading differently based on the status of a user. I have no idea what your first point is trying to say.
>Also having edit access to the E2 implies that you are able to dislodge/disable the dupe protection

No it doesn't

**Comment by Divran** [comment]
I just had a genius idea that probably solves all of these problems. It's an addition to thegrb93's idea.
* Whenever anyone uploads code to an E2, a variable is set to that player's UUID.
* If the E2's UUID does not match the owner of the E2, ALL executions of the E2 are blocked, and the E2's owner is notified.
* The E2's owner can then open the E2, read it, and reupload it (or simply hit Reload with the E2 tool) to set the UUID variable to their own UUID, which would enable execution again.

* This has the bonus side effect of solving the problem with the "virus" E2 that has been floating around, which exploits area dupes. Because the person spawning the E2 would not be the same as the person pasting the dupe, the E2 wouldn't run, and the person pasting the dupe would be notified of its existence.

**Comment by thegrb93** [comment]
Sounds pretty good. Use SteamID64 though, UID can match across different players.

**Comment by Nebual** [comment]
Hmm, sounds like a fairly good solution...

So if I copy someone's base and paste it, I have to manually reload the 4
E2's in it to get them to run? Without nessisarily knowing where they are?
Setting a mandatory E2 invisible would thus effectively copyright protect a
vehicle from ever being duped... Which has been something my pesky users
have been clamouring for, but it does dampen the open source movement.

Perhaps a 'wire_expression2_executeprotection' default on server convar?

**Comment by Divran** [comment]
@thegrb93 UID can match across different players? But I thought it was called "unique" for a reason?

@Nebual there's always the remote updater. They can use that to reload all E2s without knowing where they are. I believe the remute updater has a "reload" button which does the same thing as hitting Reload with the toolgun.

**Comment by adosikas** [comment]
A potential problem OR feature i see with that solution would be that the popup comes up every time. 
Bad for users who don't know about wire or E2 and just want to paste cool stuff, and may be put off by a warning. 
Good for the dupe author who gets his id (and additionally the name too?) embedded into dupes so everyone who spawns them sees the credit.

Ofcourse the popup would stop in both cases when one restarts the E2 with their own id and re-saves the dupe, right?

**Comment by TomyLobo** [comment]
I'm all for minges getting put off mingy E2s they downloaded off the 'net

**Comment by Divran** [comment]
@adosikas yes, correct

**Comment by dvdvideo1234** [comment]
Isn't it easier for the first guy just to dupe the E2 he wants to edit. I am using this method for ages with my friends ...

**Comment by Divran** [comment]
>Isn't it easier for the first guy just to dupe the E2 he wants to edit. I am using this method for ages with my friends ...

that's completely unrelated to this issue

**Comment by TomyLobo** [comment]
The purpose of this issue isnt to make things easier but to make things harder.
Thus your remark is off-topic and I'm removing it and all replies to it

**Comment by Divran** [comment]
sigh, looks like we're gonna have to implement this soon http://www.wiremod.com/forum/off-topic/35235-another-crynet-e2-found.html#post290620

**Comment by AbigailBuccaneer** [comment]
**I HATE USERS**

**Comment by BoggLog** [comment]
> I HATE USERS

You just cook 'em wrong xD

**Comment by thegrb93** [comment]
I don't remember, but why not set self.player to whoever uploaded the code?
