### ISSUE TITLE
ZCPU in future

### ISSUE THREAD

**Issue by its-suun** [wiremod/wire#971]
What will happen to ZCPU? It's full of bugs and unfinished implementations and the developer of it isn't active anymore.
The bugs will stay there forever if nobody will fix them. Wiremod itself is a good maintainable addon, but the unfinished zcpu code will just lie in it.
There are some (~5?) users, but most of them don't report bugs, because they know nobody will fix them.
I would like to help zcpu/gpu, but not when BP is the only (and inactive) developer of it. I can't be bothered to wait long (or never) for merging a PR.
If nothing happens then in my opinion zcpu should get out of wiremod and get in a spererate addon.

Sorry for my bad english

**Comment by oldmud0** [comment]
Wiremod is stale. Some consider it a completed project; there are no more major features we could add without placing Wire's stability at risk. Others have left to finish college, publish their papers, or whatever.

Since we are so underhanded, none of us want to do big code reviews and testing before versions are released to ensure that pull requests don't break or interact with each other. Sure, there are bugs everywhere since GMod 13, but as long as nobody reports them they will persist.

Splitting ZCPU won't help neither Wire nor ZCPU, because then only those 5 users will be able to maintain the code, and Wire users then have to download ZCPU separately.

The best way to start helping is to learn a bit about the ZCPU code base to propose solutions to make it easier for somebody else that is good at coding to apply your solution to the code itself.
***
I have an idea: why don't we start *The Great Bug Hunt of 2015*? The aim of the bug hunt would be to bump up stability since the breaking changes of GM13. 

Now it sounds like this was a long time ago, but the truth is that Garry continues to add and break things in the API, transitioning from how things were done in GM12. For example, [a UTF-8 library](https://github.com/garrynewman/garrysmod/pull/943) was added recently to GMod in the September update. We could use that, and it could fix some bugs. A bunch of new API getters were also added, which means that we have to check if we still need certain hacks to check for entity properties.

So we have 2 goals:

1. Pinpoint bugs and weird UI issues.
2. Remove unnecessary code.

I wish I could help with this, but my other projects - and school - are in the way, and I can't really predict the future to find out if my load will be smaller in the future.

**Comment by suunrider** [comment]
Black Phoenix is the only maintainer of ZCPU, so every change is determined by BP. It would be better to have a more active maintainer.
Those 5 ZCPU Users won't mantain to the code, because they can't due the inactivity of the maintainer.
Putting ZCPU out of wiremod would help by having one problem less.

**Comment by AbigailBuccaneer** [comment]
A drive to get people to fix up ZCPU would be good, if you could get people enthused about it.

For a long time I've wanted to refactor the ZCPU parser/compiler - they work in weirdly incremental ways so that parsing and compiling could happen over multiple frames, but it makes the code dirtier and could be replaced with coroutines.

**Comment by suunrider** [comment]
> So we have 2 goals:

>    1. Pinpoint bugs and weird UI issues.
>    2. Remove unnecessary code.

To 1. : There are already enough issues reported on Github. First those should get fixed before any bug hunt should get started.
To 2. : https://github.com/wiremod/wire/pull/943

**Comment by TomyLobo** [comment]
coroutines work now?
they didn't work for years

**Comment by Pharap** [comment]
Sorry if this topic's a bit dead, but I don't get why people are afraid of touching ZCPU/ZGPU, it's just a processor emulator written in lua. Kind of like a NES emulator but with a different instruction set and the graphics chip is less crazy.

I think the best way to get people using the CPU again would be to give it some proper documentation. The wiki is a bit unloved and most tutorials miss important features. Currently the only way to get the full feature set is to read the source code's opcode listing, which most casual users won't want to be doing.

Personally I think the register naming was a bit of a mistake, x86 may be the most common form of assembly but that's because of legacy code, not because it's the easiest to learn (ARM is way better in my opinion). But it's too late for removing old features, all you can do is fix what's there and add new stuff.

**Comment by thegrb93** [comment]
Cpu is useless but its fun to learn because assembly is interesting. After I wrote my first zcpu program I never touched it again. https://www.youtube.com/watch?v=3dMYWgm9Zgo

**Comment by Pharap** [comment]
Personally I find the GPU to be more usable than the EGP because you don't have to keep track of loads of indices, you just draw as you would with a normal graphics API like OpenGL. My only issue with it is that I haven't found a way to make circle outlines or polylines. I might see if I can add those as a new opcode at some point.

**Comment by thegrb93** [comment]
Yeah gpu is nice, but I could never figure out how to get it to communicate with the server-side cpu, which egp excels at. Maybe the version I used was broken.

**Comment by Pharap** [comment]
I haven't tried getting the GPU and CPU communicating yet since I've only had wiremod for a week. I know it involves hooking busses up correctly.

From what I've seen so far I think E2 is definately easier to use than the CPU, but they're probably better suited for different tasks. E2 has much better documentation as well, which probably doesn't help the CPU's case.

(So far all I've done with the EGP and GPU is write a program designed to mimic the SG1 dialling computer from Stargate SG1 so I can use it with the CAT stargate mod. I found a way to add CAT's glyph fonts to the EGP and GPU.)

**Comment by suunrider** [comment]
I'm currently working on the whole wiremod wiki (at [wiremod_wiki](https://github.com/suunrider/wiremod_wiki)) which takes some time to finish. If you want some ZCPU documentation before i finished the wiki, look at [ZCPU Documentation](http://suunrider.bplaced.net/gmod/zcpu_doc/ZCPU%20Documentation.htm).
Also @Pharap if you want to try out zcpu, download the wiremod verson from github. The workshop version is outdated and many zcpu bugs got fixed after workshop update.

**Comment by Garbius** [comment]
I'm one of the ~5. The best documentation used to be the one on BP's site. It's no longer present, but I have the source if anyone wants to host it. I was going to myself, but... well.. I haven't. 

A possible path of development would be to rebuild the VM as a binary module to expand its niche to also include performance. This, however, would require a lot of effort to build and, more importantly, secure.

**Comment by TomyLobo** [comment]
a binary module is probably not going to happen.
I don't remember all the arguments against it, but one of them is user acceptance.
Also keep in mind that GPU/SPU run on the client. We can't send binaries to the clients (I hope)

**Comment by bigdogmat** [comment]
> We can't send binaries to the clients (I hope)

we can't

**Comment by oldmud0** [comment]
If you're going to make a binary module (how many times have we talked about this...), *please* make it optional. I'm not going to have a server force me to download a special fork of the "Wiremod DLL" that turns out to contain malware.

**Comment by Divran** [comment]
We've talked about this many times. We will not include binaries in wiremod. If you want to do this you'll have to make your own,  completely separate, addon.

**Comment by TomyLobo** [comment]
call it ZCPU Accelerator... XP!

**Comment by AbigailBuccaneer** [comment]
It probably is worth thinking about having a well-defined ZVM interface so a separate binary module could replace the Lua implementation - but it's not something we're ever likely to focus on ourselves, because it is still a very niche part of Wiremod.
